/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Ported from: lib/src/ast/node.dart
 * Original: Copyright (c) 2016 Google Inc.
 * Original license: MIT
 *
 * Migration notes:
 *   Renames: node.dart -> AstNode.scala
 *   Convention: Dart abstract interface class -> Scala trait
 *   Idiom: _FakeAstNode -> FakeAstNode private class with lazy callback
 *
 * Covenant: full-port
 * Covenant-dart-reference: lib/src/ast/node.dart
 * Covenant-verified: 2026-04-26
 *
 * upstream-commit: ec85871864ca16f8045e66ad329bd462e791bfa1
 */
package ssg
package sass
package ast

import ssg.sass.util.FileSpan

/** A node in an abstract syntax tree.
  *
  * Note: although all nodes have `toString` methods that generally reflect their source text, these methods should only be used for debugging and not for creating Sass source code. They aren't tested
  * and are not guaranteed to remain stable over time.
  */
trait AstNode {

  /** The source span associated with the node.
    *
    * This indicates where in the source Sass or SCSS stylesheet the node was defined.
    */
  def span: FileSpan
}

object AstNode {

  /** Creates an [AstNode] that doesn't have any data and whose span is generated by [callback].
    *
    * A number of APIs take AstNodes instead of spans because computing spans eagerly can be expensive. This allows arbitrary spans to be passed to those callbacks while still being lazily computed.
    */
  def fake(callback: () => FileSpan): AstNode = new FakeAstNode(callback)

  /** An AstNode that just exposes a single span generated by a callback. */
  final private class FakeAstNode(callback: () => FileSpan) extends AstNode {
    lazy val span: FileSpan = callback()
  }
}
