# Do not commit changes to this file!
# Change it locally, reload build in IDE, and develop.
# Consider running: git update-index --assume-unchanged dev.properties
# You can undo it by: git update-index --no-assume-unchanged dev.properties

# Allowed: 3
ide.scala = 3
# Allowed: jvm, js, native
ide.platform = jvm
