/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Ported from: flexmark-ext-toc/src/main/java/com/vladsch/flexmark/ext/toc/internal/SimTocNodeFormatter.java
 * Original: Copyright (c) 2016-2023 Vladimir Schneider
 * Original license: BSD-2-Clause
 *
 * Migration notes:
 *   Renames: com.vladsch.flexmark.ext.toc.internal → ssg.md.ext.toc.internal
 *   Convention: Scala 3, Nullable[A], no return
 *   Idiom: match instead of switch, boundary/break for early exit
 *
 * Covenant: full-port
 * Covenant-java-reference: flexmark-ext-toc/src/main/java/com/vladsch/flexmark/ext/toc/internal/SimTocNodeFormatter.java
 * Covenant-verified: 2026-04-26
 */
package ssg
package md
package ext
package toc
package internal

import ssg.md.Nullable
import ssg.md.ast.Heading
import ssg.md.ast.util.HeadingCollectingVisitor
import ssg.md.formatter.*
import ssg.md.util.data.DataHolder

import scala.language.implicitConversions

class SimTocNodeFormatter(dataOptions: DataHolder) extends NodeFormatter {

  private val options:       TocOptions       = TocOptions.fromOptions(dataOptions, true)
  private val formatOptions: TocFormatOptions = new TocFormatOptions(dataOptions)

  override def getNodeClasses: Nullable[Set[Class[?]]] = Nullable.empty

  override def getNodeFormattingHandlers: Nullable[Set[NodeFormattingHandler[?]]] =
    Nullable(
      Set[NodeFormattingHandler[?]](
        new NodeFormattingHandler[SimTocBlock](classOf[SimTocBlock], (node, ctx, md) => render(node, ctx, md)),
        new NodeFormattingHandler[SimTocContent](classOf[SimTocContent], (node, ctx, md) => renderContent(node, ctx, md))
      )
    )

  private def render(node: SimTocBlock, context: NodeFormatterContext, markdown: MarkdownWriter): Unit =
    formatOptions.updateOnFormat match {
      case SimTocGenerateOnFormat.REMOVE =>
        val simTocPrefix = TocUtils.getSimTocPrefix(options, this.options)
        markdown.append(simTocPrefix)
        if (options.isBlankLineSpacer) markdown.blankLine()

      case SimTocGenerateOnFormat.UPDATE =>
        val visitor  = new HeadingCollectingVisitor()
        val headings = visitor.collectAndGetHeadings(context.getDocument)
        if (headings != null) { // @nowarn - Java interop: may be null
          val optionsParser = new SimTocOptionsParser()
          val parsed        = optionsParser.parseOption(node.style, this.options, Nullable.empty)
          var tocOpts       = parsed.first.get

          if (node.title.isNotNull) {
            tocOpts = tocOpts.withTitle(node.title.unescape())
          }

          val simTocPrefix = TocUtils.getSimTocPrefix(tocOpts, this.options)
          markdown.append(simTocPrefix)
          if (tocOpts.isBlankLineSpacer) markdown.blankLine()

          renderTocHeaders(markdown, headings, tocOpts)
        }

      case SimTocGenerateOnFormat.AS_IS =>
        markdown.openPreFormatted(false).append(node.chars).closePreFormatted()
    }

  private def renderTocHeaders(markdown: MarkdownWriter, headings: java.util.List[Heading], tocOpts: TocOptions): Unit = {
    val filteredHeadings = TocUtils.filteredHeadings(headings, tocOpts)
    val paired           = TocUtils.markdownHeaderTexts(filteredHeadings, tocOpts)
    TocUtils.renderTocContent(markdown, tocOpts, this.options, paired.first.get, paired.second.get)
  }

  private def renderContent(node: SimTocContent, context: NodeFormatterContext, markdown: MarkdownWriter): Unit = {
    // SimTocContent renders as empty — its content is generated by the parent SimTocBlock render
  }
}

object SimTocNodeFormatter {

  class Factory extends NodeFormatterFactory {
    override def create(options: DataHolder): NodeFormatter = new SimTocNodeFormatter(options)
  }
}
