/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-751.
 * Ported from: terser/test/compress/issue-751.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue751Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // negate_booleans_1
  // =========================================================================
  test("negate_booleans_1".fail) {
    assertCompresses(
      input = "var a = !a || !b || !c || !d || !e || !f",
      expected = "var a = !(a && b && c && d && e && f)",
      options = AllOff.copy(
        comparisons = true
      )
    )
  }

  // =========================================================================
  // negate_booleans_2
  // =========================================================================
  test("negate_booleans_2") {
    assertCompresses(
      input = """var match = !x &&       // should not touch this one
            (!z || c) &&
            (!k || d) &&
            the_stuff()""".stripMargin.trim,
      expected = """var match = !x &&
            (!z || c) &&
            (!k || d) &&
            the_stuff()""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true
      )
    )
  }

}
