/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for new.
 * Ported from: terser/test/compress/new.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressNewSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // new_with_assignement_expression
  // =========================================================================
  test("new_with_assignement_expression") {
    assertCompresses(
      input = """var a;
        new x(a = 5 * 2, b = [1, 2, 3], c = {a: "a", b: "b", cd: "c" + "d"});
        new y([a, b] = [3, 4])""".stripMargin.trim,
      expected = """var a;
        new x(a = 10, b = [1, 2, 3], c = {a: "a", b: "b", cd: "cd"});
        new y([a, b] = [3, 4])""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true
      )
    )
  }

  // =========================================================================
  // new_pure
  // =========================================================================
  test("new_pure".fail) {
    assertCompresses(
      input = """new function() {};
        (new function() {
            this.pass = () => console.log("PASS");
        }).pass()""".stripMargin.trim,
      expected = """(new function() {
            this.pass = () => console.log("PASS");
        }).pass()""".stripMargin.trim,
      options = AllOff.copy(
        pureNew = true
      )
    )
  }

}
