/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for logical-assignment.
 * Ported from: terser/test/compress/logical-assignment.js (6 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ ToplevelConfig }

final class CompressLogicalAssignmentSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // prematurely_evaluate_assignment
  // =========================================================================
  test("prematurely_evaluate_assignment") {
    assertCompresses(
      input = """var or = null
        var null_coalesce = null
        var and = 'FAIL'

        or ||= 'PASS'
        null_coalesce ??= 'PASS'
        and &&= 'PASS'

        console.log(or, null_coalesce, and)""".stripMargin.trim,
      expected = """var or = null
        var null_coalesce = null
        var and = 'FAIL'

        or ||= 'PASS'
        null_coalesce ??= 'PASS'
        and &&= 'PASS'

        console.log(or, null_coalesce, and)""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // prematurely_evaluate_assignment_inv
  // =========================================================================
  test("prematurely_evaluate_assignment_inv") {
    assertCompresses(
      input = """var or = 'PASS'
        var null_coalesce = 'PASS'
        var and = 'FAIL'

        or ||= 'FAIL'
        null_coalesce ??= 'FAIL'
        and &&= 'PASS'

        console.log(or, null_coalesce, and)""".stripMargin.trim,
      expected = """var or = 'PASS'
        var null_coalesce = 'PASS'
        var and = 'FAIL'

        or ||= 'FAIL'
        null_coalesce ??= 'FAIL'
        and &&= 'PASS'

        console.log(or, null_coalesce, and)""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // assign_in_conditional_part
  // =========================================================================
  test("assign_in_conditional_part".fail) {
    assertCompresses(
      input = """var status = 'PASS'
        var nil = null
        var nil_prop = { prop: null }

        nil &&= console.log(status = 'FAIL')
        nil_prop.prop &&= console.log(status = 'FAIL')

        console.log(status)""".stripMargin.trim,
      expected = """var status = 'PASS';
        var nil = null;

        nil &&= console.log(status = 'FAIL');
        ({prop: null}).prop &&= console.log(status = 'FAIL');

        console.log(status)""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // assign_in_conditional_part_reused
  // =========================================================================
  test("assign_in_conditional_part_reused") {
    assertCompresses(
      input = """var status = 'PASS'
        var nil = null
        var nil_prop = { prop: null }

        nil &&= console.log(status = 'FAIL')
        nil_prop.prop &&= console.log(status = 'FAIL')

        console.log(status, nil, nil_prop.prop)""".stripMargin.trim,
      expected = """var status = 'PASS'
        var nil = null
        var nil_prop = { prop: null }

        nil &&= console.log(status = 'FAIL')
        nil_prop.prop &&= console.log(status = 'FAIL')

        console.log(status, nil, nil_prop.prop)""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // assignment_in_left_part
  // =========================================================================
  test("assignment_in_left_part".fail) {
    assertCompresses(
      input = """var status = 'FAIL'
        var x = {}

        x[status = 'PASS'] ||= 1

        console.log(status)""".stripMargin.trim,
      expected = "",
      options = AllOff.copy(
        evaluate = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // assignment_in_left_part_2
  // =========================================================================
  test("assignment_in_left_part_2".fail) {
    assertCompresses(
      input = """var status = 'FAIL'
        var x = {'PASS': false}

        x[status = id('PASS')] ||= 'PASS'

        console.log(status, x.PASS)""".stripMargin.trim,
      expected = """var status;
        var x = {'PASS': false}

        x[status = id('PASS')] ||= 'PASS'

        console.log(status, x.PASS)""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

}
