/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-t120.
 * Ported from: terser/test/compress/issue-t120.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ InlineLevel }

final class CompressIssueT120Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // pr_152_regression
  // =========================================================================
  test("pr_152_regression".fail) {
    assertCompresses(
      input = """(function(root, factory) {
            root.CryptoJS = factory();
        })(this, function() {
            var CryptoJS = CryptoJS || function(Math) {
                var C = {};
                C.demo = function(n) {
                    return Math.ceil(n);
                };
                return C;
            }(Math);
            return CryptoJS;
        });
        var result = this.CryptoJS.demo(1.3);
        console.log(result)""".stripMargin.trim,
      expected = """(function(root) {
            var CryptoJS;
            root.CryptoJS = CryptoJS = CryptoJS || function(Math) {
                var C = {
                    demo: function(n) {
                        return Math.ceil(n);
                    }
                };
                return C;
            }(Math);
        })(this);
        var result = this.CryptoJS.demo(1.3);
        console.log(result)""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        evaluate = true,
        inline = InlineLevel.InlineFull,
        joinVars = true,
        loops = true,
        passes = 1,
        reduceVars = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

}
