/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for expansions.
 * Ported from: terser/test/compress/expansions.js (5 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressExpansionsSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // avoid_spread_in_ternary
  // =========================================================================
  test("avoid_spread_in_ternary") {
    assertCompresses(
      input = """function print(...x) {
            console.log(...x);
        }
        var a = [1, 2], b = [3, 4], m = Math;

        if (m)
            print(a);
        else
            print(b);

        if (m)
            print(...a);
        else
            print(b);

        if (m.no_such_property)
            print(a);
        else
            print(...b)""".stripMargin.trim,
      expected = """function print(...x) {
            console.log(...x);
        }
        var a = [ 1, 2 ], b = [ 3, 4 ], m = Math;
        print(m ? a : b);
        m ? print(...a) : print(b);
        m.no_such_property ? print(a) : print(...b)""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        conditionals = true,
        evaluate = true
      )
    )
  }

  // =========================================================================
  // object_spread_regression
  // =========================================================================
  test("object_spread_regression") {
    assertCompresses(
      input = """const x = () => {
            let o = { ...{} }
        }""".stripMargin.trim,
      expected = """const x = () => {
            let o = {}
        }""".stripMargin.trim,
      options = AllOff.copy(
        hoistProps = true
      )
    )
  }

  // =========================================================================
  // object_spread_constant
  // =========================================================================
  test("object_spread_constant".fail) {
    assertCompresses(
      input = """id({
            ...null,
            ...undefined,
            ...true,
            ...void 0,
            ...!0,
            ...~"foo",
            .../baz/,
            ...-/baz2/,

            // Several unary prefixes
            ...!!0,
            ...~!-+0,
            ...void !1,
            ...!~"foo",
            ...+!/foo/,
            ...!!!!!!!null,
            ...!~void +-42,

            ..."bar",
        })""".stripMargin.trim,
      expected = """id({
            ..."bar"
        })""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = false
      )
    )
  }

  // =========================================================================
  // object_spread_inline_after_dropping_undefined
  // =========================================================================
  test("object_spread_inline_after_dropping_undefined".fail) {
    assertCompresses(
      input = """let o = { ...undefined, ...{a: true} }
        id(o)""".stripMargin.trim,
      expected = """let o = {a: true};
        id(o)""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // object_spread_inline_after_dropping_null
  // =========================================================================
  test("object_spread_inline_after_dropping_null".fail) {
    assertCompresses(
      input = """let o = { ...null, ...{a: true} }
        id(o)""".stripMargin.trim,
      expected = """let o = {a: true};
        id(o)""".stripMargin.trim,
      options = AllOff
    )
  }

}
