/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1041.
 * Ported from: terser/test/compress/issue-1041.js (3 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue1041Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // const_declaration
  // =========================================================================
  test("const_declaration") {
    assertCompresses(
      input = "const goog = goog || {}",
      expected = "const goog = goog || {}",
      options = AllOff.copy(
        evaluate = true
      )
    )
  }

  // =========================================================================
  // const_pragma
  // =========================================================================
  test("const_pragma") {
    assertCompresses(
      input = "/** @const */ var goog = goog || {}",
      expected = "var goog = goog || {}",
      options = AllOff.copy(
        evaluate = true,
        reduceFuncs = true,
        reduceVars = true
      )
    )
  }

  // =========================================================================
  // not_const
  // =========================================================================
  test("not_const") {
    assertCompresses(
      input = "var goog = goog || {}",
      expected = "var goog = goog || {}",
      options = AllOff.copy(
        evaluate = true,
        reduceFuncs = true,
        reduceVars = true
      )
    )
  }

}
