/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-597.
 * Ported from: terser/test/compress/issue-597.js (4 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue597Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // NaN_and_Infinity_must_have_parens
  // =========================================================================
  test("NaN_and_Infinity_must_have_parens") {
    assertCompresses(
      input = """Infinity.toString();
        NaN.toString()""".stripMargin.trim,
      expected = """(1/0).toString();
        NaN.toString()""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // NaN_and_Infinity_should_not_be_replaced_when_they_are_redefined
  // =========================================================================
  test("NaN_and_Infinity_should_not_be_replaced_when_they_are_redefined") {
    assertCompresses(
      input = """var Infinity, NaN;
        Infinity.toString();
        NaN.toString()""".stripMargin.trim,
      expected = """var Infinity, NaN;
        Infinity.toString();
        NaN.toString()""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // NaN_and_Infinity_must_have_parens_evaluate
  // =========================================================================
  test("NaN_and_Infinity_must_have_parens_evaluate".fail) {
    assertCompresses(
      input = """(123456789 / 0).toString();
        (+"foo").toString()""".stripMargin.trim,
      expected = """(1/0).toString();
        NaN.toString()""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true
      )
    )
  }

  // =========================================================================
  // NaN_and_Infinity_should_not_be_replaced_when_they_are_redefined_evaluate
  // =========================================================================
  test("NaN_and_Infinity_should_not_be_replaced_when_they_are_redefined_evaluate".fail) {
    assertCompresses(
      input = """var Infinity, NaN;
        (123456789 / 0).toString();
        (+"foo").toString()""".stripMargin.trim,
      expected = """var Infinity, NaN;
        (1/0).toString();
        (0/0).toString()""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true
      )
    )
  }

}
