/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for sequences.
 * Ported from: terser/test/compress/sequences.js (43 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ ToplevelConfig }

final class CompressSequencesSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // make_sequences_1
  // =========================================================================
  test("make_sequences_1".fail) {
    assertCompresses(
      input = """foo();
        bar();
        baz()""".stripMargin.trim,
      expected = "foo(),bar(),baz()",
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // make_sequences_2
  // =========================================================================
  test("make_sequences_2".fail) {
    assertCompresses(
      input = """if (boo) {
            foo();
            bar();
            baz();
        } else {
            x();
            y();
            z();
        }""".stripMargin.trim,
      expected = """if (boo) foo(),bar(),baz();
        else x(),y(),z()""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // make_sequences_3
  // =========================================================================
  test("make_sequences_3".fail) {
    assertCompresses(
      input = """function f() {
            foo();
            bar();
            return baz();
        }
        function g() {
            foo();
            bar();
            throw new Error();
        }""".stripMargin.trim,
      expected = """function f() {
            return foo(), bar(), baz();
        }
        function g() {
            throw foo(), bar(), new Error();
        }""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // make_sequences_4
  // =========================================================================
  test("make_sequences_4".fail) {
    assertCompresses(
      input = """x = 5;
        if (y) z();

        x = 5;
        for (i = 0; i < 5; i++) console.log(i);

        x = 5;
        for (; i < 5; i++) console.log(i);

        x = 5;
        switch (y) {}

        x = 5;
        with (obj) {}""".stripMargin.trim,
      expected = """if (x = 5, y) z();
        for (x = 5, i = 0; i < 5; i++) console.log(i);
        for (x = 5; i < 5; i++) console.log(i);
        switch (x = 5, y) {}
        with (x = 5, obj)""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // lift_sequences_1
  // =========================================================================
  test("lift_sequences_1".fail) {
    assertCompresses(
      input = """var foo, x, y, bar;
        foo = !(x(), y(), bar())""".stripMargin.trim,
      expected = """var foo, x, y, bar;
        x(), y(), foo = !bar()""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // lift_sequences_2
  // =========================================================================
  test("lift_sequences_2".fail) {
    assertCompresses(
      input = """var foo = 1, bar;
        foo.x = (foo = {}, 10);
        bar = (bar = {}, 10);
        console.log(foo, bar)""".stripMargin.trim,
      expected = """var foo = 1, bar;
        foo.x = (foo = {}, 10),
        bar = {}, bar = 10,
        console.log(foo, bar)""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // lift_sequences_3
  // =========================================================================
  test("lift_sequences_3".fail) {
    assertCompresses(
      input = """var x, foo, bar, baz;
        x = (foo(), bar(), baz()) ? 10 : 20""".stripMargin.trim,
      expected = """var x, foo, bar, baz;
        foo(), bar(), x = baz() ? 10 : 20""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // lift_sequences_4
  // =========================================================================
  test("lift_sequences_4") {
    assertCompresses(
      input = """var x, foo, bar, baz;
        x = (foo, bar, baz)""".stripMargin.trim,
      expected = """var x, foo, bar, baz;
        x = baz""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // lift_sequences_5
  // =========================================================================
  test("lift_sequences_5".fail) {
    assertCompresses(
      input = """var a = 2, b;
        a *= (b, a = 4, 3);
        console.log(a)""".stripMargin.trim,
      expected = """var a = 2, b;
        b, a *= (a = 4, 3),
        console.log(a)""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // lift_sequences_6
  // =========================================================================
  test("lift_sequences_6".fail) {
    assertCompresses(
      input = """var a = 2;
        a &&= (leak(), a = 4, 3);
        console.log(a)""".stripMargin.trim,
      expected = """var a = 2;
        a &&= (leak(), a = 4, 3),
        console.log(a)""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // for_sequences
  // =========================================================================
  test("for_sequences".fail) {
    assertCompresses(
      input = """// 1
        foo();
        bar();
        for (; false;);
        // 2
        foo();
        bar();
        for (x = 5; false;);
        // 3
        x = (foo in bar);
        for (; false;);
        // 4
        x = (foo in bar);
        for (y = 5; false;);
        // 5
        x = function() {
            foo in bar;
        };
        for (y = 5; false;)""".stripMargin.trim,
      expected = """// 1
        for (foo(), bar(); false;);
        // 2
        for (foo(), bar(), x = 5; false;);
        // 3
        x = (foo in bar);
        for (; false;);
        // 4
        x = (foo in bar);
        for (y = 5; false;);
        // 5
        for (x = function() {
            foo in bar;
        }, y = 5; false;)""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // limit_1
  // =========================================================================
  test("limit_1".fail) {
    assertCompresses(
      input = """a;
        b;
        c;
        d;
        e;
        f;
        g;
        h;
        i;
        j;
        k""".stripMargin.trim,
      expected = """a, b, c;
        d, e, f;
        g, h, i;
        j, k""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 3
      )
    )
  }

  // =========================================================================
  // limit_2
  // =========================================================================
  test("limit_2".fail) {
    assertCompresses(
      input = """a, b;
        c, d;
        e, f;
        g, h;
        i, j;
        k""".stripMargin.trim,
      expected = """a, b, c, d;
        e, f, g, h;
        i, j, k""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 3
      )
    )
  }

  // =========================================================================
  // negate_iife_for
  // =========================================================================
  test("negate_iife_for".fail) {
    assertCompresses(
      input = """(function() {})();
        for (i = 0; i < 5; i++) console.log(i);
        (function() {})();
        for (; i < 10; i++) console.log(i)""".stripMargin.trim,
      expected = """for (!function() {}(), i = 0; i < 5; i++) console.log(i);
        for (!function() {}(); i < 10; i++) console.log(i)""".stripMargin.trim,
      options = AllOff.copy(
        negateIife = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // iife
  // =========================================================================
  test("iife".fail) {
    assertCompresses(
      input = """x = 42;
        (function a() {})();
        !function b() {}();
        ~function c() {}();
        +function d() {}();
        -function e() {}();
        void function f() {}();
        typeof function g() {}()""".stripMargin.trim,
      expected = """x = 42, function a() {}(), function b() {}(), function c() {}(),
        function d() {}(), function e() {}(), function f() {}(), function g() {}()""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // unsafe_undefined
  // =========================================================================
  test("unsafe_undefined".fail) {
    assertCompresses(
      input = """function f(undefined) {
            if (a)
                return b;
            if (c)
                return d;
        }
        function g(undefined) {
            if (a)
                return b;
            if (c)
                return d;
            e();
        }""".stripMargin.trim,
      expected = """function f(undefined) {
            return a ? b : c ? d : undefined;
        }
        function g(undefined) {
            return a ? b : c ? d : void e();
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true,
        unsafeUndefined = true
      )
    )
  }

  // =========================================================================
  // issue_1685
  // =========================================================================
  test("issue_1685".fail) {
    assertCompresses(
      input = """var a = 100, b = 10;
        function f() {
            var a = (a--, delete a && --b);
        }
        f();
        console.log(a, b)""".stripMargin.trim,
      expected = """var a = 100, b = 10;
        function f() {
            var a = (a--, delete a && --b);
        }
        f();
        console.log(a, b)""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // func_def_1
  // =========================================================================
  test("func_def_1".fail) {
    assertCompresses(
      input = """function f() {
            return f = 0, !!f;
        }
        console.log(f())""".stripMargin.trim,
      expected = """function f() {
            return !!(f = 0);
        }
        console.log(f())""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // func_def_2
  // =========================================================================
  test("func_def_2".fail) {
    assertCompresses(
      input = """console.log(function f() {
            return f = 0, !!f;
        }())""".stripMargin.trim,
      expected = """console.log(function f() {
            return f = 0, !!f;
        }())""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // func_def_3
  // =========================================================================
  test("func_def_3".fail) {
    assertCompresses(
      input = """function f() {
            function g() {}
            return g = 0, !!g;
        }
        console.log(f())""".stripMargin.trim,
      expected = """function f() {
            function g() {}
            return !!(g = 0);
        }
        console.log(f())""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // func_def_4
  // =========================================================================
  test("func_def_4".fail) {
    assertCompresses(
      input = """function f() {
            function g() {
                return g = 0, !!g;
            }
            return g();
        }
        console.log(f())""".stripMargin.trim,
      expected = """function f() {
            function g() {
                return !!(g = 0);
            }
            return g();
        }
        console.log(f())""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // func_def_5
  // =========================================================================
  test("func_def_5".fail) {
    assertCompresses(
      input = """function f() {
            return function g(){
                return g = 0, !!g;
            }();
        }
        console.log(f())""".stripMargin.trim,
      expected = """function f() {
            return function g(){
                return g = 0, !!g;
            }();
        }
        console.log(f())""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_1758
  // =========================================================================
  test("issue_1758".fail) {
    assertCompresses(
      input = """console.log(function(c) {
            var undefined = 42;
            return function() {
                c--;
                c--, c.toString();
                return;
            }();
        }())""".stripMargin.trim,
      expected = """console.log(function(c) {
            var undefined = 42;
            return function() {
                return c--, c--, void c.toString();
            }();
        }())""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // delete_seq_1
  // =========================================================================
  test("delete_seq_1".fail) {
    assertCompresses(
      input = """console.log(delete (1, undefined));
        console.log(delete (1, void 0));
        console.log(delete (1, Infinity));
        console.log(delete (1, 1 / 0));
        console.log(delete (1, NaN));
        console.log(delete (1, 0 / 0))""".stripMargin.trim,
      expected = """console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0)""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // delete_seq_2
  // =========================================================================
  test("delete_seq_2".fail) {
    assertCompresses(
      input = """console.log(delete (1, 2, undefined));
        console.log(delete (1, 2, void 0));
        console.log(delete (1, 2, Infinity));
        console.log(delete (1, 2, 1 / 0));
        console.log(delete (1, 2, NaN));
        console.log(delete (1, 2, 0 / 0))""".stripMargin.trim,
      expected = """console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0)""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // delete_seq_3
  // =========================================================================
  test("delete_seq_3".fail) {
    assertCompresses(
      input = """console.log(delete (1, 2, undefined));
        console.log(delete (1, 2, void 0));
        console.log(delete (1, 2, Infinity));
        console.log(delete (1, 2, 1 / 0));
        console.log(delete (1, 2, NaN));
        console.log(delete (1, 2, 0 / 0))""".stripMargin.trim,
      expected = """console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0)""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        keepInfinity = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // delete_seq_4
  // =========================================================================
  test("delete_seq_4".fail) {
    assertCompresses(
      input = """function f() {}
        console.log(delete (f(), undefined));
        console.log(delete (f(), void 0));
        console.log(delete (f(), Infinity));
        console.log(delete (f(), 1 / 0));
        console.log(delete (f(), NaN));
        console.log(delete (f(), 0 / 0))""".stripMargin.trim,
      expected = """function f() {}
        console.log((f(), !0)),
        console.log((f(), !0)),
        console.log((f(), !0)),
        console.log((f(), !0)),
        console.log((f(), !0)),
        console.log((f(), !0))""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // delete_seq_5
  // =========================================================================
  test("delete_seq_5".fail) {
    assertCompresses(
      input = """function f() {}
        console.log(delete (f(), undefined));
        console.log(delete (f(), void 0));
        console.log(delete (f(), Infinity));
        console.log(delete (f(), 1 / 0));
        console.log(delete (f(), NaN));
        console.log(delete (f(), 0 / 0))""".stripMargin.trim,
      expected = """function f() {}
        console.log((f(), !0)),
        console.log((f(), !0)),
        console.log((f(), !0)),
        console.log((f(), !0)),
        console.log((f(), !0)),
        console.log((f(), !0))""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        keepInfinity = true,
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // delete_seq_6
  // =========================================================================
  test("delete_seq_6".fail) {
    assertCompresses(
      input = """var a;
        console.log(delete (1, a))""".stripMargin.trim,
      expected = """var a;
        console.log(!0)""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // side_effects
  // =========================================================================
  test("side_effects".fail) {
    assertCompresses(
      input = "0, a(), 1, b(), 2, c(), 3",
      expected = "a(), b(), c()",
      options = AllOff.copy(
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // side_effects_cascade_1
  // =========================================================================
  test("side_effects_cascade_1".fail) {
    assertCompresses(
      input = """function f(a, b) {
            a -= 42;
            if (a < 0) a = 0;
            b.a = a;
        }""".stripMargin.trim,
      expected = """function f(a, b) {
            (a -= 42) < 0 && (a = 0), b.a = a;
        }""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        conditionals = true,
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // side_effects_cascade_2
  // =========================================================================
  test("side_effects_cascade_2") {
    assertCompresses(
      input = """function f(a, b) {
            b = a,
            !a + (b += a) || (b += a),
            b = a,
            b;
        }""".stripMargin.trim,
      expected = """function f(a, b) {
            b = a,
            !a + (b += a) || (b += a),
            b = a;
        }""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // side_effects_cascade_3
  // =========================================================================
  test("side_effects_cascade_3".fail) {
    assertCompresses(
      input = """function f(a, b) {
            "foo" ^ (b += a),
            b ? false : (b = a) ? -1 : (b -= a) - (b ^= a),
            a-- || !a,
            a;
        }""".stripMargin.trim,
      expected = """function f(a, b) {
            !(b += a) && ((b = a) || (b -= a, b ^= a)),
            a--;
        }""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        conditionals = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_27
  // =========================================================================
  test("issue_27".fail) {
    assertCompresses(
      input = """(function(jQuery) {
            var $$;
            $$ = jQuery;
            $$("body").addClass("foo");
        })(jQuery)""".stripMargin.trim,
      expected = """(function(jQuery) {
            jQuery("body").addClass("foo");
        })(jQuery)""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        passes = 2,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // reassign_const
  // =========================================================================
  test("reassign_const".fail) {
    assertCompresses(
      input = """function f() {
            const a = 1;
            a++;
            return a;
        }
        console.log(f())""".stripMargin.trim,
      expected = """function f() {
            const a = 1;
            return a++, a;
        }
        console.log(f())""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_2062
  // =========================================================================
  test("issue_2062".fail) {
    assertCompresses(
      input = """var a = 1;
        if ([ a || a++ + a--, a++ + a--, a && a.var ]);
        console.log(a)""".stripMargin.trim,
      expected = """var a = 1;
        a || (a++, a--), a++, --a && a.var;
        console.log(a)""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        collapseVars = true,
        conditionals = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_2313
  // =========================================================================
  test("issue_2313".fail) {
    assertCompresses(
      input = """var a = 0, b = 0;
        var foo = {
            get c() {
                a++;
                return 42;
            },
            set c(c) {
                b++;
            },
            d: function() {
                this.c++;
                if (this.c) console.log(a, b);
            }
        }
        foo.d()""".stripMargin.trim,
      expected = """var a = 0, b = 0;
        var foo = {
            get c() {
                return a++, 42;
            },
            set c(c) {
                b++;
            },
            d: function() {
                if (this.c++, this.c) console.log(a, b);
            }
        }
        foo.d()""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // cascade_assignment_in_return
  // =========================================================================
  test("cascade_assignment_in_return".fail) {
    assertCompresses(
      input = """function f(a, b) {
            return a = x(), b(a);
        }""".stripMargin.trim,
      expected = """function f(a, b) {
            return b(x());
        }""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // hoist_defun
  // =========================================================================
  test("hoist_defun".fail) {
    assertCompresses(
      input = """x();
        function f() {}
        y()""".stripMargin.trim,
      expected = """function f() {}
        x(), y()""".stripMargin.trim,
      options = AllOff.copy(
        joinVars = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // hoist_decl
  // =========================================================================
  test("hoist_decl") {
    assertCompresses(
      input = """var a;
        w();
        var b = x();
        y();
        for (var c; 0;) z();
        var d""".stripMargin.trim,
      expected = """var a;
        w();
        var b = x(), c, d;
        for (y(); 0;) z()""".stripMargin.trim,
      options = AllOff.copy(
        joinVars = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // for_init_var
  // =========================================================================
  test("for_init_var") {
    assertCompresses(
      input = """var a = "PASS";
        (function() {
            var b = 42;
            for (var c = 5; c > 0;) c--;
            a = "FAIL";
            var a;
        })();
        console.log(a)""".stripMargin.trim,
      expected = """var a = "PASS";
        (function() {
            for (var b = 42, c = 5, a; c > 0;) c--;
            a = "FAIL";
        })();
        console.log(a)""".stripMargin.trim,
      options = AllOff.copy(
        joinVars = true,
        unused = false
      )
    )
  }

  // =========================================================================
  // forin
  // =========================================================================
  test("forin") {
    assertCompresses(
      input = """var o = [];
        o.push("PASS");
        for (var a in o)
            console.log(o[a])""".stripMargin.trim,
      expected = """var o = [];
        for (var a in o.push("PASS"), o)
            console.log(o[a])""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // forin_assignment
  // =========================================================================
  test("forin_assignment") {
    assertCompresses(
      input = """var o = [], a = {};
        o.push("PASS");
        for (a.b in o)
            console.log(o[a.b])""".stripMargin.trim,
      expected = """var o = [], a = {};
        for (a.b in o.push("PASS"), o)
            console.log(o[a.b])""".stripMargin.trim,
      options = AllOff.copy(
        sequencesLimit = 200
      )
    )
  }

}
