/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for switch.
 * Ported from: terser/test/compress/switch.js (109 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressSwitchSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // constant_switch_1
  // =========================================================================
  test("constant_switch_1".fail) {
    assertCompresses(
      input = """switch (1+1) {
          case 1: foo(); break;
          case 1+1: bar(); break;
          case 1+1+1: baz(); break;
        }""".stripMargin.trim,
      expected = "bar()",
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // constant_switch_2
  // =========================================================================
  test("constant_switch_2".fail) {
    assertCompresses(
      input = """switch (1) {
          case 1: foo();
          case 1+1: bar(); break;
          case 1+1+1: baz();
        }""".stripMargin.trim,
      expected = """foo();
        bar()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // constant_switch_3
  // =========================================================================
  test("constant_switch_3".fail) {
    assertCompresses(
      input = """switch (10) {
          case 1: foo();
          case 1+1: bar(); break;
          case 1+1+1: baz();
          default:
            def();
        }""".stripMargin.trim,
      expected = "def()",
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // constant_switch_4
  // =========================================================================
  test("constant_switch_4".fail) {
    assertCompresses(
      input = """switch (2) {
          case 1:
            x();
            if (foo) break;
            y();
            break;
          case 1+1:
            bar();
          default:
            def();
        }""".stripMargin.trim,
      expected = """bar();
        def()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // constant_switch_5
  // =========================================================================
  test("constant_switch_5".fail) {
    assertCompresses(
      input = """switch (1) {
          case 1:
            x();
            if (foo) break;
            y();
            break;
          case 1+1:
            bar();
          default:
            def();
        }""".stripMargin.trim,
      expected = """// the break inside the if ruins our job
        // we can still get rid of irrelevant cases.
        switch (1) {
          case 1:
            x();
            if (foo) break;
            y();
        }
        // XXX: we could optimize this better by inventing an outer
        // labeled block, but that's kinda tricky.""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // constant_switch_6
  // =========================================================================
  test("constant_switch_6".fail) {
    assertCompresses(
      input = """OUT: {
            foo();
            switch (1) {
              case 1:
                x();
                if (foo) break OUT;
                y();
              case 1+1:
                bar();
                break;
              default:
                def();
            }
        }""".stripMargin.trim,
      expected = """OUT: {
            foo();
            x();
            if (foo) break OUT;
            y();
            bar();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // constant_switch_7
  // =========================================================================
  test("constant_switch_7".fail) {
    assertCompresses(
      input = """OUT: {
            foo();
            switch (1) {
              case 1:
                x();
                if (foo) break OUT;
                for (var x = 0; x < 10; x++) {
                    if (x > 5) break; // this break refers to the for, not to the switch; thus it
                                      // shouldn't ruin our optimization
                    console.log(x);
                }
                y();
              case 1+1:
                bar();
                break;
              default:
                def();
            }
        }""".stripMargin.trim,
      expected = """OUT: {
            foo();
            x();
            if (foo) break OUT;
            for (var x = 0; x < 10; x++) {
                if (x > 5) break;
                console.log(x);
            }
            y();
            bar();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // constant_switch_8
  // =========================================================================
  test("constant_switch_8".fail) {
    assertCompresses(
      input = """OUT: switch (1) {
          case 1:
            x();
            for (;;) break OUT;
            y();
            break;
          case 1+1:
            bar();
          default:
            def();
        }""".stripMargin.trim,
      expected = """OUT: {
            x();
            for (;;) break OUT;
            y();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // constant_switch_9
  // =========================================================================
  test("constant_switch_9".fail) {
    assertCompresses(
      input = """OUT: switch (1) {
          case 1:
            x();
            for (;;) if (foo) break OUT;
            y();
          case 1+1:
            bar();
          default:
            def();
        }""".stripMargin.trim,
      expected = """OUT: {
            x();
            for (;;) if (foo) break OUT;
            y();
            bar();
            def();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // drop_default_1
  // =========================================================================
  test("drop_default_1".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar': baz();
          default:
        }""".stripMargin.trim,
      expected = "if (foo === \"bar\") baz()",
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // drop_default_2
  // =========================================================================
  test("drop_default_2".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar': baz(); break;
          default:
            break;
        }""".stripMargin.trim,
      expected = "if (foo === \"bar\") baz()",
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // keep_default
  // =========================================================================
  test("keep_default".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar': baz();
          default:
            something();
            break;
        }""".stripMargin.trim,
      expected = """if (foo === 'bar') baz();
        something()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // remove_switch_1
  // =========================================================================
  test("remove_switch_1".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 1:
            1;
          case 2:
            invariant();
          case 3:
          default:
            doSomething();
        }
        function invariant() {
            /* production build */
        }""".stripMargin.trim,
      expected = """foo;
        doSomething()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_2
  // =========================================================================
  test("remove_switch_2".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 1:
            doSomething();
            break;
          default:
            doSomething();
            break;
        }""".stripMargin.trim,
      expected = """foo;
        doSomething()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_3
  // =========================================================================
  test("remove_switch_3".fail) {
    assertCompresses(
      input = """switch (foo) {
          default:
            doSomething();
            break;
          case 1:
            doSomething();
            break;
        }""".stripMargin.trim,
      expected = """foo;
        doSomething()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_4
  // =========================================================================
  test("remove_switch_4".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 1:
            doSomething();
            break;
          default:
            doSomething();
            break;
          case 2:
            doSomething();
            break;
        }""".stripMargin.trim,
      expected = """foo;
        doSomething()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_5
  // =========================================================================
  test("remove_switch_5".fail) {
    assertCompresses(
      input = """switch (foo) {
          case "bar":
            doSomething();
            break;
          default:
            doSomething();
            break;
          case "qux":
            doSomething();
            break;
        }""".stripMargin.trim,
      expected = """foo;
        doSomething()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_6
  // =========================================================================
  test("remove_switch_6".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 1:
            doSomething();
            break;
          default:
            doSomething();
            break;
          case 2:
            doSomething();
        }""".stripMargin.trim,
      expected = """foo;
        doSomething()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_7
  // =========================================================================
  test("remove_switch_7".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            doSomething();
            break;
          default:
            doSomething();
            break;
          case qux:
            doSomething();
            break;
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
          case qux:
        }
        doSomething()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_8
  // =========================================================================
  test("remove_switch_8".fail) {
    assertCompresses(
      input = """function test(foo) {
            switch (foo) {
              case 1:
                return 1;
              case 2:
              default:
              case 3:
            }
        }

        console.log(test(1))""".stripMargin.trim,
      expected = """console.log(function (foo) {
            if (foo === 1) return 1;
        }(1))""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_9
  // =========================================================================
  test("remove_switch_9".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 1:
            doSomethting();
            break;
          case 2:
          default:
            break;
          case 3:
        }""".stripMargin.trim,
      expected = "if (foo === 1) doSomethting()",
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_10
  // =========================================================================
  test("remove_switch_10".fail) {
    assertCompresses(
      input = """switch (1) {
          case 0:
            var x = 1;
          case bar():
          default:
          case bar():
          case 1:
            console.log(x);
        }
        function bar() {}""".stripMargin.trim,
      expected = """var x;
        switch (1) {
          case bar():
          case bar():
        }
        console.log(x);
        function bar() {}""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_11
  // =========================================================================
  test("remove_switch_11".fail) {
    assertCompresses(
      input = """switch (1) {
          case 0:
            var x = 1;
          case 1:
            console.log(x);
        }""".stripMargin.trim,
      expected = """var x;
        console.log(x)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_12
  // =========================================================================
  test("remove_switch_12".fail) {
    assertCompresses(
      input = """switch (1) {
          case 0:
            var x = 1;
          case foo():
            console.log('foo');
          case 1:
            console.log(x);
        }
        function foo() {}""".stripMargin.trim,
      expected = """if (1 === foo()) {
            var x;
            console.log('foo');
        }
        console.log(x);
        function foo() {}""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_13
  // =========================================================================
  test("remove_switch_13".fail) {
    assertCompresses(
      input = """switch (1) {
          case 0:
            var x = 1;
          case foo():
            console.log('foo');
            break;
          case 1:
            console.log(x);
        }
        function foo() {}""".stripMargin.trim,
      expected = """if (1 === foo()) {
            var x;
            console.log('foo');
        } else console.log(x);
        function foo() {}""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_14
  // =========================================================================
  test("remove_switch_14".fail) {
    assertCompresses(
      input = """function test(foo) {
            var x = 1;
            switch (foo) {
              case 0:
              case 1:
              default:
              case x--:
                console.log(x);
            }
        }
        test(0);
        test(1);
        test(2)""".stripMargin.trim,
      expected = """function test(foo) {
            var x = 1;
            switch (foo) {
              case 0:
              case 1:
              case x--:
            }
            console.log(x);
        }
        test(0);
        test(1);
        test(2)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_15
  // =========================================================================
  test("remove_switch_15".fail) {
    assertCompresses(
      input = """function test(foo) {
            var x = 1;
            switch (foo) {
              case 0:
              default:
              case x--:
                console.log(x);
            }
        }
        test(0);
        test(1);
        test(2)""".stripMargin.trim,
      expected = """function test(foo) {
            var x = 1;
            switch (foo) {
              case 0:
              case x--:
            }
            console.log(x);
        }
        test(0);
        test(1);
        test(2)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // remove_switch_16
  // =========================================================================
  test("remove_switch_16".fail) {
    assertCompresses(
      input = """function test(foo) {
            var x = 1;
            switch (foo) {
              case 0:
              default:
              case x--:
            }
            console.log(x);
        }
        test(0);
        test(1);
        test(2)""".stripMargin.trim,
      expected = """function test(foo) {
            var x = 1;
            switch (foo) {
              case 0:
              case x--:
            }
            console.log(x);
        }
        test(0);
        test(1);
        test(2)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_1
  // =========================================================================
  test("collapse_into_default_1".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar':
            bar();
          case 'baz':
            baz();
          case 'qux':
          default:
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case 'bar':
            bar();
          case 'baz':
            baz();
          default:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_2
  // =========================================================================
  test("collapse_into_default_2".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar':
            bar();
          case 'baz':
            baz();
          default:
          case 'qux':
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case 'bar':
            bar();
          case 'baz':
            baz();
          default:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_3
  // =========================================================================
  test("collapse_into_default_3".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case qux:
          default:
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case qux:
          default:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_4
  // =========================================================================
  test("collapse_into_default_4".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          default:
          case qux:
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          default:
          case qux:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_5
  // =========================================================================
  test("collapse_into_default_5".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case 'qux':
          case qux:
          default:
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case 'qux':
          case qux:
          default:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_6
  // =========================================================================
  test("collapse_into_default_6".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case qux:
          case 'qux':
          default:
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case qux:
          default:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_7
  // =========================================================================
  test("collapse_into_default_7".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          default:
          case 'qux':
          case qux:
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          default:
          case 'qux':
          case qux:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_8
  // =========================================================================
  test("collapse_into_default_8".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          default:
          case qux:
          case 'qux':
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          default:
          case qux:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_9
  // =========================================================================
  test("collapse_into_default_9".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case 'qux':
          default:
          case qux:
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case 'qux':
          default:
          case qux:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_10
  // =========================================================================
  test("collapse_into_default_10".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case qux:
          default:
          case 'qux':
            other();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case baz:
            baz();
          case qux:
          default:
            other();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_11
  // =========================================================================
  test("collapse_into_default_11".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case 'qux':
          case qux:
          default:
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case 'qux':
          case qux:
          default:
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_12
  // =========================================================================
  test("collapse_into_default_12".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case qux:
          case 'qux':
          default:
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case qux:
          case 'qux':
          default:
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_13
  // =========================================================================
  test("collapse_into_default_13".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          default:
          case 'qux':
          case qux:
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          default:
          case 'qux':
          case qux:
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_14
  // =========================================================================
  test("collapse_into_default_14".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          default:
          case qux:
          case 'qux':
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          default:
          case qux:
          case 'qux':
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_15
  // =========================================================================
  test("collapse_into_default_15".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case 'qux':
          default:
          case qux:
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case 'qux':
          default:
          case qux:
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_16
  // =========================================================================
  test("collapse_into_default_16".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case qux:
          default:
          case 'qux':
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case qux:
          default:
          case 'qux':
            other();
          case 'baz':
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_17
  // =========================================================================
  test("collapse_into_default_17".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case 'qux':
          case qux:
          default:
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case 'qux':
          case qux:
          default:
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_18
  // =========================================================================
  test("collapse_into_default_18".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case qux:
          case 'qux':
          default:
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case qux:
          case 'qux':
          default:
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_19
  // =========================================================================
  test("collapse_into_default_19".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          default:
          case 'qux':
          case qux:
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          default:
          case 'qux':
          case qux:
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_20
  // =========================================================================
  test("collapse_into_default_20".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          default:
          case qux:
          case 'qux':
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          default:
          case qux:
          case 'qux':
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_21
  // =========================================================================
  test("collapse_into_default_21".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case 'qux':
          default:
          case qux:
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case 'qux':
          default:
          case qux:
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // collapse_into_default_22
  // =========================================================================
  test("collapse_into_default_22".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            bar();
          case qux:
          default:
          case 'qux':
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
            bar();
          case qux:
          default:
          case 'qux':
            other();
          case baz:
            baz();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        module = true,
        reduceVars = true,
        sideEffects = true,
        switches = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // issue_1663
  // =========================================================================
  test("issue_1663".fail) {
    assertCompresses(
      input = """var a = 100, b = 10;
        function f() {
            switch (1) {
              case 1:
                b = a++;
                return ++b;
              default:
                var b;
            }
        }
        f();
        console.log(a, b)""".stripMargin.trim,
      expected = """var a = 100, b = 10;
        function f() {
            var b;
            b = a++;
            return ++b;
        }
        f();
        console.log(a, b)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // drop_case
  // =========================================================================
  test("drop_case".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar': baz(); break;
          case 'moo':
            break;
        }""".stripMargin.trim,
      expected = "if (foo === 'bar') baz()",
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // drop_case_2
  // =========================================================================
  test("drop_case_2".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar': bar(); break;
          case 'moo':
          case moo:
          case 'baz':
            break;
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case 'bar': bar();
          case 'moo':
          case moo:
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // keep_case
  // =========================================================================
  test("keep_case".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar': baz(); break;
          case moo:
            break;
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case 'bar': baz();
          case moo:
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // if_else
  // =========================================================================
  test("if_else".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar':
            bar();
            break;
          default:
            other();
        }""".stripMargin.trim,
      expected = """if (foo === 'bar') bar();
        else other()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // if_else2
  // =========================================================================
  test("if_else2".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar':
            bar();
          default:
            other();
        }""".stripMargin.trim,
      expected = """if (foo === 'bar') bar();
        other()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // if_else3
  // =========================================================================
  test("if_else3".fail) {
    assertCompresses(
      input = """switch (foo) {
          default:
            other();
            break;
          case 'bar':
            bar();
        }""".stripMargin.trim,
      expected = """if (foo === 'bar') bar();
        else other()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // if_else4
  // =========================================================================
  test("if_else4".fail) {
    assertCompresses(
      input = """switch (foo) {
          default:
            other();
          case 'bar':
            bar();
        }""".stripMargin.trim,
      expected = """if (foo !== 'bar') other();
        bar()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // if_else5
  // =========================================================================
  test("if_else5".fail) {
    assertCompresses(
      input = """switch (1) {
          case bar:
            bar();
            break;
          case 1:
            other();
        }""".stripMargin.trim,
      expected = """if (1 === bar) bar();
      else {
          1;
          other();
      }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // if_else6
  // =========================================================================
  test("if_else6".fail) {
    assertCompresses(
      input = """switch (1) {
          case bar:
            bar();
          case 1:
            other();
        }""".stripMargin.trim,
      expected = """if (1 === bar) bar();
        1;
        other()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // if_else7
  // =========================================================================
  test("if_else7".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 'bar':
            break;
            bar();
          default:
            other();
        }""".stripMargin.trim,
      expected = """if (foo === 'bar');
        else other()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // if_else8
  // =========================================================================
  test("if_else8".fail) {
    assertCompresses(
      input = """function test(foo) {
            switch (foo) {
            case 'bar':
                return 'PASS';
            default:
                return 'FAIL';
            }
        }
        console.log(test('bar'))""".stripMargin.trim,
      expected = """function test(foo) {
            return 'bar' === foo ? 'PASS' : 'FAIL';

        }
        console.log(test('bar'))""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // issue_376
  // =========================================================================
  test("issue_376".fail) {
    assertCompresses(
      input = """switch (true) {
          case boolCondition:
            console.log(1);
            break;
          case false:
            console.log(2);
            break;
        }""".stripMargin.trim,
      expected = "if (true === boolCondition) console.log(1)",
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_441_1
  // =========================================================================
  test("issue_441_1".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            qux();
            break;
          case baz:
            qux();
            break;
          default:
            qux();
            break;
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
          case baz:
        }
        qux()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_441_2
  // =========================================================================
  test("issue_441_2".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            qux();
            break;
          case fall:
          case baz:
            qux();
            break;
          default:
            qux();
            break;
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
          case fall:
          case baz:
        }
        qux()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_441_3
  // =========================================================================
  test("issue_441_3".fail) {
    assertCompresses(
      input = """switch (foo) {
          case bar:
            qux();
            break;
          case fall:
          case baz:
            qux();
            break;
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case bar:
          case fall:
          case baz:
            qux();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_441_4
  // =========================================================================
  test("issue_441_4".fail) {
    assertCompresses(
      input = """switch (foo) {
          case 1:
            qux();
            break;
          case fall1:
          case 2:
            qux();
            break;
          case 3:
            other();
            break;
          case 4:
            qux();
            break;
          case fall2:
          case 5:
            qux();
            break;
        }""".stripMargin.trim,
      expected = """switch (foo) {
          case 1:
          case fall1:
          case 2:
            qux();
            break;
          case 3:
            other();
            break;
          case 4:
          case fall2:
          case 5:
            qux()
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1674
  // =========================================================================
  test("issue_1674".fail) {
    assertCompresses(
      input = """switch (0) {
          default:
            console.log("FAIL");
            break;
          case 0:
            console.log("PASS");
            break;
        }""".stripMargin.trim,
      expected = "console.log(\"PASS\")",
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1679
  // =========================================================================
  test("issue_1679".fail) {
    assertCompresses(
      input = """var a = 100, b = 10;
        function f() {
            switch (--b) {
              default:
              case !function x() {}:
                break;
              case b--:
                switch (0) {
                  default:
                  case a--:
                }
                break;
              case (a++):
                break;
            }
        }
        f();
        console.log(a, b)""".stripMargin.trim,
      expected = """var a = 100, b = 10;
        function f() {
            switch (--b) {
              default:
              case !function x() {}:
                break;
              case b--:
                a--;
              case (a++):
            }
        }
        f();
        console.log(a, b)""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        deadCode = true,
        evaluate = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1680_1
  // =========================================================================
  test("issue_1680_1".fail) {
    assertCompresses(
      input = """function f(x) {
            console.log(x);
            return x + 1;
        }
        switch (2) {
          case f(0):
          case f(1):
            f(2);
          case 2:
          case f(3):
          case f(4):
            f(5);
        }""".stripMargin.trim,
      expected = """function f(x) {
            console.log(x);
            return x + 1;
        }
        switch (2) {
          case f(0):
          case f(1):
            f(2);
          case 2:
            f(5);
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1680_2
  // =========================================================================
  test("issue_1680_2".fail) {
    assertCompresses(
      input = """var a = 100, b = 10;
        switch (b) {
          case a--:
            break;
          case b:
            var c;
            break;
          case a:
            break;
          case a--:
            break;
        }
        console.log(a, b)""".stripMargin.trim,
      expected = """var a = 100, b = 10;
        switch (b) {
          case a--:
          case b:
            var c;
          case a:
          case a--:
        }
        console.log(a, b)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1690_1
  // =========================================================================
  test("issue_1690_1") {
    assertCompresses(
      input = "switch (console.log(\"PASS\")) {}",
      expected = "console.log(\"PASS\")",
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1690_2
  // =========================================================================
  test("issue_1690_2") {
    assertCompresses(
      input = "switch (console.log(\"PASS\")) {}",
      expected = "switch (console.log(\"PASS\")) {}",
      options = AllOff.copy(
        deadCode = false,
        switches = true
      )
    )
  }

  // =========================================================================
  // if_switch_typeof
  // =========================================================================
  test("if_switch_typeof") {
    assertCompresses(
      input = "if (a) switch(typeof b) {}",
      expected = "a",
      options = AllOff.copy(
        conditionals = true,
        deadCode = true,
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1698
  // =========================================================================
  test("issue_1698".fail) {
    assertCompresses(
      input = """var a = 1;
        !function() {
            switch (a++) {}
        }();
        console.log(a)""".stripMargin.trim,
      expected = """var a = 1;
        !function() {
            switch (a++) {}
        }();
        console.log(a)""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1705_1
  // =========================================================================
  test("issue_1705_1".fail) {
    assertCompresses(
      input = """var a = 0;
        switch (a) {
          default:
            console.log("FAIL");
          case 0:
            break;
        }""".stripMargin.trim,
      expected = """var a = 0;
        if (a !== 0) console.log("FAIL")""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1705_2
  // =========================================================================
  test("issue_1705_2".fail) {
    assertCompresses(
      input = """var a = 0;
        switch (a) {
          default:
            console.log("FAIL");
          case 0:
            break;
        }""".stripMargin.trim,
      expected = "",
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        reduceFuncs = true,
        reduceVars = true,
        sequencesLimit = 200,
        sideEffects = true,
        switches = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // issue_1705_3
  // =========================================================================
  test("issue_1705_3".fail) {
    assertCompresses(
      input = """switch (a) {
          case 0:
            break;
          default:
            break;
        }""".stripMargin.trim,
      expected = "a",
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1758
  // =========================================================================
  test("issue_1758") {
    assertCompresses(
      input = """var a = 1, b = 2;
        switch (a--) {
          default:
            b++;
        }
        console.log(a, b)""".stripMargin.trim,
      expected = """var a = 1, b = 2;
        a--;
        b++;
        console.log(a, b)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_2535
  // =========================================================================
  test("issue_2535".fail) {
    assertCompresses(
      input = """switch(w(), 42) {
            case 13: x();
            case 42: y();
            default: z();
        }""".stripMargin.trim,
      expected = """w(), 42;
        42;
        y();
        z()""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1750
  // =========================================================================
  test("issue_1750".fail) {
    assertCompresses(
      input = """var a = 0, b = 1;
        switch (true) {
          case a, true:
          default:
            b = 2;
          case true:
        }
        console.log(a, b)""".stripMargin.trim,
      expected = """var a = 0, b = 1;
        true;
        a, true;
        b = 2;
        console.log(a, b)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches
  // =========================================================================
  test("collapse_same_branches".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 1:
                console.log("PASS");
                break

            case 2:
                console.log("PASS");
                break

        }""".stripMargin.trim,
      expected = """switch (id(1)) {
            case 1:
            case 2:
                console.log("PASS");
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_2
  // =========================================================================
  test("collapse_same_branches_2".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 1:
                console.log("PASS");

            case 2:
                console.log("PASS");
        }""".stripMargin.trim,
      expected = """switch (id(1)) {
            case 1:
                console.log("PASS");

            case 2:
                console.log("PASS");
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_not_in_a_row
  // =========================================================================
  test("collapse_same_branches_not_in_a_row".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 1:
                console.log("PASS")
                break;
            case 2:
                console.log("FAIL");
                break;
            case 3:
                console.log("PASS");
                break;
        }""".stripMargin.trim,
      expected = """switch (id(1)) {
            case 1:
            case 3:
                console.log("PASS");
                break;
            case 2:
                console.log("FAIL");
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_not_in_a_row2
  // =========================================================================
  test("collapse_same_branches_not_in_a_row2".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 1:
                console.log("PASS");
                break;
            case 2:
                console.log("FAIL");
                break;
            case 3:
                console.log("PASS");
                break;
            case 4:
                console.log("PASS");
                break;
        }""".stripMargin.trim,
      expected = """switch (id(1)) {
            case 1:
            case 3:
            case 4:
                console.log("PASS");
                break;
            case 2:
                console.log("FAIL");
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_not_in_a_row_including_fallthrough_with_same_body
  // =========================================================================
  test("collapse_same_branches_not_in_a_row_including_fallthrough_with_same_body".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 1:
                console.log("PASS");
                break;
            case 2:
                console.log("FAIL");
                break;
            case 3:
            case 4:
                console.log("PASS");
                break;
            case 9:
                console.log("FAIL");
                break;
            case 5:
            case 6:
            case 7:
            case 8:
                console.log("PASS");
                break;
        }""".stripMargin.trim,
      expected = """switch (id(1)) {
            case 1:
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
            case 8:
                console.log("PASS");
                break;
            case 2:
            case 9:
                console.log("FAIL");
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_not_in_a_row_ensure_no_side_effects
  // =========================================================================
  test("collapse_same_branches_not_in_a_row_ensure_no_side_effects".fail) {
    assertCompresses(
      input = """let i = 1;
        switch (id(2)) {
            case 1:
                console.log(1);
                break;
            case 2:
                console.log(2);
                break;
            case ++i:
                console.log(1);
                break;
        }""".stripMargin.trim,
      expected = """let i = 1;
        switch (id(2)) {
            case 1:
                console.log(1);
                break;
            case 2:
                console.log(2);
                break;
            case ++i:
                console.log(1);
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_not_in_a_row_ensure_no_evaluate_elad
  // =========================================================================
  test("collapse_same_branches_not_in_a_row_ensure_no_evaluate_elad".fail) {
    assertCompresses(
      input = """let i = 1;
        switch (true) {
            case 3 == i:
                console.log(i);
                break;
            case 5 == i:
                console.log(5);
                break;
            case 1 == i:
                console.log(i);
                break;
        }""".stripMargin.trim,
      expected = """let i = 1;
        switch (true) {
            case 3 == i:
                console.log(i);
                break;
            case 5 == i:
                console.log(5);
                break;
            case 1 == i:
                console.log(i);
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_not_in_a_row_even_if_last_case_without_abort
  // =========================================================================
  test("collapse_same_branches_not_in_a_row_even_if_last_case_without_abort".fail) {
    assertCompresses(
      input = """switch (id(3)) {
            case 1:
                console.log(1);
                break;
            case 2:
                console.log(2);
                break;
            case 3:
                console.log(1);
        }""".stripMargin.trim,
      expected = """switch (id(3)) {
            case 1:
            case 3:
                console.log(1);
                break;
            case 2:
                console.log(2);
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_as_default_not_in_a_row
  // =========================================================================
  test("collapse_same_branches_as_default_not_in_a_row".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 1:
                console.log("PASS");
                break;
            case 2:
                console.log("FAIL");
                break;
            case 3:
                console.log("PREVENT_IFS");
                break;
            case 4:
                console.log("PASS");
                break;
            default:
                console.log("PASS");
                break;
        }""".stripMargin.trim,
      expected = """switch (id(1)) {
            case 1:
            case 4:
            default:
                console.log("PASS");
                break;
            case 2:
                console.log("FAIL");
                break;
            case 3:
                console.log("PREVENT_IFS");
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_in_a_row2
  // =========================================================================
  test("collapse_same_branches_in_a_row2".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 1:
                console.log("PASS");
                break;
            case 2:
                console.log("FAIL");
                break;
            case 3:
                console.log("PASS");
                break;
            case 4:
                console.log("FAIL");
                break;
        }""".stripMargin.trim,
      expected = """switch (id(1)) {
            case 1:
            case 3:
                console.log("PASS");
                break;
            case 2:
            case 4:
                console.log("FAIL");
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // collapse_same_branches_in_a_row_with_return
  // =========================================================================
  test("collapse_same_branches_in_a_row_with_return") {
    assertCompresses(
      input = """function fn() {
            switch (id(1)) {
                case 1:
                    return "PASS";
                case 2:
                    return "FAIL";
                case 3:
                    return "PASS";
                case 4:
                    return "FAIL";
            }
        }
        console.log(fn())""".stripMargin.trim,
      expected = """function fn() {
            switch (id(1)) {
                case 1:
                case 3:
                    return "PASS";
                case 2:
                case 4:
                    return "FAIL";
            }
        }
        console.log(fn())""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // trim_empty_last_branches
  // =========================================================================
  test("trim_empty_last_branches".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 1:
                console.log("PASS")
            case 2:
                // break should be removed too
                break
            case 3: {}
            case 4:
        }""".stripMargin.trim,
      expected = "if (id(1) === 1) console.log(\"PASS\")",
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // trim_empty_last_branches_2
  // =========================================================================
  test("trim_empty_last_branches_2") {
    assertCompresses(
      input = """somewhere_else: if (id(true)) {
            switch (id(1)) {
                case 1:
                    console.log("PASS")
                case 2:
                    break somewhere_else
                case 3: {}
                case 4:
            }
        }""".stripMargin.trim,
      expected = """somewhere_else: if (id(true))
            switch (id(1)) {
                case 1:
                    console.log("PASS")
                case 2:
                    break somewhere_else
            }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // trim_empty_last_branches_3
  // =========================================================================
  test("trim_empty_last_branches_3".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 1:
                console.log("PASS")
            case 2:
                "no side effect"
        }""".stripMargin.trim,
      expected = "if (id(1) === 1) console.log(\"PASS\")",
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // trim_side_effect_free_branches_falling_into_default
  // =========================================================================
  test("trim_side_effect_free_branches_falling_into_default".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case 0:
                "no side effect"
            case 1:
                // Not here either
            default:
                console.log("PASS default")
            case 2:
                console.log("PASS 2")
        }""".stripMargin.trim,
      expected = """switch (id(1)) {
            case 0:
                "no side effect"
            case 1:
                // Not here either
            default:
                console.log("PASS default")
            case 2:
                console.log("PASS 2")
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // trim_side_effect_free_branches_falling_into_default_2
  // =========================================================================
  test("trim_side_effect_free_branches_falling_into_default_2".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            default:
            case 0:
                "no side effect"
            case 1:
                console.log("PASS default")
            case 2:
                console.log("PASS 2")
        }""".stripMargin.trim,
      expected = """switch (id(1)) {
            default:
            case 0:
                "no side effect"
            case 1:
                console.log("PASS default")
            case 2:
                console.log("PASS 2")
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // gut_entire_switch
  // =========================================================================
  test("gut_entire_switch".fail) {
    assertCompresses(
      input = """switch (id(123)) {
            case 1:
            case 2:
            case 3:
            default:
                console.log("PASS");
        }""".stripMargin.trim,
      expected = "id(123); console.log(\"PASS\")",
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // gut_entire_switch_2
  // =========================================================================
  test("gut_entire_switch_2".fail) {
    assertCompresses(
      input = """switch (id(123)) {
            case 1:
                "no side effect"
            case 1:
                // Not here either
            default:
                console.log("PASS");
        }""".stripMargin.trim,
      expected = "id(123); console.log(\"PASS\")",
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // turn_into_if
  // =========================================================================
  test("turn_into_if".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case id(2):
                console.log("FAIL");
        }
        console.log("PASS")""".stripMargin.trim,
      expected = """if (id(1) === id(2)) console.log("FAIL");
        console.log("PASS")""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // turn_into_if_2
  // =========================================================================
  test("turn_into_if_2".fail) {
    assertCompresses(
      input = """switch (id(1)) {
            case id(2):
                console.log("FAIL");
            default:
                console.log("PASS");
        }""".stripMargin.trim,
      expected = """if (id(1) === id(2)) console.log("FAIL");
        console.log("PASS")""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1083_1
  // =========================================================================
  test("issue_1083_1".fail) {
    assertCompresses(
      input = """function test(definitely_true, maybe_true) {
            switch (true) {
                case definitely_true:
                default:
                    console.log("PASS");
                    break;
                case maybe_true:
                    console.log("FAIL");
                    break;
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      expected = """function test(definitely_true, maybe_true) {
            switch (true) {
                case definitely_true:
                default:
                    console.log("PASS");
                    break;
                case maybe_true:
                    console.log("FAIL");
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1083_2
  // =========================================================================
  test("issue_1083_2".fail) {
    assertCompresses(
      input = """function test(definitely_true, maybe_true) {
            switch (true) {
                case definitely_true:
                default:
                    console.log("PASS");
                    break;
                case maybe_true:
                    console.log("FAIL");
                    break;
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      expected = """function test(definitely_true, maybe_true) {
            switch (true) {
                case definitely_true:
                default:
                    console.log("PASS");
                    break;
                case maybe_true:
                    console.log("FAIL");
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1083_3
  // =========================================================================
  test("issue_1083_3".fail) {
    assertCompresses(
      input = """function test(definitely_true, maybe_true) {
            switch (true) {
                case maybe_true:
                    console.log("maybe");
                    break;
                default:
                case definitely_true:
                    console.log("definitely");
                    break;
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      expected = """function test(definitely_true, maybe_true) {
            if (true === maybe_true) console.log("maybe");
            else console.log("definitely");
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1083_4
  // =========================================================================
  test("issue_1083_4".fail) {
    assertCompresses(
      input = """function test(definitely_true, maybe_true) {
            switch (true) {
                case maybe_true:
                    console.log("maybe");
                    break;
                case definitely_true:
                default:
                    console.log("definitely");
                    break;
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      expected = """function test(definitely_true, maybe_true) {
            if (true === maybe_true) console.log("maybe");
            else console.log("definitely");
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1083_5
  // =========================================================================
  test("issue_1083_5".fail) {
    assertCompresses(
      input = """function test(definitely_true, maybe_true) {
            switch (true) {
                default:
                    console.log("definitely");
                    break;
                case maybe_true:
                    console.log("maybe");
                    break;
                case definitely_true:
                    console.log("definitely");
                    break;
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      expected = """function test(definitely_true, maybe_true) {
            switch (true) {
                default:
                    console.log("definitely");
                    break;
                case maybe_true:
                    console.log("maybe");
                    break;
                case definitely_true:
                    console.log("definitely");
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // issue_1083_6
  // =========================================================================
  test("issue_1083_6".fail) {
    assertCompresses(
      input = """function test(definitely_true, maybe_true) {
            switch (true) {
                case definitely_true:
                    console.log("definitely");
                    break;
                case maybe_true:
                    console.log("maybe");
                    break;
                default:
                    console.log("definitely");
                    break;
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      expected = """function test(definitely_true, maybe_true) {
            switch (true) {
                case definitely_true:
                    console.log("definitely");
                    break;
                case maybe_true:
                    console.log("maybe");
                    break;
                default:
                    console.log("definitely");
            }
        }
        test(true, false);
        test(true, true)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // side_effectful_case
  // =========================================================================
  test("side_effectful_case") {
    assertCompresses(
      input = """var c = "FAIL";
        switch (0) {
          case c = "PASS", 0:
        }
        console.log(c)""".stripMargin.trim,
      expected = """var c = "FAIL";
        if (0 === (c="PASS", 0));
        console.log(c)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

  // =========================================================================
  // regression_retain_var_in_eliminated_default
  // =========================================================================
  test("regression_retain_var_in_eliminated_default") {
    assertCompresses(
      input = """var a = 100;

        (function () {
            a++
            a.toString()
            switch (null) {
              default: {
                var a
              }
            }
        })();

        console.log(a)""".stripMargin.trim,
      expected = """var a = 100;
        (function () {
            a++;
            a.toString();
            var a;
            null;
        })();
        console.log(a)""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

}
