/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for expression.
 * Ported from: terser/test/compress/expression.js (3 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressExpressionSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // pow
  // =========================================================================
  test("pow") {
    assertCompresses(
      input = """var a = 2 ** 7;
        var b = 3;
        b **= 2""".stripMargin.trim,
      expected = """var a = 2 ** 7;
        var b = 3;
        b **= 2""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // pow_with_number_constants
  // =========================================================================
  test("pow_with_number_constants") {
    assertCompresses(
      input = """var a = 5 ** NaN;
        var b = 42 ** +0;
        var c = 42 ** -0;
        var d = NaN ** 1;
        var e = 2 ** Infinity;
        var f = 2 ** -Infinity""".stripMargin.trim,
      expected = """var a = 5 ** NaN;
        var b = 42 ** +0;
        var c = 42 ** -0;
        var d = NaN ** 1;
        var e = 2 ** (1/0);
        var f = 2 ** (-1/0)""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // pow_with_unary_between_brackets
  // =========================================================================
  test("pow_with_unary_between_brackets") {
    assertCompresses(
      input = "var a = (-(+5)) ** 3",
      expected = "var a = (-+5)**3",
      options = AllOff
    )
  }

}
