/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-t1371.
 * Ported from: terser/test/compress/issue-t1371.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssueT1371Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // issue_t1371
  // =========================================================================
  test("issue_t1371") {
    assertCompresses(
      input = """(foo?.bar()).baz = true;
        ((foo?.bar())).baz = true;
        (foo?.bar)();
        (foo?.bar).baz;
        new (foo?.bar)();
        (foo?.())();
        (foo?.()).bar;
        new (foo?.())();        
        
        (foo?.bar());
        (foo?.bar) + 42;
        (foo?.bar), 42""".stripMargin.trim,
      expected = """(foo?.bar()).baz = true;
        (foo?.bar()).baz = true;
        (foo?.bar)();
        (foo?.bar).baz;
        new (foo?.bar)();
        (foo?.())();
        (foo?.()).bar;
        new (foo?.())();        

        foo?.bar();
        foo?.bar + 42;
        foo?.bar, 42""".stripMargin.trim,
      options = AllOff
    )
  }

}
