/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for node_version.
 * Ported from: terser/test/compress/node_version.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressNodeVersionSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // eval_let_6
  // =========================================================================
  test("eval_let_6") {
    assertCompresses(
      input = """eval("let a;");
        console.log()""".stripMargin.trim,
      expected = """eval("let a;");
        console.log()""".stripMargin.trim,
      options = AllOff
    )
  }

}
