/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for conditionals.
 * Ported from: terser/test/compress/conditionals.js (36 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ InlineLevel, ToplevelConfig }

final class CompressConditionalsSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // ifs_1
  // =========================================================================
  test("ifs_1".fail) {
    assertCompresses(
      input = """if (foo) bar();
        if (!foo); else bar();
        if (foo); else bar();
        if (foo); else""".stripMargin.trim,
      expected = """foo&&bar();
        foo&&bar();
        foo||bar();
        foo""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // ifs_2
  // =========================================================================
  test("ifs_2") {
    assertCompresses(
      input = """if (foo) {
            x();
        } else if (bar) {
            y();
        } else if (baz) {
            z();
        }

        if (foo) {
            x();
        } else if (bar) {
            y();
        } else if (baz) {
            z();
        } else {
            t();
        }""".stripMargin.trim,
      expected = """foo ? x() : bar ? y() : baz && z();
        foo ? x() : bar ? y() : baz ? z() : t()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // ifs_3_should_warn
  // =========================================================================
  test("ifs_3_should_warn".fail) {
    assertCompresses(
      input = """var x, y;
        if (x && !(x + "1") && y) { // 1
            var qq;
            foo();
        } else {
            bar();
        }

        if (x || !!(x + "1") || y) { // 2
            foo();
        } else {
            var jj;
            bar();
        }""".stripMargin.trim,
      expected = """var x, y;
        var qq; bar();          // 1
        foo(); var jj;          // 2""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // ifs_4
  // =========================================================================
  test("ifs_4") {
    assertCompresses(
      input = """if (foo && bar) {
            x(foo)[10].bar.baz = something();
        } else
            x(foo)[10].bar.baz = something_else()""".stripMargin.trim,
      expected = """foo && bar
            ? x(foo)[10].bar.baz = something()
            : x(foo)[10].bar.baz = something_else()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // ifs_5
  // =========================================================================
  test("ifs_5".fail) {
    assertCompresses(
      input = """function f() {
            if (foo) return;
            bar();
            baz();
        }
        function g() {
            if (foo) return;
            if (bar) return;
            if (baz) return;
            if (baa) return;
            a();
            b();
        }""".stripMargin.trim,
      expected = """function f() {
            if (!foo) {
                bar();
                baz();
            }
        }
        function g() {
            if (!(foo || bar || baz || baa)) {
                a();
                b();
            }
        }""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        conditionals = true,
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // ifs_6
  // =========================================================================
  test("ifs_6") {
    assertCompresses(
      input = """var x, y;
        if (!foo && !bar && !baz && !boo) {
            x = 10;
        } else {
            x = 20;
        }
        if (y) {
            x[foo] = 10;
        } else {
            x[foo] = 20;
        }
        if (foo) {
            x[bar] = 10;
        } else {
            x[bar] = 20;
        }""".stripMargin.trim,
      expected = """var x, y;
        x = foo || bar || baz || boo ? 20 : 10;
        x[foo] = y ? 10 : 20;
        foo ? x[bar] = 10 : x[bar] = 20""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        conditionals = true
      )
    )
  }

  // =========================================================================
  // cond_1
  // =========================================================================
  test("cond_1") {
    assertCompresses(
      input = """function foo(do_something, some_condition) {
            if (some_condition) {
                do_something(x);
            } else {
                do_something(y);
            }
            if (some_condition) {
                side_effects(x);
            } else {
                side_effects(y);
            }
        }""".stripMargin.trim,
      expected = """function foo(do_something, some_condition) {
            do_something(some_condition ? x : y);
            some_condition ? side_effects(x) : side_effects(y);
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // cond_2
  // =========================================================================
  test("cond_2".fail) {
    assertCompresses(
      input = """function foo(x, FooBar, some_condition) {
            if (some_condition) {
                x = new FooBar(1);
            } else {
                x = new FooBar(2);
            }
        }""".stripMargin.trim,
      expected = """function foo(x, FooBar, some_condition) {
            x = new FooBar(some_condition ? 1 : 2);
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // cond_3
  // =========================================================================
  test("cond_3") {
    assertCompresses(
      input = """var FooBar;
        if (some_condition()) {
            new FooBar(1);
        } else {
            FooBar(2);
        }""".stripMargin.trim,
      expected = """var FooBar;
        some_condition() ? new FooBar(1) : FooBar(2)""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // cond_4
  // =========================================================================
  test("cond_4") {
    assertCompresses(
      input = """var do_something;
        if (some_condition()) {
            do_something();
        } else {
            do_something();
        }
        if (some_condition()) {
            side_effects();
        } else {
            side_effects();
        }""".stripMargin.trim,
      expected = """var do_something;
        some_condition(), do_something();
        some_condition(), side_effects()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // cond_5
  // =========================================================================
  test("cond_5") {
    assertCompresses(
      input = """if (some_condition()) {
            if (some_other_condition()) {
                do_something();
            } else {
                alternate();
            }
        } else {
            alternate();
        }

        if (some_condition()) {
            if (some_other_condition()) {
                do_something();
            }
        }""".stripMargin.trim,
      expected = """some_condition() && some_other_condition() ? do_something() : alternate();
        some_condition() && some_other_condition() && do_something()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // cond_7
  // =========================================================================
  test("cond_7".fail) {
    assertCompresses(
      input = """var x, y, z, a, b;
        // compress these
        if (y) {
            x = 1+1;
        } else {
            x = 2;
        }

        if (y) {
            x = 1+1;
        } else if (z) {
            x = 2;
        } else {
            x = 3-1;
        }

        x = y ? 'foo' : 'fo'+'o';

        x = y ? 'foo' : y ? 'foo' : 'fo'+'o';

        // Compress conditions that have side effects
        if (condition()) {
            x = 10+10;
        } else {
            x = 20;
        }

        if (z) {
            x = 'fuji';
        } else if (condition()) {
            x = 'fu'+'ji';
        } else {
            x = 'fuji';
        }

        x = condition() ? 'foobar' : 'foo'+'bar';

        // don't compress these
        x = y ? a : b;

        x = y ? 'foo' : 'fo'""".stripMargin.trim,
      expected = """var x, y, z, a, b;
        x = 2;
        x = 2;
        x = 'foo';
        x = 'foo';
        x = (condition(), 20);
        x = ((z || condition()), 'fuji');
        x = (condition(), 'foobar');
        x = y ? a : b;
        x = y ? 'foo' : 'fo'""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        evaluate = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // cond_7_1
  // =========================================================================
  test("cond_7_1") {
    assertCompresses(
      input = """var x;
        // access to global should be assumed to have side effects
        if (y) {
            x = 1+1;
        } else {
            x = 2;
        }""".stripMargin.trim,
      expected = """var x;
        x = (y, 2)""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        evaluate = true
      )
    )
  }

  // =========================================================================
  // cond_8
  // =========================================================================
  test("cond_8") {
    assertCompresses(
      input = """var a;
        // compress these
        a = condition ? true : false;
        a = !condition ? true : false;
        a = condition() ? true : false;

        a = condition ? !0 : !1;
        a = !condition ? !null : !2;
        a = condition() ? !0 : !-3.5;

        if (condition) {
            a = true;
        } else {
            a = false;
        }

        if (condition) {
            a = !0;
        } else {
            a = !1;
        }

        a = condition ? false : true;
        a = !condition ? false : true;
        a = condition() ? false : true;

        a = condition ? !3 : !0;
        a = !condition ? !2 : !0;
        a = condition() ? !1 : !0;

        if (condition) {
            a = false;
        } else {
            a = true;
        }

        if (condition) {
            a = !1;
        } else {
            a = !0;
        }

        // don't compress these
        a = condition ? 1 : false;
        a = !condition ? true : 0;
        a = condition ? 1 : 0""".stripMargin.trim,
      expected = """var a;
        a = !!condition;
        a = !condition;
        a = !!condition();

        a = !!condition;
        a = !condition;
        a = !!condition();

        a = !!condition;
        a = !!condition;

        a = !condition;
        a = !!condition;
        a = !condition();

        a = !condition;
        a = !!condition;
        a = !condition();

        a = !condition;
        a = !condition;

        a = !!condition && 1;
        a = !condition || 0;
        a = condition ? 1 : 0""".stripMargin.trim,
      options = AllOff.copy(
        booleans = false,
        conditionals = true,
        evaluate = true
      )
    )
  }

  // =========================================================================
  // cond_8b
  // =========================================================================
  test("cond_8b") {
    assertCompresses(
      input = """var a;
        // compress these
        a = condition ? true : false;
        a = !condition ? true : false;
        a = condition() ? true : false;

        a = condition ? !0 : !1;
        a = !condition ? !null : !2;
        a = condition() ? !0 : !-3.5;

        if (condition) {
            a = true;
        } else {
            a = false;
        }

        if (condition) {
            a = !0;
        } else {
            a = !1;
        }

        a = condition ? false : true;
        a = !condition ? false : true;
        a = condition() ? false : true;

        a = condition ? !3 : !0;
        a = !condition ? !2 : !0;
        a = condition() ? !1 : !0;

        if (condition) {
            a = false;
        } else {
            a = true;
        }

        if (condition) {
            a = !1;
        } else {
            a = !0;
        }

        a = condition ? 1 : false;
        a = !condition ? true : 0;
        a = condition ? 1 : 0""".stripMargin.trim,
      expected = """var a;
        a = !!condition;
        a = !condition;
        a = !!condition();

        a = !!condition;
        a = !condition;
        a = !!condition();

        a = !!condition;
        a = !!condition;

        a = !condition;
        a = !!condition;
        a = !condition();

        a = !condition;
        a = !!condition;
        a = !condition();

        a = !condition;
        a = !condition;

        a = !!condition && 1;
        a = !condition || 0;
        a = condition ? 1 : 0""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        conditionals = true,
        evaluate = true
      )
    )
  }

  // =========================================================================
  // cond_8c
  // =========================================================================
  test("cond_8c") {
    assertCompresses(
      input = """var a;
        // compress these
        a = condition ? true : false;
        a = !condition ? true : false;
        a = condition() ? true : false;

        a = condition ? !0 : !1;
        a = !condition ? !null : !2;
        a = condition() ? !0 : !-3.5;

        if (condition) {
            a = true;
        } else {
            a = false;
        }

        if (condition) {
            a = !0;
        } else {
            a = !1;
        }

        a = condition ? false : true;
        a = !condition ? false : true;
        a = condition() ? false : true;

        a = condition ? !3 : !0;
        a = !condition ? !2 : !0;
        a = condition() ? !1 : !0;

        if (condition) {
            a = false;
        } else {
            a = true;
        }

        if (condition) {
            a = !1;
        } else {
            a = !0;
        }

        a = condition ? 1 : false;
        a = !condition ? true : 0;
        a = condition ? 1 : 0""".stripMargin.trim,
      expected = """var a;
        a = !!condition;
        a = !condition;
        a = !!condition();

        a = !!condition;
        a = !condition;
        a = !!condition() || !-3.5;

        a = !!condition;
        a = !!condition;

        a = !condition;
        a = !!condition;
        a = !condition();

        a = !condition;
        a = !!condition;
        a = !condition();

        a = !condition;
        a = !condition;

        a = !!condition && 1;
        a = !condition || 0;
        a = condition ? 1 : 0""".stripMargin.trim,
      options = AllOff.copy(
        booleans = false,
        conditionals = true,
        evaluate = false
      )
    )
  }

  // =========================================================================
  // cond_9
  // =========================================================================
  test("cond_9".fail) {
    assertCompresses(
      input = """function f(x, y) {
            g() ? x(1) : x(2);
            x ? (y || x)() : (y || x)();
            x ? y(a, b) : y(d, b, c);
            x ? y(a, b, c) : y(a, b, c);
            x ? y(a, b, c) : y(a, b, f);
            x ? y(a, b, c) : y(a, e, c);
            x ? y(a, b, c) : y(a, e, f);
            x ? y(a, b, c) : y(d, b, c);
            x ? y(a, b, c) : y(d, b, f);
            x ? y(a, b, c) : y(d, e, c);
            x ? y(a, b, c) : y(d, e, f);
        }""".stripMargin.trim,
      expected = """function f(x, y) {
            g() ? x(1) : x(2);
            x, (y || x)();
            x ? y(a, b) : y(d, b, c);
            x, y(a, b, c);
            y(a, b, x ? c : f);
            y(a, x ? b : e, c);
            x ? y(a, b, c) : y(a, e, f);
            y(x ? a : d, b, c);
            x ? y(a, b, c) : y(d, b, f);
            x ? y(a, b, c) : y(d, e, c);
            x ? y(a, b, c) : y(d, e, f);
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // ternary_boolean_consequent
  // =========================================================================
  test("ternary_boolean_consequent") {
    assertCompresses(
      input = """function f1() { return a == b ? true : x; }
        function f2() { return a == b ? false : x; }
        function f3() { return a < b ? !0 : x; }
        function f4() { return a < b ? !1 : x; }
        function f5() { return c ? !0 : x; }
        function f6() { return c ? false : x; }
        function f7() { return !c ? true : x; }
        function f8() { return !c ? !1 : x; }""".stripMargin.trim,
      expected = """function f1() { return a == b || x; }
        function f2() { return a != b && x; }
        function f3() { return a < b || x; }
        function f4() { return !(a < b) && x; }
        function f5() { return !!c || x; }
        function f6() { return !c && x; }
        function f7() { return !c || x; }
        function f8() { return !!c && x; }""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        collapseVars = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        hoistFuns = true,
        ifReturn = true,
        joinVars = true,
        keepFargs = true,
        loops = true,
        properties = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // ternary_boolean_alternative
  // =========================================================================
  test("ternary_boolean_alternative") {
    assertCompresses(
      input = """function f1() { return a == b ? x : true; }
        function f2() { return a == b ? x : false; }
        function f3() { return a < b ? x : !0; }
        function f4() { return a < b ? x : !1; }
        function f5() { return c ? x : true; }
        function f6() { return c ? x : !1; }
        function f7() { return !c ? x : !0; }
        function f8() { return !c ? x : false; }""".stripMargin.trim,
      expected = """function f1() { return a != b || x; }
        function f2() { return a == b && x; }
        function f3() { return !(a < b) || x; }
        function f4() { return a < b && x; }
        function f5() { return !c || x; }
        function f6() { return !!c && x; }
        function f7() { return !!c || x; }
        function f8() { return !c && x; }""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        collapseVars = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        hoistFuns = true,
        ifReturn = true,
        joinVars = true,
        keepFargs = true,
        loops = true,
        properties = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // trivial_boolean_ternary_expressions
  // =========================================================================
  test("trivial_boolean_ternary_expressions") {
    assertCompresses(
      input = """f('foo' in m ? true  : false);
        f('foo' in m ? false : true);

        f(g       ? true : false);
        f(foo()   ? true : false);
        f("bar"   ? true : false);
        f(5       ? true : false);
        f(5.7     ? true : false);
        f(x - y   ? true : false);

        f(x == y  ? true : false);
        f(x === y ?   !0 :    !1);
        f(x < y   ?   !0 : false);
        f(x <= y  ? true : false);
        f(x > y   ? true :    !1);
        f(x >= y  ?   !0 :    !1);

        f(g       ? false : true);
        f(foo()   ? false : true);
        f("bar"   ? false : true);
        f(5       ? false : true);
        f(5.7     ? false : true);
        f(x - y   ? false : true);

        f(x == y  ?    !1 :   !0);
        f(x === y ? false : true);

        f(x < y   ? false : true);
        f(x <= y  ? false :   !0);
        f(x > y   ?    !1 : true);
        f(x >= y  ?    !1 :   !0)""".stripMargin.trim,
      expected = """f('foo' in m);
        f(!('foo' in m));

        f(!!g);
        f(!!foo());
        f(!0);
        f(!0);
        f(!0);
        f(!!(x - y));

        f(x == y);
        f(x === y);
        f(x < y);
        f(x <= y);
        f(x > y);
        f(x >= y);

        f(!g);
        f(!foo());
        f(!1);
        f(!1);
        f(!1);
        f(!(x - y));

        f(x != y);
        f(x !== y);

        f(!(x < y));
        f(!(x <= y));
        f(!(x > y));
        f(!(x >= y))""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        conditionals = true,
        evaluate = true
      )
    )
  }

  // =========================================================================
  // issue_1154
  // =========================================================================
  test("issue_1154".fail) {
    assertCompresses(
      input = """function f1(x) { return x ? -1 : -1; }
        function f2(x) { return x ? +2 : +2; }
        function f3(x) { return x ? ~3 : ~3; }
        function f4(x) { return x ? !4 : !4; }
        function f5(x) { return x ? void 5 : void 5; }
        function f6(x) { return x ? typeof 6 : typeof 6; }

        function g1() { return g() ? -1 : -1; }
        function g2() { return g() ? +2 : +2; }
        function g3() { return g() ? ~3 : ~3; }
        function g4() { return g() ? !4 : !4; }
        function g5() { return g() ? void 5 : void 5; }
        function g6() { return g() ? typeof 6 : typeof 6; }""".stripMargin.trim,
      expected = """function f1(x) { return -1; }
        function f2(x) { return 2; }
        function f3(x) { return -4; }
        function f4(x) { return !1; }
        function f5(x) { return; }
        function f6(x) { return "number"; }

        function g1() { return g(), -1; }
        function g2() { return g(), 2; }
        function g3() { return g(), -4; }
        function g4() { return g(), !1; }
        function g5() { return void g(); }
        function g6() { return g(), "number"; }""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        conditionals = true,
        evaluate = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // no_evaluate
  // =========================================================================
  test("no_evaluate".fail) {
    assertCompresses(
      input = """function f(b) {
            a = b ? !0 : !0;
            a = b ? ~1 : ~1;
            a = b ? -2 : -2;
            a = b ? +3 : +3;
        }""".stripMargin.trim,
      expected = """function f(b) {
            a = !0;
            a = ~1;
            a = -2;
            a = +3;
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        evaluate = false,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // equality_conditionals_false
  // =========================================================================
  test("equality_conditionals_false".fail) {
    assertCompresses(
      input = """function f(a, b, c) {
            console.log(
                a == (b ? a : a),
                a == (b ? a : c),
                a != (b ? a : a),
                a != (b ? a : c),
                a === (b ? a : a),
                a === (b ? a : c),
                a !== (b ? a : a),
                a !== (b ? a : c)
            );
        }
        f(0, 0, 0);
        f(0, true, 0);
        f(1, 2, 3);
        f(1, null, 3);
        f(NaN);
        f(NaN, "foo")""".stripMargin.trim,
      expected = """function f(a, b, c) {
            console.log(
                a == (b ? a : a),
                a == (b ? a : c),
                a != (b ? a : a),
                a != (b ? a : c),
                a === (b ? a : a),
                a === (b ? a : c),
                a !== (b ? a : a),
                a !== (b ? a : c)
            );
        }
        f(0, 0, 0),
        f(0, true, 0),
        f(1, 2, 3),
        f(1, null, 3),
        f(NaN),
        f(NaN, "foo")""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = false,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // equality_conditionals_true
  // =========================================================================
  test("equality_conditionals_true".fail) {
    assertCompresses(
      input = """function f(a, b, c) {
            console.log(
                a == (b ? a : a),
                a == (b ? a : c),
                a != (b ? a : a),
                a != (b ? a : c),
                a === (b ? a : a),
                a === (b ? a : c),
                a !== (b ? a : a),
                a !== (b ? a : c)
            );
        }
        f(0, 0, 0);
        f(0, true, 0);
        f(1, 2, 3);
        f(1, null, 3);
        f(NaN);
        f(NaN, "foo")""".stripMargin.trim,
      expected = """function f(a, b, c) {
            console.log(
                (b, a == a),
                a == (b ? a : c),
                (b, a != a),
                a != (b ? a : c),
                (b, a === a),
                a === (b ? a : c),
                (b, a !== a),
                a !== (b ? a : c)
            );
        }
        f(0, 0, 0),
        f(0, true, 0),
        f(1, 2, 3),
        f(1, null, 3),
        f(NaN),
        f(NaN, "foo")""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // issue_1645_1
  // =========================================================================
  test("issue_1645_1") {
    assertCompresses(
      input = """var a = 100, b = 10;
        (b = a) ? a++ + (b += a) ? b += a : b += a : b ^= a;
        console.log(a, b)""".stripMargin.trim,
      expected = """var a = 100, b = 10;
        (b = a) ? (a++ + (b += a), b += a) : b ^= a;
        console.log(a,b)""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // issue_1645_2
  // =========================================================================
  test("issue_1645_2".fail) {
    assertCompresses(
      input = """var a = 0;
        function f() {
            return a++;
        }
        f() ? a += 2 : a += 4;
        console.log(a)""".stripMargin.trim,
      expected = """var a = 0;
        function f(){
            return a++;
        }
        f() ? a += 2 : a += 4;
        console.log(a)""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // condition_symbol_matches_consequent
  // =========================================================================
  test("condition_symbol_matches_consequent") {
    assertCompresses(
      input = """function foo(x, y) {
            return x ? x : y;
        }
        function bar() {
            return g ? g : h;
        }
        var g = 4;
        var h = 5;
        console.log(foo(3, null), foo(0, 7), foo(true, false), bar())""".stripMargin.trim,
      expected = """function foo(x, y) {
            return x || y;
        }
        function bar() {
            return g || h;
        }
        var g = 4;
        var h = 5;
        console.log(foo(3, null), foo(0, 7), foo(true, false), bar())""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // delete_conditional_1
  // =========================================================================
  test("delete_conditional_1".fail) {
    assertCompresses(
      input = """console.log(delete (1 ? undefined : x));
        console.log(delete (1 ? void 0 : x));
        console.log(delete (1 ? Infinity : x));
        console.log(delete (1 ? 1 / 0 : x));
        console.log(delete (1 ? NaN : x));
        console.log(delete (1 ? 0 / 0 : x))""".stripMargin.trim,
      expected = """console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0)""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        conditionals = true,
        evaluate = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // delete_conditional_2
  // =========================================================================
  test("delete_conditional_2".fail) {
    assertCompresses(
      input = """console.log(delete (0 ? x : undefined));
        console.log(delete (0 ? x : void 0));
        console.log(delete (0 ? x : Infinity));
        console.log(delete (0 ? x : 1 / 0));
        console.log(delete (0 ? x : NaN));
        console.log(delete (0 ? x : 0 / 0))""".stripMargin.trim,
      expected = """console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0);
        console.log(!0)""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        conditionals = true,
        evaluate = true,
        keepInfinity = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_2535_1
  // =========================================================================
  test("issue_2535_1".fail) {
    assertCompresses(
      input = """if (true || x()) y();
        if (true && x()) y();
        if (x() || true) y();
        if (x() && true) y();
        if (false || x()) y();
        if (false && x()) y();
        if (x() || false) y();
        if (x() && false) y()""".stripMargin.trim,
      expected = """y();
        x() && y();
        (x(), 1) && y();
        x() && y();
        x() && y();
        x() && y();
        (x(), 0) && y()""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        conditionals = true,
        evaluate = true,
        passes = 2,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_2535_2
  // =========================================================================
  test("issue_2535_2".fail) {
    assertCompresses(
      input = """function x() {}
        function y() {
            return "foo";
        }
        console.log((x() || true) || y());
        console.log((y() || true) || x());
        console.log((x() || true) && y());
        console.log((y() || true) && x());
        console.log((x() && true) || y());
        console.log((y() && true) || x());
        console.log((x() && true) && y());
        console.log((y() && true) && x());
        console.log((x() || false) || y());
        console.log((y() || false) || x());
        console.log((x() || false) && y());
        console.log((y() || false) && x());
        console.log((x() && false) || y());
        console.log((y() && false) || x());
        console.log((x() && false) && y());
        console.log((y() && false) && x())""".stripMargin.trim,
      expected = """function x() {}
        function y() {
            return "foo";
        }
        console.log(x() || !0);
        console.log(y() || !0);
        console.log((x(), y()));
        console.log((y(), x()));
        console.log(!!x() || y());
        console.log(!!y() || x());
        console.log(x() && y());
        console.log(y() && x());
        console.log(x() || y());
        console.log(y() || x());
        console.log(!!x() && y());
        console.log(!!y() && x());
        console.log((x(), y()));
        console.log((y(), x()));
        console.log(x() && !1);
        console.log(y() && !1)""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        conditionals = true,
        evaluate = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_2560
  // =========================================================================
  test("issue_2560".fail) {
    assertCompresses(
      input = """function log(x) {
            console.log(x);
        }
        function foo() {
            return log;
        }
        function bar() {
            if (x !== (x = foo())) {
                x(1);
            } else {
                x(2);
            }
        }
        var x = function() {
            console.log("init");
        };
        bar();
        bar()""".stripMargin.trim,
      expected = """function log(x) {
            console.log(x);
        }
        function bar() {
            x !== (x = log) ? x(1) : x(2);
        }
        var x = function() {
            console.log("init");
        };
        bar();
        bar()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        inline = InlineLevel.InlineFull,
        reduceFuncs = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // issue_2994
  // =========================================================================
  test("issue_2994") {
    assertCompresses(
      input = """function f(condition1, condition2, condition3) {
            if (condition1) {
                if (condition2) {
                    return aValue;
                } else {
                    const variable1 = 'something';
                    if (condition3) {
                        const variable2 = 'else';
                        return anotherValue;
                    } else {
                        return undefined;
                    }
                }
            }
        }
        let aValue = 2, anotherValue = 3;
        for (let i = 0; i < 8; ++i) {
            console.log(f(i & 4, i & 2, i & 1));
        }""".stripMargin.trim,
      expected = """function f(condition1, condition2, condition3) {
            if (condition1) {
                if (condition2) return aValue;
                {
                    const variable1 = "something";
                    if (condition3) {
                        const variable2 = "else";
                        return anotherValue;
                    }
                    return;
                }
            }
        }
        let aValue = 2, anotherValue = 3;
        for (let i = 0; i < 8; ++i)
            console.log(f(i & 4, i & 2, i & 1))""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // hoist_decl
  // =========================================================================
  test("hoist_decl") {
    assertCompresses(
      input = """if (x()) {
            var a;
            y();
        } else {
            z();
            var b;
        }""".stripMargin.trim,
      expected = """var a, b;
        x() ? y() : z()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        joinVars = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // to_and_or
  // =========================================================================
  test("to_and_or") {
    assertCompresses(
      input = """var values = [
            0,
            null,
            true,
            "foo",
            false,
            -1 / 0,
            void 0,
        ];
        values.forEach(function(x) {
            values.forEach(function(y) {
                values.forEach(function(z) {
                    console.log(x ? y || z : z);
                });
            });
        })""".stripMargin.trim,
      expected = """var values = [
            0,
            null,
            true,
            "foo",
            false,
            -1 / 0,
            void 0,
        ];
        values.forEach(function(x) {
            values.forEach(function(y) {
                values.forEach(function(z) {
                    console.log(x && y || z);
                });
            });
        })""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

  // =========================================================================
  // ifs_same_consequent
  // =========================================================================
  test("ifs_same_consequent") {
    assertCompresses(
      input = """if (foo) {
            x();
        } else if (bar) {
            x();
        } else if (baz) {
            x();
        }

        if (foo) {
            x();
        } else if (bar) {
            x();
        } else if (baz) {
            x();
        } else {
            x();
        }

        if (foo) {
            x();
        } else if (bar) {
            x();
        } else if (baz) {
            x();
        } else {
            y();
        }""".stripMargin.trim,
      expected = """(foo || bar || baz) && x();
        (foo || bar || baz), x();
        (foo || bar || baz) ? x() : y()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true
      )
    )
  }

}
