/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-747.
 * Ported from: terser/test/compress/issue-747.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue747Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // dont_reuse_prop
  // =========================================================================
  test("dont_reuse_prop".fail) {
    assertCompresses(
      input = """"aaaaaaaaaabbbbb";
        var obj = {};
        obj.a = 123;
        obj.asd = 256;
        console.log(obj.a)""".stripMargin.trim,
      expected = "\"aaaaaaaaaabbbbb\";var obj={};obj.a=123;obj.o=256;console.log(obj.a)",
      options = AllOff
    )
  }

  // =========================================================================
  // unmangleable_props_should_always_be_reserved
  // =========================================================================
  test("unmangleable_props_should_always_be_reserved".fail) {
    assertCompresses(
      input = """"aaaaaaaaaabbbbb";
        var obj = {};
        obj.asd = 256;
        obj.a = 123;
        console.log(obj.a)""".stripMargin.trim,
      expected = "\"aaaaaaaaaabbbbb\";var obj={};obj.o=256;obj.a=123;console.log(obj.a)",
      options = AllOff
    )
  }

}
