/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1338.
 * Ported from: terser/test/compress/issue-1338.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ ToplevelConfig }

final class CompressIssue1338Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // comment_1562957781
  // =========================================================================
  test("comment_1562957781".fail) {
    assertCompresses(
      input = """'use strict';

        const DEBUG = false;

        function initPlayer() { // eslint-disable-line
            const player = new createPlayer();

            return player;
        }

        function createPlayer() {
            if (DEBUG) {
                console.log('-> new player');
            }

            this.destroy = () => {
                if (DEBUG) {
                    console.log('-> destroyed player');
                }
            };
        }

        initPlayer()""".stripMargin.trim,
      expected = """'use strict';

        function createPlayer() {
            if (false)
                console.log('-> new player');

            this.destroy = () => {
                if (false)
                    console.log('-> destroyed player');
            };
        }

        (function () { // eslint-disable-line
            const player = new createPlayer();

            return player;
        })()""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

}
