/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for optional-chains.
 * Ported from: terser/test/compress/optional-chains.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ InlineLevel }

final class CompressOptionalChainsSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // issue_1586_optional_chain_inlined
  // =========================================================================
  test("issue_1586_optional_chain_inlined".fail) {
    assertCompresses(
      input = """const fn = () => (foo(), bar())
        obj = {
            prop: fn?.(),
        }""".stripMargin.trim,
      expected = """obj = {
            prop: (foo(), bar()),
        }""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        module = true,
        reduceVars = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // issue_1586_optional_chain_inlined_2
  // =========================================================================
  test("issue_1586_optional_chain_inlined_2".fail) {
    assertCompresses(
      input = """obj = {
            prop: (() => (foo(), bar()))?.(),
        }""".stripMargin.trim,
      expected = """obj = {
            prop: (foo(), bar()),
        }""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull
      )
    )
  }

}
