/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1446.
 * Ported from: terser/test/compress/issue-1446.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue1446Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // typeof_eq_undefined
  // =========================================================================
  test("typeof_eq_undefined".fail) {
    assertCompresses(
      input = """var a = typeof b != "undefined";
        b = typeof a != "undefined";
        var c = typeof d.e !== "undefined";
        var f = "undefined" === typeof g;
        g = "undefined" === typeof f;
        var h = "undefined" == typeof i.j""".stripMargin.trim,
      expected = """var a = typeof b != "undefined";
        b = a !== void 0;
        var c = d.e !== void 0;
        var f = "undefined" == typeof g;
        g = void 0 === f;
        var h = void 0 === i.j""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        typeofs = true
      )
    )
  }

  // =========================================================================
  // typeof_eq_undefined_ie8
  // =========================================================================
  test("typeof_eq_undefined_ie8".fail) {
    assertCompresses(
      input = """var a = typeof b != "undefined";
        b = typeof a != "undefined";
        var c = typeof d.e !== "undefined";
        var f = "undefined" === typeof g;
        g = "undefined" === typeof f;
        var h = "undefined" == typeof i.j""".stripMargin.trim,
      expected = """var a = typeof b != "undefined";
        b = a !== void 0;
        var c =  typeof d.e != "undefined";
        var f = "undefined" == typeof g;
        g = void 0 === f;
        var h = "undefined" == typeof i.j""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        ie8 = true,
        typeofs = true
      )
    )
  }

}
