/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for hoist_vars.
 * Ported from: terser/test/compress/hoist_vars.js (6 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressHoistVarsSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // statements
  // =========================================================================
  test("statements") {
    assertCompresses(
      input = """function f() {
            var a = 1;
            var b = 2;
            var c = 3;
            function g() {}
            return g(a, b, c);
        }""".stripMargin.trim,
      expected = """function f() {
            var a = 1, b = 2, c = 3;
            function g() {}
            return g(a, b, c);
        }""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = false,
        hoistVars = true
      )
    )
  }

  // =========================================================================
  // statements_funs
  // =========================================================================
  test("statements_funs") {
    assertCompresses(
      input = """function f() {
            var a = 1;
            var b = 2;
            var c = 3;
            function g() {}
            return g(a, b, c);
        }""".stripMargin.trim,
      expected = """function f() {
            function g() {}
            var a = 1, b = 2, c = 3;
            return g(a, b, c);
        }""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = true,
        hoistVars = true
      )
    )
  }

  // =========================================================================
  // sequences
  // =========================================================================
  test("sequences") {
    assertCompresses(
      input = """function f() {
            var a = 1, b = 2;
            function g() {}
            var c = 3;
            return g(a, b, c);
        }""".stripMargin.trim,
      expected = """function f() {
            var c, a = 1, b = 2;
            function g() {}
            c = 3;
            return g(a, b, c);
        }""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = false,
        hoistVars = true
      )
    )
  }

  // =========================================================================
  // sequences_funs
  // =========================================================================
  test("sequences_funs") {
    assertCompresses(
      input = """function f() {
            var a = 1, b = 2;
            function g() {}
            var c = 3;
            return g(a, b, c);
        }""".stripMargin.trim,
      expected = """function f() {
            function g() {}
            var a = 1, b = 2, c = 3;
            return g(a, b, c);
        }""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = true,
        hoistVars = true
      )
    )
  }

  // =========================================================================
  // issue_2295
  // =========================================================================
  test("issue_2295") {
    assertCompresses(
      input = """function foo(o) {
            var a = o.a;
            if (a) return a;
            var a = 1;
        }""".stripMargin.trim,
      expected = """function foo(o) {
            var a = o.a;
            if (a) return a;
            a = 1;
        }""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        hoistVars = true
      )
    )
  }

  // =========================================================================
  // regression_toplevel_args
  // =========================================================================
  test("regression_toplevel_args".fail) {
    assertCompresses(
      input = """var Foo;
        var Bar""".stripMargin.trim,
      expected = "var Foo, Bar",
      options = AllOff.copy(
        hoistVars = true
      )
    )
  }

}
