/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for if_return.
 * Ported from: terser/test/compress/if_return.js (21 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ InlineLevel }

final class CompressIfReturnSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // if_return_1
  // =========================================================================
  test("if_return_1") {
    assertCompresses(
      input = """function f(x) {
            if (x) {
                return true;
            }
        }""".stripMargin.trim,
      expected = "function f(x){if(x)return!0}",
      options = AllOff.copy(
        booleans = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // if_return_2
  // =========================================================================
  test("if_return_2".fail) {
    assertCompresses(
      input = """function f(x, y) {
            if (x)
                return 3;
            if (y)
                return c();
        }""".stripMargin.trim,
      expected = "function f(x,y){return x?3:y?c():void 0}",
      options = AllOff.copy(
        booleans = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // if_return_3
  // =========================================================================
  test("if_return_3".fail) {
    assertCompresses(
      input = """function f(x) {
            a();
            if (x) {
                b();
                return false;
            }
        }""".stripMargin.trim,
      expected = "function f(x){if(a(),x)return b(),!1}",
      options = AllOff.copy(
        booleans = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // if_return_4
  // =========================================================================
  test("if_return_4".fail) {
    assertCompresses(
      input = """function f(x, y) {
            a();
            if (x) return 3;
            b();
            if (y) return c();
        }""".stripMargin.trim,
      expected = "function f(x,y){return a(),x?3:(b(),y?c():void 0)}",
      options = AllOff.copy(
        booleans = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // if_return_5
  // =========================================================================
  test("if_return_5".fail) {
    assertCompresses(
      input = """function f() {
            if (x)
                return;
            return 7;
            if (y)
                return j;
        }""".stripMargin.trim,
      expected = "function f(){if(!x)return 7}",
      options = AllOff.copy(
        booleans = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // if_return_6
  // =========================================================================
  test("if_return_6") {
    assertCompresses(
      input = """function f(x) {
          return x ? true : void 0;
          return y;
        }""".stripMargin.trim,
      expected = """// suboptimal
        function f(x){return!!x||void 0}""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // if_return_7
  // =========================================================================
  test("if_return_7".fail) {
    assertCompresses(
      input = """function f(x) {
            if (x) {
                return true;
            }
            foo();
            bar();
        }""".stripMargin.trim,
      expected = "function f(x){if(x)return!0;foo(),bar()}",
      options = AllOff.copy(
        booleans = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // if_return_8
  // =========================================================================
  test("if_return_8".fail) {
    assertCompresses(
      input = """function f(e) {
            if (2 == e) return foo();
            if (3 == e) return bar();
            if (4 == e) return baz();
            fail(e);
        }

        function g(e) {
            if (a(e)) return foo();
            if (b(e)) return bar();
            if (c(e)) return baz();
            fail(e);
        }

        function h(e) {
            if (a(e)) return foo();
            else if (b(e)) return bar();
            else if (c(e)) return baz();
            else fail(e);
        }

        function i(e) {
            if (a(e)) return foo();
            else if (b(e)) return bar();
            else if (c(e)) return baz();
            fail(e);
        }""".stripMargin.trim,
      expected = """function f(e){return 2==e?foo():3==e?bar():4==e?baz():void fail(e)}
        function g(e){return a(e)?foo():b(e)?bar():c(e)?baz():void fail(e)}
        function h(e){return a(e)?foo():b(e)?bar():c(e)?baz():void fail(e)}
        function i(e){return a(e)?foo():b(e)?bar():c(e)?baz():void fail(e)}""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_1089
  // =========================================================================
  test("issue_1089".fail) {
    assertCompresses(
      input = """function x() {
            var f = document.getElementById("fname");
            if (f.files[0].size > 12345) {
                alert("alert");
                f.focus();
                return false;
            }
        }""".stripMargin.trim,
      expected = """function x() {
            var f = document.getElementById("fname");
            if (f.files[0].size > 12345)
                return alert("alert"), f.focus(), !1;
        }""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        comparisons = true,
        conditionals = true,
        deadCode = true,
        evaluate = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // issue_1437
  // =========================================================================
  test("issue_1437") {
    assertCompresses(
      input = """function x() {
            if (a())
                return b();
            if (c())
                return d();
            else
                e();
            f();
        }""".stripMargin.trim,
      expected = """function x() {
            if (a())
                return b();
            if (c())
                return d();
            else
                e()
            f();
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = false,
        ifReturn = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // issue_1437_conditionals
  // =========================================================================
  test("issue_1437_conditionals".fail) {
    assertCompresses(
      input = """function x() {
            if (a())
                return b();
            if (c())
                return d();
            else
                e();
            f();
        }""".stripMargin.trim,
      expected = """function x() {
            return a() ? b() : c() ? d() : (e(), f(), void 0);
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // issue_512
  // =========================================================================
  test("issue_512".fail) {
    assertCompresses(
      input = """function a() {
            if (b()) {
                c();
                return;
            }
            throw e;
        }""".stripMargin.trim,
      expected = """function a() {
            if (!b()) throw e;
            c();
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true,
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_1317
  // =========================================================================
  test("issue_1317") {
    assertCompresses(
      input = """!function(a) {
            if (a) return;
            let b = 1;
            function g() {
                return b;
            }
            console.log(g());
        }()""".stripMargin.trim,
      expected = """!function(a) {
            if (a) return;
            let b = 1;
            function g() {
                return b;
            }
            console.log(g());
        }()""".stripMargin.trim,
      options = AllOff.copy(
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // issue_1317_strict
  // =========================================================================
  test("issue_1317_strict") {
    assertCompresses(
      input = """"use strict";
        !function(a) {
            if (a) return;
            let b = 1;
            function g() {
                return b;
            }
            console.log(g());
        }()""".stripMargin.trim,
      expected = """"use strict";
        !function(a) {
            if (a) return;
            let b = 1;
            function g() {
                return b;
            }
            console.log(g());
        }()""".stripMargin.trim,
      options = AllOff.copy(
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // if_var_return
  // =========================================================================
  test("if_var_return".fail) {
    assertCompresses(
      input = """function f() {
            var a;
            return;
            var b;
        }
        function g() {
            var a;
            if (u()) {
                var b;
                return v();
                var c;
            }
            var d;
            if (w()) {
                var e;
                return x();
                var f;
            } else {
                var g;
                y();
                var h;
            }
            var i;
            z();
            var j;
        }""".stripMargin.trim,
      expected = """function f() {
            var a, b;
        }
        function g() {
            var a, b, c, d, e, f, g, h, i, j;
            return u() ? v() : w() ? x() : (y(), z(), void 0);
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true,
        joinVars = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // if_if_return_return
  // =========================================================================
  test("if_if_return_return") {
    assertCompresses(
      input = """function f(a, b) {
            if (a) {
                if (b)
                    return b;
                return;
            }
            g();
        }""".stripMargin.trim,
      expected = """function f(a, b) {
            if (a)
                return b || void 0;
            g();
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // issue_2747
  // =========================================================================
  test("issue_2747") {
    assertCompresses(
      input = """"use strict";
        function f(baz) {
            if (baz === 0) {
                return null;
            }
            let r;
            if (baz > 2) {
                r = 4;
            } else {
                r = 5;
            }
            return r;
        }
        console.log(f(0), f(1), f(3))""".stripMargin.trim,
      expected = """"use strict";
        function f(baz) {
            if (baz === 0) return null;
            let r;
            return r = baz > 2 ? 4 : 5, r;
        }
        console.log(f(0), f(1), f(3))""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true,
        sequencesLimit = 200,
        unused = true
      )
    )
  }

  // =========================================================================
  // if_return_same_value
  // =========================================================================
  test("if_return_same_value".fail) {
    assertCompresses(
      input = """function f() {
            if (foo) {
                return x();
            }
            if (bar) {
                return x();
            }
        }
        function g() {
            if (foo) {
                return x();
            }
            if (bar) {
                return x();
            }
            return x();
        }
        function h() {
            if (foo) {
                return x();
            }
            if (bar) {
                return x();
            }
            return y();
        }""".stripMargin.trim,
      expected = """function f() { return (foo || bar) ? x() : void 0 }
        function g() { return (foo || bar), x() }
        function h() { return (foo || bar) ? x() : y() }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // issue_t833
  // =========================================================================
  test("issue_t833") {
    assertCompresses(
      input = """var a = id(1), object = {PASS: 1};
        for (var p in object) {
            if (a) {
                test(); continue;
                function test() {console.log(p)}
            }
        }""".stripMargin.trim,
      expected = """var a = id(1), object = {PASS: 1};
        for (var p in object)
            if (a) {
                test();
                continue;
                function test(){console.log(p)}
            }""".stripMargin.trim,
      options = AllOff.copy(
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // issue_t1606_1
  // =========================================================================
  test("issue_t1606_1".fail) {
    assertCompresses(
      input = """(() => {
            if (true) {
                const fileName = "PASS";
                ((fileName) => {
                    console.log(fileName);
                })(fileName);
                return;
            }
        })()""".stripMargin.trim,
      expected = """(() => {
            if (true) {
                const fileName = "PASS";
                ((fileName) => {
                    console.log(fileName);
                })(fileName);
            }
        })()""".stripMargin.trim,
      options = AllOff.copy(
        ifReturn = true,
        inline = InlineLevel.InlineFull,
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_t1606_2
  // =========================================================================
  test("issue_t1606_2".fail) {
    assertCompresses(
      input = """(() => {
            if (!true) ; else {
                const fileName = "PASS";
                ((fileName) => {
                    console.log(fileName);
                })(fileName);
                return;
            }
        })()""".stripMargin.trim,
      expected = """(() => {
            if (!true) ; else {
                const fileName = "PASS";
                ((fileName) => {
                    console.log(fileName);
                })(fileName);
            }
        })()""".stripMargin.trim,
      options = AllOff.copy(
        ifReturn = true,
        inline = InlineLevel.InlineFull,
        sequencesLimit = 200,
        sideEffects = true
      )
    )
  }

}
