/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for pure_funcs.
 * Ported from: terser/test/compress/pure_funcs.js (21 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ InlineLevel, ToplevelConfig }

final class CompressPureFuncsSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // array
  // =========================================================================
  test("array") {
    assertCompresses(
      input = """var a;
        function f(b) {
            Math.floor(a / b);
            Math.floor(c / b);
        }""".stripMargin.trim,
      expected = """var a;
        function f(b) {
            c;
        }""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("Math.floor"),
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // func
  // =========================================================================
  test("func".fail) {
    assertCompresses(
      input = """function f(a, b) {
            Math.floor(a / b);
            Math.floor(c / b);
        }""".stripMargin.trim,
      expected = """function f(a, b) {
            Math.floor(c / b);
        }""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // side_effects
  // =========================================================================
  test("side_effects") {
    assertCompresses(
      input = """function f(a, b) {
            console.log(a());
            console.log(b);
        }""".stripMargin.trim,
      expected = """function f(a, b) {
            a();
        }""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("console.log"),
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // unused
  // =========================================================================
  test("unused".fail) {
    assertCompresses(
      input = """function foo() {
            var u = pure(1);
            var x = pure(2);
            var y = pure(x);
            var z = pure(pure(side_effects()));
            return pure(3);
        }""".stripMargin.trim,
      expected = """function foo() {
            side_effects();
            return pure(3);
        }""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("pure"),
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // babel
  // =========================================================================
  test("babel") {
    assertCompresses(
      input = """function _classCallCheck(instance, Constructor) {
            if (!(instance instanceof Constructor))
                throw new TypeError("Cannot call a class as a function");
        }
        var Foo = function Foo() {
            _classCallCheck(this, Foo);
        }""".stripMargin.trim,
      expected = """function _classCallCheck(instance, Constructor) {
            if (!(instance instanceof Constructor))
                throw new TypeError("Cannot call a class as a function");
        }
        var Foo = function() {
        }""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("_classCallCheck"),
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // conditional
  // =========================================================================
  test("conditional") {
    assertCompresses(
      input = """pure(1 | a() ? 2 & b() : 7 ^ c());
        pure(1 | a() ? 2 & b() : 5);
        pure(1 | a() ? 4 : 7 ^ c());
        pure(1 | a() ? 4 : 5);
        pure(3 ? 2 & b() : 7 ^ c());
        pure(3 ? 2 & b() : 5);
        pure(3 ? 4 : 7 ^ c());
        pure(3 ? 4 : 5)""".stripMargin.trim,
      expected = """1 | a() ? b() : c();
        1 | a() && b();
        1 | a() || c();
        a();
        3 ? b() : c();
        3 && b();
        3 || c()""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("pure"),
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // relational
  // =========================================================================
  test("relational") {
    assertCompresses(
      input = """foo() in foo();
        foo() instanceof bar();
        foo() < "bar";
        bar() > foo();
        bar() != bar();
        bar() !== "bar";
        "bar" == foo();
        "bar" === bar();
        "bar" >= "bar"""".stripMargin.trim,
      expected = """bar();
        bar();
        bar(), bar();
        bar();
        bar()""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("foo"),
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // arithmetic
  // =========================================================================
  test("arithmetic") {
    assertCompresses(
      input = """foo() + foo();
        foo() - bar();
        foo() * "bar";
        bar() / foo();
        bar() & bar();
        bar() | "bar";
        "bar" >> foo();
        "bar" << bar();
        "bar" >>> "bar"""".stripMargin.trim,
      expected = """bar();
        bar();
        bar(), bar();
        bar();
        bar()""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("foo"),
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // boolean_and
  // =========================================================================
  test("boolean_and") {
    assertCompresses(
      input = """foo() && foo();
        foo() && bar();
        foo() && "bar";
        bar() && foo();
        bar() && bar();
        bar() && "bar";
        "bar" && foo();
        "bar" && bar();
        "bar" && "bar"""".stripMargin.trim,
      expected = """foo() && bar();
        bar();
        bar() && bar();
        bar();
        "bar" && bar()""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("foo"),
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // boolean_or
  // =========================================================================
  test("boolean_or") {
    assertCompresses(
      input = """foo() || foo();
        foo() || bar();
        foo() || "bar";
        bar() || foo();
        bar() || bar();
        bar() || "bar";
        "bar" || foo();
        "bar" || bar();
        "bar" || "bar"""".stripMargin.trim,
      expected = """foo() || bar();
        bar();
        bar() || bar();
        bar();
        "bar" || bar()""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("foo"),
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // assign
  // =========================================================================
  test("assign") {
    assertCompresses(
      input = """var a;
        function f(b) {
            a = foo();
            b *= 4 + foo();
            c >>= 0 | foo();
        }""".stripMargin.trim,
      expected = """var a;
        function f(b) {
            a = foo();
            b *= 4 + foo();
            c >>= 0 | foo();
        }""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("foo"),
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // unary
  // =========================================================================
  test("unary") {
    assertCompresses(
      input = """typeof foo();
        typeof bar();
        typeof "bar";
        void foo();
        void bar();
        void "bar";
        delete a[foo()];
        delete a[bar()];
        delete a["bar"];
        a[foo()]++;
        a[bar()]++;
        a["bar"]++;
        --a[foo()];
        --a[bar()];
        --a["bar"];
        ~foo();
        ~bar();
        ~"bar"""".stripMargin.trim,
      expected = """bar();
        bar();
        delete a[foo()];
        delete a[bar()];
        delete a["bar"];
        a[foo()]++;
        a[bar()]++;
        a["bar"]++;
        --a[foo()];
        --a[bar()];
        --a["bar"];
        bar()""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("foo"),
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_2629_4
  // =========================================================================
  test("issue_2629_4".fail) {
    assertCompresses(
      input = """(/*@__PURE__*/ x(), y());
        (w(), /*@__PURE__*/ x(), y())""".stripMargin.trim,
      expected = """y();
        w(), y()""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_2629_5
  // =========================================================================
  test("issue_2629_5".fail) {
    assertCompresses(
      input = """[ /*@__PURE__*/ x() ];
        [ /*@__PURE__*/ x(), y() ];
        [ w(), /*@__PURE__*/ x(), y() ]""".stripMargin.trim,
      expected = """y();
        w(), y()""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_2705_4
  // =========================================================================
  test("issue_2705_4".fail) {
    assertCompresses(
      input = """(/*@__PURE__*/ new x(), y());
        (w(), /*@__PURE__*/ new x(), y())""".stripMargin.trim,
      expected = """y();
        w(), y()""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_2705_5
  // =========================================================================
  test("issue_2705_5".fail) {
    assertCompresses(
      input = """[ /*@__PURE__*/ new x() ];
        [ /*@__PURE__*/ new x(), y() ];
        [ w(), /*@__PURE__*/ new x(), y() ]""".stripMargin.trim,
      expected = """y();
        w(), y()""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // issue_3065_1
  // =========================================================================
  test("issue_3065_1".fail) {
    assertCompresses(
      input = """function modifyWrapper(a, f, wrapper) {
            wrapper.a = a;
            wrapper.f = f;
            return wrapper;
        }
        function pureFunc(fun) {
            return modifyWrapper(1, fun, function(a) {
                return fun(a);
            });
        }
        var unused = pureFunc(function(x) {
            return x;
        })""".stripMargin.trim,
      expected = "",
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        pureFuncs = List("pureFunc"),
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // issue_3065_2
  // =========================================================================
  test("issue_3065_2".fail) {
    assertCompresses(
      input = """function modifyWrapper(a, f, wrapper) {
            wrapper.a = a;
            wrapper.f = f;
            return wrapper;
        }
        function pureFunc(fun) {
            return modifyWrapper(1, fun, function(a) {
                return fun(a);
            });
        }
        var unused = pureFunc(function(x) {
            return x;
        })""".stripMargin.trim,
      expected = "",
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        pureFuncs = List("pureFunc"),
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // issue_3065_2b
  // =========================================================================
  test("issue_3065_2b".fail) {
    assertCompresses(
      input = """function modifyWrapper(a, f, wrapper) {
            wrapper.a = a;
            wrapper.f = f;
            return wrapper;
        }
        function pureFunc(fun) {
            return modifyWrapper(1, fun, function(a) {
                return fun(a);
            });
        }
        var unused = pureFunc(function(x) {
            return x;
        });
        function print(message) {
            console.log(message);
        }
        print(2);
        print(3)""".stripMargin.trim,
      expected = """function o(o) {
            console.log(o);
        }
        o(2);
        o(3)""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        pureFuncs = List("pureFunc"),
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // issue_3065_3
  // =========================================================================
  test("issue_3065_3".fail) {
    assertCompresses(
      input = """function debug(msg) {
            console.log(msg);
        }
        debug(function() {
            console.log("PASS");
            return "FAIL";
        }())""".stripMargin.trim,
      expected = """(function() {
            console.log("PASS");
        })()""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("debug"),
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // issue_3065_4
  // =========================================================================
  test("issue_3065_4".fail) {
    assertCompresses(
      input = """var debug = function(msg) {
            console.log(msg);
        };
        debug(function() {
            console.log("PASS");
            return "FAIL";
        }())""".stripMargin.trim,
      expected = """(function() {
            console.log("PASS");
        })()""".stripMargin.trim,
      options = AllOff.copy(
        pureFuncs = List("debug"),
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

}
