/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Golden-comparison integration test for the full Site.build pipeline (ISS-1055).
 * Runs Site.build on the committed fixture-site and asserts byte-exact equality
 * against committed golden trees (minify:false and minify:true).
 *
 * The goldens under fixture-site-expected/ and fixture-site-expected-min/ are
 * REAL Site.build output (generated by running the pipeline, not hand-written).
 *
 * This is an SSG-native module (not a port of an external library).
 * See docs/architecture/site-pipeline-design.md section 9 for design.
 *
 * JVM-only: reads the committed fixture/golden resources from the filesystem
 * via classpath resource URLs (straightforward on JVM).
 */
package ssg
package site

import ssg.commons.io.FileOps
import ssg.commons.io.FilePath

class SitePipelineGoldenSuite extends munit.FunSuite {

  /** Resolves a classpath resource directory to a FilePath.
    *
    * On sbt 1.x, test resources are copied to target/.../test-classes/ and getResource returns a file:// URL that converts directly to a Path. On sbt 2.0, test classes+resources are packaged into a
    * `<name>-tests.jar` placed on the test classpath, so getResource returns a `jar:` URL whose `toURI`/`Paths.get` throws FileSystemNotFoundException. Since this suite walks the resource as a real
    * directory tree, in the jar case we fall back to the on-disk source resources directory (`ssg-site/src/test/resources/<name>`), which holds the same committed fixtures; the forked test JVM runs
    * with the repository root as its working directory.
    */
  private def resourceDir(name: String): FilePath = {
    val url = Option(getClass.getClassLoader.getResource(name)).getOrElse(fail(s"Resource '$name' not found on classpath"))
    if (url.getProtocol == "file") {
      FilePath.of(java.nio.file.Paths.get(url.toURI).toString)
    } else {
      // jar: (or other non-filesystem) URL — sbt 2.0 packages test resources into a `<name>-tests.jar`.
      // Since this suite needs to walk the resource as a real directory tree, fall back to the on-disk
      // committed source fixtures at ssg-site/src/test/resources/<name>. The sbt-2.0 forked test JVM runs
      // with a per-project working directory under <repo>/.sbt/matrix/..., so search the cwd and its
      // ancestors for the first one that contains ssg-site/src/test/resources/<name>.
      val rel = java.nio.file.Paths.get("ssg-site", "src", "test", "resources", name)

      def search(dir: java.nio.file.Path): Option[FilePath] =
        if (dir == null) None
        else {
          val candidate = dir.resolve(rel)
          if (java.nio.file.Files.isDirectory(candidate)) Some(FilePath.of(candidate.toString))
          else search(dir.getParent)
        }

      val start = java.nio.file.Paths.get(FilePath.cwd.pathString).toAbsolutePath
      search(start).getOrElse(
        fail(s"Resource '$name' is in a non-file URL ($url) and no ancestor of $start contains $rel")
      )
    }
  }

  /** Creates a temporary directory for test output, cleaned up after. */
  private def withTempDir(testName: String)(body: FilePath => Unit): Unit = {
    val tmpBase = FilePath.cwd.resolve("target").resolve("test-tmp")
    val testDir = tmpBase.resolve(s"ssg-golden-$testName-${System.nanoTime()}")
    FileOps.createDirectories(testDir)
    try
      body(testDir)
    finally
      FileOps.deleteRecursively(testDir)
  }

  /** Walks a directory and returns a sorted set of relative paths (files only). */
  private def fileSet(root: FilePath): Vector[String] =
    FileOps
      .walkTree(root)
      .filter(f => !FileOps.isDirectory(f))
      .map { f =>
        val rel = f.pathString.stripPrefix(root.pathString)
        // Strip leading separator.
        if (rel.startsWith("/")) rel.substring(1)
        else if (rel.startsWith("\\")) rel.substring(1)
        else rel
      }
      .sorted
      .toVector

  /** Runs Site.build on the committed fixture-site and returns the destination path. */
  private def buildFixture(tmpDir: FilePath, minify: Boolean): (FilePath, BuildResult) = {
    val fixtureDir = resourceDir("fixture-site")
    val configYaml = FileOps.readString(fixtureDir.resolve("_config.yml"))
    val destDir    = tmpDir.resolve(if (minify) "_site-min" else "_site")
    FileOps.createDirectories(destDir)

    val baseConfig = SiteConfig.load(configYaml)
    val config     = baseConfig.copy(
      source = fixtureDir,
      destination = destDir,
      minify = minify
    )

    val result = Site.build(config)
    (destDir, result)
  }

  // ---------------------------------------------------------------------------
  // Golden comparison: minify=false
  // Runs Site.build on the fixture-site with minify:false and asserts the
  // produced _site tree equals fixture-site-expected/ byte-for-byte.
  // ---------------------------------------------------------------------------
  test("golden comparison: minify=false produces byte-exact match to committed golden") {
    withTempDir("nomin") { tmpDir =>
      val (destDir, result) = buildFixture(tmpDir, minify = false)
      val goldenDir         = resourceDir("fixture-site-expected")

      // No diagnostics expected for a clean build.
      assertEquals(
        result.diagnostics.size,
        0,
        s"Expected zero diagnostics, got: ${result.diagnostics}"
      )

      // Structural assertion: the file sets must be identical.
      val producedFiles = fileSet(destDir)
      val goldenFiles   = fileSet(goldenDir)
      assertEquals(
        producedFiles,
        goldenFiles,
        s"File set mismatch.\nProduced: $producedFiles\nGolden: $goldenFiles"
      )

      // Byte-exact assertion: every file's content must match.
      goldenFiles.foreach { rel =>
        val producedContent = FileOps.readString(destDir.resolve(rel))
        val goldenContent   = FileOps.readString(goldenDir.resolve(rel))
        assertEquals(
          producedContent,
          goldenContent,
          s"Content mismatch for '$rel'"
        )
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Golden comparison: minify=true
  // Runs Site.build on the fixture-site with minify:true and asserts the
  // produced _site tree equals fixture-site-expected-min/ byte-for-byte.
  // ---------------------------------------------------------------------------
  test("golden comparison: minify=true produces byte-exact match to committed golden") {
    withTempDir("min") { tmpDir =>
      val (destDir, result) = buildFixture(tmpDir, minify = true)
      val goldenDir         = resourceDir("fixture-site-expected-min")

      // No diagnostics expected for a clean build.
      assertEquals(
        result.diagnostics.size,
        0,
        s"Expected zero diagnostics, got: ${result.diagnostics}"
      )

      // Structural assertion: the file sets must be identical.
      val producedFiles = fileSet(destDir)
      val goldenFiles   = fileSet(goldenDir)
      assertEquals(
        producedFiles,
        goldenFiles,
        s"File set mismatch.\nProduced: $producedFiles\nGolden: $goldenFiles"
      )

      // Byte-exact assertion: every file's content must match.
      goldenFiles.foreach { rel =>
        val producedContent = FileOps.readString(destDir.resolve(rel))
        val goldenContent   = FileOps.readString(goldenDir.resolve(rel))
        assertEquals(
          producedContent,
          goldenContent,
          s"Content mismatch for '$rel'"
        )
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Minify differential: the two golden trees DIFFER
  // Proves minify:true actually transforms output (not a silent no-op).
  // Case 11 from site-pipeline-design.md section 9.
  // ---------------------------------------------------------------------------
  test("minify differential: minify=true tree differs from minify=false tree") {
    withTempDir("diff") { tmpDir =>
      val (destNoMin, _) = buildFixture(tmpDir, minify = false)
      val (destMin, _)   = buildFixture(tmpDir, minify = true)

      // Both trees must have the same file set.
      val noMinFiles = fileSet(destNoMin)
      val minFiles   = fileSet(destMin)
      assertEquals(
        noMinFiles,
        minFiles,
        "File sets must match between minify:false and minify:true"
      )

      // At least one file must differ (proving minify is not a no-op).
      val anyDiff = noMinFiles.exists { rel =>
        val noMinContent = FileOps.readString(destNoMin.resolve(rel))
        val minContent   = FileOps.readString(destMin.resolve(rel))
        noMinContent != minContent
      }
      assert(
        anyDiff,
        "minify:true must produce at least one file different from minify:false (minifier must not be a no-op)"
      )
    }
  }

  // ---------------------------------------------------------------------------
  // Structural assertions per design section 9:
  // - _layouts/, _includes/, _config.yml do NOT appear in the output
  // - static.txt appears unchanged
  // - about.md -> about/index.html (permalink)
  // - assets/style.scss -> assets/style.css (sass compilation)
  // ---------------------------------------------------------------------------
  test("structural: special directories and config excluded from output") {
    withTempDir("struct") { tmpDir =>
      val (destDir, _) = buildFixture(tmpDir, minify = false)
      val produced     = fileSet(destDir)

      // _layouts/ must not appear in output.
      assert(
        !produced.exists(_.startsWith("_layouts")),
        s"_layouts/ must not appear in output, got: $produced"
      )
      // _includes/ must not appear in output.
      assert(
        !produced.exists(_.startsWith("_includes")),
        s"_includes/ must not appear in output, got: $produced"
      )
      // _config.yml must not appear in output.
      assert(
        !produced.exists(_ == "_config.yml"),
        s"_config.yml must not appear in output, got: $produced"
      )
    }
  }

  test("structural: static.txt copied verbatim (byte-exact)") {
    withTempDir("static") { tmpDir =>
      val fixtureDir   = resourceDir("fixture-site")
      val (destDir, _) = buildFixture(tmpDir, minify = false)

      val sourceContent   = FileOps.readString(fixtureDir.resolve("static.txt"))
      val producedContent = FileOps.readString(destDir.resolve("static.txt"))
      assertEquals(
        producedContent,
        sourceContent,
        "static.txt must be copied byte-identical from source to output"
      )
    }
  }

  test("structural: about.md with permalink /about/ produces about/index.html") {
    withTempDir("permalink") { tmpDir =>
      val (destDir, _) = buildFixture(tmpDir, minify = false)

      // about/index.html must exist (from permalink: /about/).
      assert(
        FileOps.exists(destDir.resolve("about").resolve("index.html")),
        "about/index.html must exist (from permalink: /about/)"
      )
      // about.html must NOT exist (the old source-relative path).
      assert(
        !FileOps.exists(destDir.resolve("about.html")),
        "about.html must not exist (permalink override to /about/)"
      )
      // about.md must NOT exist (the source file).
      assert(
        !FileOps.exists(destDir.resolve("about.md")),
        "about.md must not exist in output"
      )
    }
  }

  test("structural: assets/style.scss compiles to assets/style.css") {
    withTempDir("sass") { tmpDir =>
      val (destDir, _) = buildFixture(tmpDir, minify = false)

      // assets/style.css must exist (from scss compilation).
      assert(
        FileOps.exists(destDir.resolve("assets").resolve("style.css")),
        "assets/style.css must exist (scss compiled to css)"
      )
      // assets/style.scss must NOT exist (no verbatim copy of the source).
      assert(
        !FileOps.exists(destDir.resolve("assets").resolve("style.scss")),
        "assets/style.scss must not exist in output (it was compiled, not copied)"
      )
    }
  }
}
