/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Structural comparison tests: verifies that our renderer produces SVGs
 * with the same graph topology (nodes, edges, labels) as reference
 * Graphviz output generated by the `dot` / `neato` binaries.
 *
 * Known renderer differences (documented, not bugs):
 *
 *   1. Edge labels with spring layout: the Neato layout engine does
 *      not position edge labels, so they are suppressed (the
 *      renderer skips labels when coordinates are 0,0).  Label
 *      comparisons filter out edge-only labels.
 *
 *   2. Multi-line labels: Graphviz splits `label="First\nNode"` into
 *      separate <text> elements; our renderer emits a single <text>
 *      with a literal newline.  Comparisons split multi-line text.
 */
package ssg
package graphviz
package render

import munit.FunSuite
import scala.io.Source

final class ReferenceComparisonSuite extends FunSuite {

  // -- DOT inputs (identical to DotGallerySuite) --------------------------------

  private val dot1 = "digraph G { }"
  private val dot2 = "digraph G { a }"
  private val dot3 = "digraph G { Hello -> World }"
  private val dot4 = "graph { a -- b; b -- c; a -- c; d -- c; e -- c; e -- a; }"
  private val dot5 = "digraph { a -> b; b -> c; c -> d; d -> a; }"
  private val dot6 = """digraph {
                       |  a -> b [label="0.2",weight="0.2"];
                       |  a -> c [label="0.4",weight="0.4"];
                       |  c -> b [label="0.6",weight="0.6"];
                       |  e -> e [label="0.1",weight="0.1"];
                       |  e -> b [label="0.7",weight="0.7"];
                       |}""".stripMargin
  private val dot7 = """digraph G {
                       |  subgraph cluster_0 {
                       |    style=filled; color=lightgrey;
                       |    node [style=filled,color=white];
                       |    a0 -> a1 -> a2 -> a3;
                       |    label = "process #1";
                       |  }
                       |  subgraph cluster_1 {
                       |    node [style=filled];
                       |    b0 -> b1 -> b2 -> b3;
                       |    label = "process #2";
                       |    color=blue
                       |  }
                       |  start -> a0; start -> b0;
                       |  a1 -> b3; b2 -> a3;
                       |  a3 -> a0; a3 -> end; b3 -> end;
                       |  start [shape=Mdiamond];
                       |  end [shape=Msquare];
                       |}""".stripMargin
  private val dot8 = """digraph finite_state_machine {
                       |  rankdir=LR;
                       |  node [shape = doublecircle]; 0 3 4 8;
                       |  node [shape = circle];
                       |  0 -> 2 [label = "SS(B)"];
                       |  0 -> 1 [label = "SS(S)"];
                       |  1 -> 3 [label = "S($end)"];
                       |  2 -> 6 [label = "SS(b)"];
                       |  2 -> 5 [label = "SS(a)"];
                       |  2 -> 4 [label = "S(A)"];
                       |  5 -> 7 [label = "S(b)"];
                       |  5 -> 5 [label = "S(a)"];
                       |  6 -> 6 [label = "S(b)"];
                       |  6 -> 5 [label = "S(a)"];
                       |  7 -> 8 [label = "S(b)"];
                       |  7 -> 5 [label = "S(a)"];
                       |  8 -> 6 [label = "S(b)"];
                       |  8 -> 5 [label = "S(a)"];
                       |}""".stripMargin
  private val dot9 = """digraph G {
                       |  a [shape=box]; b [shape=ellipse]; c [shape=circle];
                       |  d [shape=diamond]; e [shape=plaintext]; f [shape=point];
                       |  g [shape=triangle]; h [shape=pentagon]; i [shape=hexagon];
                       |  j [shape=rect]; k [shape=rectangle]; l [shape=none];
                       |  a -> b -> c -> d -> e -> f -> g -> h -> i -> j -> k -> l
                       |}""".stripMargin
  private val dot10 = """digraph G {
                        |  a -> b [style=bold]
                        |  a -> c [style=dashed]
                        |  a -> d [style=dotted]
                        |  a -> e [dir=both]
                        |  a -> f [dir=back]
                        |  a -> g [dir=none]
                        |}""".stripMargin
  private val dot11 = """digraph G {
                        |  node [style=filled]
                        |  a [fillcolor=green]
                        |  b [fillcolor="#FF0000"]
                        |  c [fillcolor=yellow, fontcolor=blue]
                        |  d [color=red]
                        |  a -> b [color=red]
                        |  b -> c [color=blue]
                        |  c -> d [color="#00FF00"]
                        |}""".stripMargin
  private val dot12 = """strict graph {
                        |  a -- b
                        |  a -- b
                        |  b -- a
                        |}""".stripMargin
  private val dot13 = """digraph MyGraph {
                        |  rankdir=LR;
                        |  label="My Graph Title";
                        |  fontsize=20;
                        |  a -> b -> c;
                        |}""".stripMargin
  private val dot14 = """digraph G {
                        |  subgraph cluster_outer {
                        |    label="Outer";
                        |    subgraph cluster_inner {
                        |      label="Inner";
                        |      a -> b;
                        |    }
                        |    c -> d;
                        |  }
                        |  e -> a;
                        |  d -> e;
                        |}""".stripMargin
  private val dot15 = """graph ER {
                        |  node [shape=box]; course; institute; student;
                        |  node [shape=ellipse]; name0; name1; name2; code; grade; number;
                        |  node [shape=diamond,style=filled,color=lightgrey]; "C-I"; "S-C"; "S-I";
                        |  name0 -- course;
                        |  code -- course;
                        |  course -- "C-I";
                        |  "C-I" -- institute;
                        |  institute -- name1;
                        |  institute -- "S-I";
                        |  "S-I" -- student;
                        |  student -- grade;
                        |  student -- name2;
                        |  student -- number;
                        |  student -- "S-C";
                        |  "S-C" -- course;
                        |}""".stripMargin
  private val dot16 = """graph G {
                        |  run -- intr; intr -- runbl; runbl -- run;
                        |  run -- kernel; kernel -- zombie; kernel -- sleep;
                        |  kernel -- runmem; sleep -- swap;
                        |  swap -- runswap; runswap -- new;
                        |  runswap -- runmem; new -- runmem;
                        |  sleep -- runmem;
                        |}""".stripMargin
  private val dot17 = """digraph G {
                        |  subgraph cluster_0 {
                        |    style=filled; color=lightgrey;
                        |    a0 -> a1 -> a2;
                        |  }
                        |  subgraph cluster_1 {
                        |    color=blue;
                        |    b0 -> b1 -> b2;
                        |  }
                        |  subgraph cluster_2 {
                        |    color=red;
                        |    c0 -> c1 -> c2;
                        |  }
                        |  a0 -> b0; b0 -> c0;
                        |  a2 -> b2; b2 -> c2;
                        |  a1 -> c1;
                        |}""".stripMargin
  private val dot18 = """digraph G {
                        |  node [shape=box];
                        |  a; b;
                        |  node [shape=circle];
                        |  c; d;
                        |  edge [color=red];
                        |  a -> b;
                        |  edge [color=blue];
                        |  c -> d;
                        |  a -> c;
                        |}""".stripMargin
  private val dot19 = """digraph G {
                        |  "Node A" -> "Node B";
                        |  "Node B" -> "Node C (special)";
                        |  "Node A" [label="First\nNode"];
                        |  "Node C (special)" [label="Last \"Node\""];
                        |}""".stripMargin
  private val dot20 = """digraph G {
                        |  root -> a; root -> b; root -> c; root -> d; root -> e;
                        |  root -> f; root -> g; root -> h; root -> i; root -> j;
                        |  a -> leaf1; b -> leaf2; c -> leaf3; d -> leaf4; e -> leaf5;
                        |}""".stripMargin

  // -- Gallery specification ----------------------------------------------------

  /** Each gallery entry: DOT input, reference SVG resource name, directed flag, and known label differences between our renderer and Graphviz.
    *
    * @param refOnlyLabels
    *   labels present in the reference SVG but absent from ours (e.g. edge labels suppressed by spring layout, or node labels for shape=none which Graphviz shows but our renderer suppresses)
    * @param ourOnlyLabels
    *   labels present in our SVG but absent from the reference
    */
  final private case class GalleryEntry(
    name:          String,
    dot:           String,
    refFile:       String,
    isDirected:    Boolean,
    refOnlyLabels: Set[String],
    ourOnlyLabels: Set[String]
  )

  // Edge labels suppressed by spring layout (Neato does not position them)
  private val selfLoopEdgeLabels = Set("0.1", "0.2", "0.4", "0.6", "0.7")
  private val fsmEdgeLabels      = Set("SS(B)", "SS(S)", "S($end)", "SS(b)", "SS(a)", "S(A)", "S(b)", "S(a)")

  private val gallery: Seq[GalleryEntry] = Seq(
    GalleryEntry("empty", dot1, "empty.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("single_node", dot2, "single_node.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("hello_world", dot3, "hello_world.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("undirected", dot4, "undirected.svg", isDirected = false, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("cycle", dot5, "cycle.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("self_loop", dot6, "self_loop.svg", isDirected = true, refOnlyLabels = selfLoopEdgeLabels, ourOnlyLabels = Set.empty),
    GalleryEntry("clusters", dot7, "clusters.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("fsm", dot8, "fsm.svg", isDirected = true, refOnlyLabels = fsmEdgeLabels, ourOnlyLabels = Set.empty),
    // Node "l" has shape=none: Graphviz renders the label, our renderer suppresses text for none shapes
    // Node "f" has shape=point: Graphviz renders the label, our renderer suppresses text for point shapes
    GalleryEntry("shapes", dot9, "shapes.svg", isDirected = true, refOnlyLabels = Set("l", "f"), ourOnlyLabels = Set.empty),
    GalleryEntry("edge_styles", dot10, "edge_styles.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("colors", dot11, "colors.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("strict", dot12, "strict.svg", isDirected = false, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("named_graph", dot13, "named_graph.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("nested_subgraphs", dot14, "nested_subgraphs.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("er_diagram", dot15, "er_diagram.svg", isDirected = false, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("process_states", dot16, "process_states.svg", isDirected = false, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("cross_edges", dot17, "cross_edges.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("multi_defaults", dot18, "multi_defaults.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("quoted_ids", dot19, "quoted_ids.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty),
    GalleryEntry("fan_out", dot20, "fan_out.svg", isDirected = true, refOnlyLabels = Set.empty, ourOnlyLabels = Set.empty)
  )

  // -- SVG structure extraction -------------------------------------------------

  /** Structural info extracted from an SVG for comparison purposes. */
  final private case class SvgStructure(
    nodeCount:    Int,
    edgeCount:    Int,
    textLabels:   Set[String],
    hasArrowDefs: Boolean
  )

  // Regex patterns for extracting structure from Graphviz reference SVGs.
  // Graphviz uses <g id="nodeN" class="node"> for node groups and
  // <g id="edgeN" class="edge"> for edge groups.
  private val refNodeGroupRe = """class="node"""".r
  private val refEdgeGroupRe = """class="edge"""".r
  // Match text content inside <text> elements.
  private val refTextRe = """>([^<]+)</text>""".r
  // Graphviz directed-edge arrowheads use <polygon fill="black"> inside
  // edge groups; this distinguishes directed from undirected graphs.
  private val refArrowRe = """<polygon\s+fill="black"[^/]*/?>""".r

  /** Extracts structural info from a Graphviz-generated reference SVG. */
  private def extractRefStructure(svg: String): SvgStructure = {
    val nodeCount = refNodeGroupRe.findAllMatchIn(svg).size
    val edgeCount = refEdgeGroupRe.findAllMatchIn(svg).size
    val labels    = refTextRe.findAllMatchIn(svg).map(_.group(1).trim).filter(_.nonEmpty).toSet
    val hasArrows = refArrowRe.findFirstIn(svg).isDefined
    SvgStructure(nodeCount, edgeCount, labels, hasArrows)
  }

  // Regex patterns for extracting structure from our SSG-rendered SVGs.
  // Our renderer uses <g class="node"> inside <g class="nodes"> and
  // <g class="edge"> inside <g class="edges">.
  private val ourNodeGroupRe = """class="node"""".r
  private val ourEdgeGroupRe = """class="edge"""".r
  private val ourTextRe      = """>([^<]+)</text>""".r
  private val ourMarkerRe    = """<marker\b""".r

  /** Extracts structural info from our SSG-rendered SVG. */
  private def extractOurStructure(svg: String): SvgStructure = {
    val nodeCount = ourNodeGroupRe.findAllMatchIn(svg).size
    val edgeCount = ourEdgeGroupRe.findAllMatchIn(svg).size
    val labels    = ourTextRe.findAllMatchIn(svg).map(_.group(1).trim).filter(_.nonEmpty).toSet
    val hasArrows = ourMarkerRe.findFirstIn(svg).isDefined
    SvgStructure(nodeCount, edgeCount, labels, hasArrows)
  }

  // -- Helpers ------------------------------------------------------------------

  private val neatoConfig: GraphvizConfig = GraphvizConfig(engine = LayoutEngine.Neato)

  private def renderOurs(dotInput: String): String =
    Graphviz.render(dotInput, neatoConfig)

  /** Reads a reference SVG from classpath resources. */
  private def readReference(fileName: String): String = {
    val stream = getClass.getResourceAsStream("/references/" + fileName)
    assert(stream != null, s"Reference SVG not found on classpath: /references/$fileName")
    val src = Source.fromInputStream(stream, "UTF-8")
    try src.mkString
    finally src.close()
  }

  /** Normalizes HTML entities in extracted text labels for comparison. */
  private def normalizeLabel(s: String): String =
    s.replace("&quot;", "\"").replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">").replace("&#45;", "-").replace("&#39;", "'")

  /** Splits multi-line labels into individual lines for comparison. Graphviz renders `label="First\nNode"` as two separate <text> elements ("First" and "Node"), while our renderer emits one <text>
    * with `"First\nNode"`. Splitting on `\n` normalizes both.
    */
  private def splitLabels(labels: Set[String]): Set[String] =
    labels.flatMap(_.split('\n').map(_.trim).filter(_.nonEmpty))

  // -- Tests --------------------------------------------------------------------

  for (entry <- gallery) {

    // --- Node count ---
    test(s"ref-compare ${entry.name}: same node count") {
      val refSvg    = readReference(entry.refFile)
      val refStruct = extractRefStructure(refSvg)
      val ourSvg    = renderOurs(entry.dot)
      val ourStruct = extractOurStructure(ourSvg)
      assertEquals(
        ourStruct.nodeCount,
        refStruct.nodeCount,
        s"[${entry.name}] node count mismatch (ours=${ourStruct.nodeCount}, ref=${refStruct.nodeCount})"
      )
    }

    // --- Edge count ---
    test(s"ref-compare ${entry.name}: same edge count") {
      val refSvg    = readReference(entry.refFile)
      val refStruct = extractRefStructure(refSvg)
      val ourSvg    = renderOurs(entry.dot)
      val ourStruct = extractOurStructure(ourSvg)
      assertEquals(
        ourStruct.edgeCount,
        refStruct.edgeCount,
        s"[${entry.name}] edge count mismatch (ours=${ourStruct.edgeCount}, ref=${refStruct.edgeCount})"
      )
    }

    // --- Text labels ---
    // Known differences accounted for:
    //   - refOnlyLabels: labels in the reference but not ours (edge labels
    //     suppressed by spring layout, shape=none/point text suppression)
    //   - ourOnlyLabels: labels in ours but not the reference
    //   - multi-line labels split into lines (splitLabels)
    test(s"ref-compare ${entry.name}: same text labels") {
      val refSvg    = readReference(entry.refFile)
      val refStruct = extractRefStructure(refSvg)
      val ourSvg    = renderOurs(entry.dot)
      val ourStruct = extractOurStructure(ourSvg)

      // Normalize HTML entities
      val rawRef  = refStruct.textLabels.map(normalizeLabel)
      val rawOurs = ourStruct.textLabels.map(normalizeLabel)

      // Remove known-different labels from each side
      val filteredRef  = rawRef -- entry.refOnlyLabels
      val filteredOurs = rawOurs -- entry.ourOnlyLabels

      // Split multi-line labels for fair comparison
      val normalizedRef  = splitLabels(filteredRef)
      val normalizedOurs = splitLabels(filteredOurs)

      assertEquals(
        normalizedOurs,
        normalizedRef,
        s"[${entry.name}] text label mismatch\n  only in ours: ${(normalizedOurs -- normalizedRef).mkString(", ")}\n  only in ref:  ${(normalizedRef -- normalizedOurs).mkString(", ")}"
      )
    }

    // --- Arrow markers ---
    test(s"ref-compare ${entry.name}: arrow markers consistent with graph type") {
      val ourSvg    = renderOurs(entry.dot)
      val ourStruct = extractOurStructure(ourSvg)
      if (entry.isDirected) {
        val refSvg    = readReference(entry.refFile)
        val refStruct = extractRefStructure(refSvg)
        if (refStruct.edgeCount > 0) {
          assert(
            ourStruct.hasArrowDefs,
            s"[${entry.name}] directed graph with edges should have arrow marker defs"
          )
        }
      } else {
        assert(
          !ourStruct.hasArrowDefs,
          s"[${entry.name}] undirected graph should NOT have arrow marker defs"
        )
      }
    }
  }
}
