/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * JVM implementation of NativeMath using the Foreign Function & Memory API
 * (stable since JDK 22) to call the native C library's pow() function.
 *
 * The JVM's Math.pow (fdlibm) differs by up to 1 ULP from the native C
 * library's pow() for certain inputs. Since dart-sass spec outputs are
 * generated by the Dart VM (which uses native pow), we must match that
 * behavior to pass the sass-spec test suite.
 */
package ssg
package sass
package util

import java.lang.foreign.{FunctionDescriptor, Linker, ValueLayout}

object NativeMathPlatform extends NativeMathOps {

  private val linker0: Linker                             = Linker.nativeLinker()
  private val lookup0: java.lang.foreign.SymbolLookup     = linker0.defaultLookup()

  /** Bind a native C function `(double) -> double`. */
  private def bind1(name: String): java.lang.invoke.MethodHandle = {
    val sym = lookup0.find(name).orElseThrow(() =>
      new UnsupportedOperationException(s"Native C $name() symbol not found")
    )
    linker0.downcallHandle(
      sym,
      FunctionDescriptor.of(ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE)
    )
  }

  /** Bind a native C function `(double, double) -> double`. */
  private def bind2(name: String): java.lang.invoke.MethodHandle = {
    val sym = lookup0.find(name).orElseThrow(() =>
      new UnsupportedOperationException(s"Native C $name() symbol not found")
    )
    linker0.downcallHandle(
      sym,
      FunctionDescriptor.of(ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE)
    )
  }

  /** Bind a native C function `(double, double, double) -> double`. */
  private def bind3(name: String): java.lang.invoke.MethodHandle = {
    val sym = lookup0.find(name).orElseThrow(() =>
      new UnsupportedOperationException(s"Native C $name() symbol not found")
    )
    linker0.downcallHandle(
      sym,
      FunctionDescriptor.of(
        ValueLayout.JAVA_DOUBLE,
        ValueLayout.JAVA_DOUBLE,
        ValueLayout.JAVA_DOUBLE,
        ValueLayout.JAVA_DOUBLE
      )
    )
  }

  private val nativePowHandle:   java.lang.invoke.MethodHandle = bind2("pow")
  private val nativeFmaHandle:   java.lang.invoke.MethodHandle = bind3("fma")
  private val nativeSinHandle:   java.lang.invoke.MethodHandle = bind1("sin")
  private val nativeCosHandle:   java.lang.invoke.MethodHandle = bind1("cos")
  private val nativeAtan2Handle: java.lang.invoke.MethodHandle = bind2("atan2")

  override def pow(base: Double, exp: Double): Double =
    nativePowHandle.invoke(base, exp).asInstanceOf[Double]

  override def fma(a: Double, b: Double, c: Double): Double =
    nativeFmaHandle.invoke(a, b, c).asInstanceOf[Double]

  override def sin(x: Double): Double =
    nativeSinHandle.invoke(x).asInstanceOf[Double]

  override def cos(x: Double): Double =
    nativeCosHandle.invoke(x).asInstanceOf[Double]

  override def atan2(y: Double, x: Double): Double =
    nativeAtan2Handle.invoke(y, x).asInstanceOf[Double]

  /** sqrt is correctly-rounded by IEEE 754, so Java's Math.sqrt is fine. */
  override def sqrt(x: Double): Double =
    java.lang.Math.sqrt(x)
}
