/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Ported from: lib/src/module.dart, lib/src/module/built_in.dart,
 *              lib/src/module/forwarded_view.dart, lib/src/module/shadowed_view.dart
 * Original: Copyright (c) 2019 Google Inc.
 * Original license: MIT
 *
 * Migration notes:
 *   Renames: module.dart -> Module.scala (merged family)
 *   Convention: Skeleton — public API surface only
 */
package ssg
package sass

import scala.language.implicitConversions
import ssg.sass.ast.css.CssStylesheet
import ssg.sass.ast.sass.ForwardRule
import ssg.sass.value.Value

/** A Sass module — a collection of variables, functions, mixins and CSS generated by evaluating a stylesheet.
  */
trait Module[T <: Callable] {

  /** The canonical URL of this module's source stylesheet, if any. */
  def url: Nullable[String]

  /** The variables defined in this module. */
  def variables: Map[String, Value]

  /** The functions defined in this module. */
  def functions: Map[String, T]

  /** The mixins defined in this module. */
  def mixins: Map[String, T]

  /** The CSS emitted by evaluating this module. */
  def css: CssStylesheet

  /** Whether this module's source was loaded from a dependency. */
  def transitivelyContainsCss: Boolean

  /** Whether this module contains any `@extend` rules. */
  def transitivelyContainsExtensions: Boolean

  /** Sets a variable's value in this module. */
  def setVariable(name: String, value: Value): Unit

  /** Returns an opaque identity token for the variable named [name] — used
    * by dart-sass's `_assertNoConflicts` to deduplicate variables that
    * are re-exported from a common upstream module under the same name.
    *
    * The default implementation uses the module itself as the identity,
    * which causes every variable in an unrelated module to compare
    * unequal. Forwarded/shadowed views override this to delegate to the
    * underlying module so that two forward chains pointing at the same
    * source collapse to a single identity.
    */
  def variableIdentity(name: String): AnyRef = this

  /** Whether this module (or any module it transitively forwards) could
    * have declared a `!default` variable with any of the given [[names]]
    * as its name. Used by dart-sass to detect configuration-arrives-
    * too-late errors when `@forward ... with (...)` configures a module
    * that was already loaded elsewhere.
    *
    * The default implementation returns `false`, matching a module that
    * has no configurable variables. `_EnvironmentModule` overrides this.
    */
  def couldHaveBeenConfigured(names: Set[String]): Boolean = false
}

/** A module defined in Dart/Scala code (e.g. `sass:math`). */
final class BuiltInModule[T <: Callable](
  val name:     String,
  functionList: List[T] = Nil,
  mixinList:    List[T] = Nil,
  variableMap:  Map[String, Value] = Map.empty[String, Value]
) extends Module[T] {

  def url: Nullable[String] = s"sass:$name"

  val functions: Map[String, T] = functionList.map(f => f.name -> f).toMap

  val mixins: Map[String, T] = mixinList.map(m => m.name -> m).toMap

  private val variablesState = scala.collection.mutable.Map.from(variableMap)
  def variables: Map[String, Value] = variablesState.toMap

  // Built-in modules never produce CSS — return an empty stylesheet.
  val css: CssStylesheet = CssStylesheet.empty(url)

  def transitivelyContainsCss:        Boolean = false
  def transitivelyContainsExtensions: Boolean = false

  def setVariable(name: String, value: Value): Unit =
    variablesState(name) = value
}

/** A view of a [[Module]] that only exposes members matching a forward rule (`@forward ... show`/`hide`).
  *
  * Members can additionally be exposed under a `prefix` (`@forward ... as prefix-*`). Filtering order
  * mirrors dart-sass's `_forwardedMap`:
  *   1. The inner module's keys are wrapped through the `prefix` (so `a` becomes `prefix-a`).
  *   2. show/hide filters are applied against the *prefixed* keys — i.e. `hide a` paired with
  *      `as b-*` does NOT hide the upstream `a` (its prefixed form is `b-a`, which doesn't match
  *      the hide name `a`).
  */
final class ForwardedView[T <: Callable](
  val inner:                    Module[T],
  val prefix:                   Nullable[String] = Nullable.empty,
  val shownVariables:           Nullable[Set[String]] = Nullable.empty,
  val shownMixinsAndFunctions:  Nullable[Set[String]] = Nullable.empty,
  val hiddenVariables:          Nullable[Set[String]] = Nullable.empty,
  val hiddenMixinsAndFunctions: Nullable[Set[String]] = Nullable.empty
) extends Module[T] {

  private def _prefixed(name: String): String =
    prefix.fold(name)(p => p + name)

  /** Visibility check against the *prefixed* key. */
  private def _isVarVisible(prefixedName: String): Boolean = {
    val shown  = shownVariables.fold(true)(_.contains(prefixedName))
    val hidden = hiddenVariables.fold(false)(_.contains(prefixedName))
    shown && !hidden
  }

  /** Visibility check against the *prefixed* key. */
  private def _isCallableVisible(prefixedName: String): Boolean = {
    val shown  = shownMixinsAndFunctions.fold(true)(_.contains(prefixedName))
    val hidden = hiddenMixinsAndFunctions.fold(false)(_.contains(prefixedName))
    shown && !hidden
  }

  /** Strips the [[prefix]] from `name` if present, returning the underlying member name. */
  private def _unprefix(name: String): Nullable[String] =
    prefix.fold(Nullable(name)) { p =>
      if (name.startsWith(p)) Nullable(name.substring(p.length))
      else Nullable.empty
    }

  def url: Nullable[String] = inner.url

  def variables: Map[String, Value] =
    inner.variables.collect {
      case (n, v) if _isVarVisible(_prefixed(n)) => _prefixed(n) -> v
    }

  def functions: Map[String, T] =
    inner.functions.collect {
      case (n, f) if _isCallableVisible(_prefixed(n)) => _prefixed(n) -> f
    }

  def mixins: Map[String, T] =
    inner.mixins.collect {
      case (n, m) if _isCallableVisible(_prefixed(n)) => _prefixed(n) -> m
    }

  def css:                            CssStylesheet = inner.css
  def transitivelyContainsCss:        Boolean       = inner.transitivelyContainsCss
  def transitivelyContainsExtensions: Boolean       = inner.transitivelyContainsExtensions

  def setVariable(name: String, value: Value): Unit =
    // The incoming `name` is the prefixed key (caller-side). Visibility
    // is checked against that key, then the prefix is stripped before
    // delegating to the inner module's storage.
    if (!_isVarVisible(name))
      throw new IllegalArgumentException(s"Undefined variable: $$$name")
    else
      _unprefix(name).fold(throw new IllegalArgumentException(s"Undefined variable: $$$name")) { underlying =>
        inner.setVariable(underlying, value)
      }

  override def variableIdentity(name: String): AnyRef = {
    val underlying = _unprefix(name)
    if (underlying.isEmpty) this
    else inner.variableIdentity(underlying.get)
  }

  override def couldHaveBeenConfigured(names: Set[String]): Boolean =
    inner.couldHaveBeenConfigured(names)
}

object ForwardedView {

  /** Builds a [[ForwardedView]] from an existing module and a parsed `@forward` rule. */
  def apply[T <: Callable](inner: Module[T], rule: ForwardRule): ForwardedView[T] =
    new ForwardedView[T](
      inner = inner,
      prefix = rule.prefix,
      shownVariables = rule.shownVariables,
      shownMixinsAndFunctions = rule.shownMixinsAndFunctions,
      hiddenVariables = rule.hiddenVariables,
      hiddenMixinsAndFunctions = rule.hiddenMixinsAndFunctions
    )
}

/** A view of a [[Module]] that hides a fixed set of names — typically the variables configured by an enclosing `@use ... with (...)` so they don't shadow themselves when re-exposed.
  */
final class ShadowedView[T <: Callable](
  val inner:             Module[T],
  val shadowedVars:      Set[String] = Set.empty,
  val shadowedMixins:    Set[String] = Set.empty,
  val shadowedFunctions: Set[String] = Set.empty
) extends Module[T] {

  def url: Nullable[String] = inner.url

  def variables: Map[String, Value] =
    inner.variables.filterNot { case (n, _) => shadowedVars.contains(n) }

  def functions: Map[String, T] =
    inner.functions.filterNot { case (n, _) => shadowedFunctions.contains(n) }

  def mixins: Map[String, T] =
    inner.mixins.filterNot { case (n, _) => shadowedMixins.contains(n) }

  def css:                            CssStylesheet = inner.css
  def transitivelyContainsCss:        Boolean       = inner.transitivelyContainsCss
  def transitivelyContainsExtensions: Boolean       = inner.transitivelyContainsExtensions

  def setVariable(name: String, value: Value): Unit =
    if (shadowedVars.contains(name))
      throw new IllegalArgumentException(s"Undefined variable: $$$name")
    else inner.setVariable(name, value)

  override def variableIdentity(name: String): AnyRef = inner.variableIdentity(name)

  override def couldHaveBeenConfigured(names: Set[String]): Boolean =
    inner.couldHaveBeenConfigured(names)
}
