/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Ported from: lib/src/module.dart, lib/src/module/built_in.dart,
 *              lib/src/module/forwarded_view.dart, lib/src/module/shadowed_view.dart
 * Original: Copyright (c) 2019 Google Inc.
 * Original license: MIT
 *
 * Migration notes:
 *   Renames: module.dart -> Module.scala (merged family)
 *   Convention: Skeleton — public API surface only
 */
package ssg
package sass

import scala.language.implicitConversions
import ssg.sass.ast.AstNode
import ssg.sass.ast.css.{ CssComment, CssStylesheet }
import ssg.sass.ast.sass.ForwardRule
import ssg.sass.extend.ExtensionStore
import ssg.sass.value.Value
import ssg.sass.SassScriptException

/** A Sass module — a collection of variables, functions, mixins and CSS generated by evaluating a stylesheet.
  */
trait Module[T <: Callable] {

  /// The canonical URL for this module's source file.
  ///
  /// This may be `null` if the module was loaded from a string without a URL
  /// provided.
  def url: Nullable[String]

  /// Modules that this module uses.
  def upstream: List[Module[T]]

  /// The module's variables.
  def variables: Map[String, Value]

  /// The nodes where each variable in [variables] was defined.
  ///
  /// This stores [AstNode]s rather than [FileSpan]s so it can avoid calling
  /// [AstNode.span] if the span isn't required, since some nodes need to do
  /// real work to manufacture a source span.
  ///
  /// Implementations must ensure that this has the same keys as [variables].
  def variableNodes: Map[String, AstNode]

  /// The module's functions.
  ///
  /// Implementations must ensure that each [Callable] is stored under its
  /// own name.
  def functions: Map[String, T]

  /// The module's mixins.
  ///
  /// Implementations must ensure that each [Callable] is stored under its
  /// own name.
  def mixins: Map[String, T]

  /// The module's CSS tree.
  def css: CssStylesheet

  /// The extension store for this module, tracking extensions and style rules.
  def extensionStore: ExtensionStore

  /// A map from modules in [upstream] to loud comments written in this module
  /// that should be emitted before the given module.
  def preModuleComments: Map[Module[T], List[CssComment]]

  /// Whether this module *or* any modules in [upstream] contain any CSS.
  def transitivelyContainsCss: Boolean

  /// Whether this module *or* any modules in [upstream] contain `@extend`
  /// rules.
  def transitivelyContainsExtensions: Boolean

  /// Sets the variable named [name] to [value], associated with
  /// [nodeWithSpan]'s source span.
  ///
  /// This takes an [AstNode] rather than a [FileSpan] so it can avoid calling
  /// [AstNode.span] if the span isn't required, since some nodes need to do
  /// real work to manufacture a source span.
  ///
  /// Throws a [SassScriptException] if this module doesn't define a variable
  /// named [name].
  def setVariable(name: String, value: Value): Unit

  /// Whether this module exposes no members or CSS.
  def isEmpty: Boolean =
    variables.isEmpty && functions.isEmpty && mixins.isEmpty && css.children.isEmpty

  /// Creates a copy of this module with new [css] and [extender].
  def cloneCss(): Module[T]

  /** Returns an opaque identity token for the variable named [name] — used by dart-sass's `_assertNoConflicts` to deduplicate variables that are re-exported from a common upstream module under the
    * same name.
    *
    * The default implementation uses the module itself as the identity, which causes every variable in an unrelated module to compare unequal. Forwarded/shadowed views override this to delegate to
    * the underlying module so that two forward chains pointing at the same source collapse to a single identity.
    */
  def variableIdentity(name: String): AnyRef = this

  /** Whether this module (or any module it transitively forwards) could have declared a `!default` variable with any of the given [[names]] as its name. Used by dart-sass to detect
    * configuration-arrives- too-late errors when `@forward ... with (...)` configures a module that was already loaded elsewhere.
    *
    * The default implementation returns `false`, matching a module that has no configurable variables. `_EnvironmentModule` overrides this.
    */
  def couldHaveBeenConfigured(names: Set[String]): Boolean = false
}

/** A module defined in Dart/Scala code (e.g. `sass:math`). */
final class BuiltInModule[T <: Callable](
  val name:     String,
  functionList: List[T] = Nil,
  mixinList:    List[T] = Nil,
  variableMap:  Map[String, Value] = Map.empty[String, Value]
) extends Module[T] {

  def url: Nullable[String] = s"sass:$name"

  val upstream: List[Module[T]] = Nil

  val functions: Map[String, T] = functionList.map(f => f.name -> f).toMap

  val mixins: Map[String, T] = mixinList.map(m => m.name -> m).toMap

  private val variablesState = scala.collection.mutable.Map.from(variableMap)
  def variables: Map[String, Value] = variablesState.toMap

  def variableNodes: Map[String, AstNode] = Map.empty

  // Built-in modules never produce CSS — return an empty stylesheet.
  val css: CssStylesheet = CssStylesheet.empty(url)

  val extensionStore: ExtensionStore = ExtensionStore.empty

  val preModuleComments: Map[Module[T], List[CssComment]] = Map.empty

  def transitivelyContainsCss:        Boolean = false
  def transitivelyContainsExtensions: Boolean = false

  // dart-sass built_in.dart:53-58: built-in module variables are read-only.
  def setVariable(name: String, value: Value): Unit = {
    if (!variables.contains(name))
      throw SassScriptException("Undefined variable.")
    throw SassScriptException("Cannot modify built-in variable.")
  }

  def cloneCss(): Module[T] = this
}

/** A view of a [[Module]] that only exposes members matching a forward rule (`@forward ... show`/`hide`).
  *
  * Members can additionally be exposed under a `prefix` (`@forward ... as prefix-*`). Filtering order mirrors dart-sass's `_forwardedMap`:
  *   1. The inner module's keys are wrapped through the `prefix` (so `a` becomes `prefix-a`).
  *   2. show/hide filters are applied against the *prefixed* keys — i.e. `hide a` paired with `as b-*` does NOT hide the upstream `a` (its prefixed form is `b-a`, which doesn't match the hide name
  *      `a`).
  *
  * Port of dart-sass's `ForwardedModuleView` (lib/src/module/forwarded_view.dart).
  * The `variables`, `variableNodes`, `functions`, and `mixins` accessors
  * delegate to the inner module's live maps through filtering logic,
  * so changes to the inner module after the view is created are reflected
  * automatically — matching dart-sass's lazy `PrefixedMapView` /
  * `LimitedMapView` semantics.
  */
final class ForwardedView[T <: Callable](
  val inner:                    Module[T],
  val prefix:                   Nullable[String] = Nullable.empty,
  val shownVariables:           Nullable[Set[String]] = Nullable.empty,
  val shownMixinsAndFunctions:  Nullable[Set[String]] = Nullable.empty,
  val hiddenVariables:          Nullable[Set[String]] = Nullable.empty,
  val hiddenMixinsAndFunctions: Nullable[Set[String]] = Nullable.empty
) extends Module[T] {

  private def _prefixed(name: String): String =
    prefix.fold(name)(p => p + name)

  /** Visibility check against the *prefixed* key. */
  private def _isVarVisible(prefixedName: String): Boolean = {
    val shown  = shownVariables.fold(true)(_.contains(prefixedName))
    val hidden = hiddenVariables.fold(false)(_.contains(prefixedName))
    shown && !hidden
  }

  /** Visibility check against the *prefixed* key. */
  private def _isCallableVisible(prefixedName: String): Boolean = {
    val shown  = shownMixinsAndFunctions.fold(true)(_.contains(prefixedName))
    val hidden = hiddenMixinsAndFunctions.fold(false)(_.contains(prefixedName))
    shown && !hidden
  }

  def url: Nullable[String] = inner.url

  def upstream: List[Module[T]] = inner.upstream

  def variables: Map[String, Value] =
    inner.variables.collect {
      case (n, v) if _isVarVisible(_prefixed(n)) => _prefixed(n) -> v
    }

  def variableNodes: Map[String, AstNode] =
    inner.variableNodes.collect {
      case (n, node) if _isVarVisible(_prefixed(n)) => _prefixed(n) -> node
    }

  def functions: Map[String, T] =
    inner.functions.collect {
      case (n, f) if _isCallableVisible(_prefixed(n)) => _prefixed(n) -> f
    }

  def mixins: Map[String, T] =
    inner.mixins.collect {
      case (n, m) if _isCallableVisible(_prefixed(n)) => _prefixed(n) -> m
    }

  def css:                            CssStylesheet                    = inner.css
  def extensionStore:                 ExtensionStore                   = inner.extensionStore
  def preModuleComments:              Map[Module[T], List[CssComment]] = inner.preModuleComments
  def transitivelyContainsCss:        Boolean                          = inner.transitivelyContainsCss
  def transitivelyContainsExtensions: Boolean                          = inner.transitivelyContainsExtensions

  /// Port of dart-sass `ForwardedModuleView.setVariable`.
  def setVariable(name: String, value: Value): Unit = {
    // dart-sass: if `shownVariables` is set and doesn't contain this name, reject.
    shownVariables.foreach { shown =>
      if (!shown.contains(name))
        throw SassScriptException("Undefined variable.")
    }
    // dart-sass: if `hiddenVariables` is set and contains this name, reject.
    hiddenVariables.foreach { hidden =>
      if (hidden.contains(name))
        throw SassScriptException("Undefined variable.")
    }
    // Strip the prefix before delegating to the inner module.
    var unprefixed = name
    prefix.foreach { p =>
      if (!name.startsWith(p))
        throw SassScriptException("Undefined variable.")
      unprefixed = name.substring(p.length)
    }
    inner.setVariable(unprefixed, value)
  }

  /// Port of dart-sass `ForwardedModuleView.cloneCss`.
  /// Returns a ForwardedView wrapping the cloned inner module, preserving
  /// the forward rule — matching `ForwardedModuleView(_inner.cloneCss(), _rule)`.
  def cloneCss(): Module[T] =
    new ForwardedView[T](
      inner.cloneCss(),
      prefix,
      shownVariables,
      shownMixinsAndFunctions,
      hiddenVariables,
      hiddenMixinsAndFunctions
    )

  /// Port of dart-sass `ForwardedModuleView.variableIdentity`.
  override def variableIdentity(name: String): AnyRef = {
    assert(variables.contains(name))
    var unprefixed = name
    prefix.foreach { p =>
      assert(name.startsWith(p))
      unprefixed = name.substring(p.length)
    }
    inner.variableIdentity(unprefixed)
  }

  /// Port of dart-sass `ForwardedModuleView.couldHaveBeenConfigured`.
  override def couldHaveBeenConfigured(names: Set[String]): Boolean = {
    assert(shownVariables.fold(true)(_ => true) || hiddenVariables.fold(true)(_ => true))
    if (prefix.isEmpty && shownVariables.isEmpty &&
        hiddenVariables.fold(true)(_.isEmpty)) {
      return inner.couldHaveBeenConfigured(names)
    }
    var adjusted = names
    prefix.foreach { p =>
      adjusted = adjusted.collect {
        case n if n.startsWith(p) => n.substring(p.length)
      }
    }
    shownVariables match {
      case safelist if safelist.isDefined =>
        inner.couldHaveBeenConfigured(adjusted.intersect(safelist.get))
      case _ =>
        hiddenVariables match {
          case blocklist if blocklist.isDefined && blocklist.get.nonEmpty =>
            inner.couldHaveBeenConfigured(adjusted.diff(blocklist.get))
          case _ =>
            inner.couldHaveBeenConfigured(adjusted)
        }
    }
  }

  /// Port of dart-sass `ForwardedModuleView.==`.
  override def equals(other: Any): Boolean = other match {
    case that: ForwardedView[?] =>
      inner == that.inner &&
        prefix == that.prefix &&
        shownVariables == that.shownVariables &&
        shownMixinsAndFunctions == that.shownMixinsAndFunctions &&
        hiddenVariables == that.hiddenVariables &&
        hiddenMixinsAndFunctions == that.hiddenMixinsAndFunctions
    case _ => false
  }

  /// Port of dart-sass `ForwardedModuleView.hashCode`.
  override def hashCode: Int = inner.hashCode ^ prefix.hashCode

  override def toString: String = s"forwarded $inner"
}

object ForwardedView {

  /** Builds a [[ForwardedView]] from an existing module and a parsed `@forward` rule. */
  def apply[T <: Callable](inner: Module[T], rule: ForwardRule): ForwardedView[T] =
    new ForwardedView[T](
      inner = inner,
      prefix = rule.prefix,
      shownVariables = rule.shownVariables,
      shownMixinsAndFunctions = rule.shownMixinsAndFunctions,
      hiddenVariables = rule.hiddenVariables,
      hiddenMixinsAndFunctions = rule.hiddenMixinsAndFunctions
    )

  /** Like [[ForwardedView]], but returns `inner` as-is if it doesn't need
    * any modification. Port of dart-sass `ForwardedModuleView.ifNecessary`.
    */
  def ifNecessary[T <: Callable](inner: Module[T], rule: ForwardRule): Module[T] = {
    if (rule.prefix.isEmpty &&
        rule.shownMixinsAndFunctions.isEmpty &&
        rule.shownVariables.isEmpty &&
        rule.hiddenMixinsAndFunctions.fold(true)(_.isEmpty) &&
        rule.hiddenVariables.fold(true)(_.isEmpty)) {
      inner
    } else {
      ForwardedView(inner, rule)
    }
  }
}

/** A view of a [[Module]] that hides a fixed set of names — typically the
  * variables configured by an enclosing `@use ... with (...)` so they don't
  * shadow themselves when re-exposed.
  *
  * Port of dart-sass's `ShadowedModuleView` (lib/src/module/shadowed_view.dart).
  * The `variables`, `variableNodes`, `functions`, and `mixins` accessors
  * delegate to the inner module's live maps through filtering logic,
  * so changes to the inner module after the view is created are reflected
  * automatically.
  */
final class ShadowedView[T <: Callable](
  val inner:             Module[T],
  val shadowedVars:      Set[String] = Set.empty,
  val shadowedMixins:    Set[String] = Set.empty,
  val shadowedFunctions: Set[String] = Set.empty
) extends Module[T] {

  def url: Nullable[String] = inner.url

  def upstream: List[Module[T]] = inner.upstream

  def variables: Map[String, Value] =
    inner.variables.filterNot { case (n, _) => shadowedVars.contains(n) }

  def variableNodes: Map[String, AstNode] =
    inner.variableNodes.filterNot { case (n, _) => shadowedVars.contains(n) }

  def functions: Map[String, T] =
    inner.functions.filterNot { case (n, _) => shadowedFunctions.contains(n) }

  def mixins: Map[String, T] =
    inner.mixins.filterNot { case (n, _) => shadowedMixins.contains(n) }

  def css:                            CssStylesheet                    = inner.css
  def extensionStore:                 ExtensionStore                   = inner.extensionStore
  def preModuleComments:              Map[Module[T], List[CssComment]] = inner.preModuleComments
  def transitivelyContainsCss:        Boolean                          = inner.transitivelyContainsCss
  def transitivelyContainsExtensions: Boolean                          = inner.transitivelyContainsExtensions

  /// Returns whether this module exposes no members or CSS.
  /// Port of dart-sass `ShadowedModuleView.isEmpty`.
  override def isEmpty: Boolean =
    variables.isEmpty && functions.isEmpty && mixins.isEmpty && css.children.isEmpty

  /// Port of dart-sass `ShadowedModuleView.setVariable`.
  def setVariable(name: String, value: Value): Unit =
    if (!variables.contains(name))
      throw SassScriptException("Undefined variable.")
    else inner.setVariable(name, value)

  /// Port of dart-sass `ShadowedModuleView.cloneCss`.
  /// Preserves the shadow sets when cloning, wrapping the cloned inner.
  def cloneCss(): Module[T] =
    new ShadowedView[T](inner.cloneCss(), shadowedVars, shadowedMixins, shadowedFunctions)

  /// Port of dart-sass `ShadowedModuleView.variableIdentity`.
  override def variableIdentity(name: String): AnyRef = {
    assert(variables.contains(name))
    inner.variableIdentity(name)
  }

  /// Port of dart-sass `ShadowedModuleView.couldHaveBeenConfigured`.
  override def couldHaveBeenConfigured(names: Set[String]): Boolean =
    if (variables == inner.variables)
      inner.couldHaveBeenConfigured(names)
    else
      inner.couldHaveBeenConfigured(
        variables.keysIterator.filter(names.contains).toSet
      )

  /// Port of dart-sass `ShadowedModuleView.==`.
  override def equals(other: Any): Boolean = other match {
    case that: ShadowedView[?] =>
      inner == that.inner &&
        variables.keys.toSeq == that.variables.keys.toSeq &&
        functions.keys.toSeq == that.functions.keys.toSeq &&
        mixins.keys.toSeq == that.mixins.keys.toSeq
    case _ => false
  }

  /// Port of dart-sass `ShadowedModuleView.hashCode`.
  override def hashCode: Int = inner.hashCode

  override def toString: String = s"shadowed $inner"
}

object ShadowedView {

  /// Like [[ShadowedView]], but returns `null` if [inner] would be unchanged.
  /// Port of dart-sass `ShadowedModuleView.ifNecessary`.
  def ifNecessary[T <: Callable](
    inner:     Module[T],
    variables: Set[String] = Set.empty,
    functions: Set[String] = Set.empty,
    mixins:    Set[String] = Set.empty
  ): Nullable[ShadowedView[T]] = {
    val needsVars = variables.nonEmpty && inner.variables.keysIterator.exists(variables.contains)
    val needsFns  = functions.nonEmpty && inner.functions.keysIterator.exists(functions.contains)
    val needsMxs  = mixins.nonEmpty && inner.mixins.keysIterator.exists(mixins.contains)
    if (needsVars || needsFns || needsMxs)
      Nullable(new ShadowedView[T](inner, variables, mixins, functions))
    else
      Nullable.empty
  }
}
