/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Build-time generator for ssg.md.util.misc.EmbeddedResources (Scala.js platform, ISS-979).
 *
 * Class.getResourceAsStream is unavailable on Scala.js. Rather than resolve resources against the
 * process working directory (which only works inside the SSG repository tree), the JS build embeds
 * ssg-md's main runtime resources directly into the compiled output. This generator walks the
 * ssg-md main resources directory and emits a Scala object mapping the classpath-absolute resource
 * path (e.g. "/EmojiReference.txt") to the resource bytes.
 *
 * Resource bytes are Base64-encoded (ASCII) and split into multiple string literals to stay well
 * under the JVM 64KB string-constant (UTF-8 byte) limit — entities.properties (~24KB) and
 * EmojiReference.txt (~724KB) both exceed comfortable single-literal sizes once decoding overhead is
 * considered. The chunks are concatenated and Base64-decoded lazily on first access so unused
 * resources cost nothing at object initialization.
 */

import sbt._
import java.nio.file.Files
import java.util.Base64

object EmbeddedResourcesGen {

  // Base64 is pure ASCII, so character count equals UTF-8 byte count. 40000 keeps each string
  // literal comfortably below the 65535-byte classfile constant-pool limit.
  private val ChunkSize: Int = 40000

  /** Walks `resourceDir` and writes a Scala object embedding every file's bytes into `outFile`. */
  def generate(resourceDir: File, outFile: File, log: sbt.util.Logger): Unit = {
    val files: Seq[File] =
      if (resourceDir.isDirectory) {
        (resourceDir ** "*").get.filter(_.isFile).sortBy(_.getPath)
      } else {
        Seq.empty
      }

    val sb = new StringBuilder

    sb.append("/*\n")
    sb.append(" * Copyright (c) 2026 SSG contributors\n")
    sb.append(" * SPDX-License-Identifier: Apache-2.0\n")
    sb.append(" *\n")
    sb.append(" * GENERATED by project/EmbeddedResourcesGen.scala (ISS-979) — do not edit by hand.\n")
    sb.append(" * Embeds ssg-md's main runtime resources for the Scala.js platform so resource lookup\n")
    sb.append(" * does not depend on the process working directory.\n")
    sb.append(" */\n")
    sb.append("package ssg\n")
    sb.append("package md\n")
    sb.append("package util\n")
    sb.append("package misc\n\n")
    sb.append("import java.util.Base64\n\n")
    sb.append("object EmbeddedResources {\n\n")

    val entries = files.zipWithIndex.map { case (file, idx) =>
      val rel     = resourceDir.toPath.relativize(file.toPath).toString.replace('\\', '/')
      val path    = "/" + rel
      val bytes   = Files.readAllBytes(file.toPath)
      val encoded = Base64.getEncoder.encodeToString(bytes)
      val name    = "res" + idx

      sb.append("  private def ").append(name).append("(): Array[Byte] = {\n")
      sb.append("    val b = new StringBuilder\n")
      var off = 0
      while (off < encoded.length) {
        val end   = math.min(off + ChunkSize, encoded.length)
        val chunk = encoded.substring(off, end)
        sb.append("    b.append(\"").append(chunk).append("\")\n")
        off = end
      }
      if (encoded.isEmpty) {
        sb.append("    val _ = b // empty resource\n")
      }
      sb.append("    Base64.getDecoder.decode(b.toString)\n")
      sb.append("  }\n\n")

      (path, name)
    }

    sb.append("  /** Classpath-absolute resource path -> thunk producing freshly-decoded bytes. */\n")
    sb.append("  val resources: Map[String, () => Array[Byte]] = Map(\n")
    entries.zipWithIndex.foreach { case ((path, name), i) =>
      sb.append("    \"").append(escape(path)).append("\" -> (() => ").append(name).append("())")
      if (i < entries.length - 1) {
        sb.append(",")
      }
      sb.append("\n")
    }
    sb.append("  )\n")
    sb.append("}\n")

    Files.createDirectories(outFile.toPath.getParent)
    IO.write(outFile, sb.toString)
    log.info(s"[ssg-md JS] embedded ${entries.length} runtime resource(s) into ${outFile.getName}")
  }

  private def escape(s: String): String =
    s.flatMap {
      case '\\' => "\\\\"
      case '"'  => "\\\""
      case c    => c.toString
    }
}
