/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0 */
package ssg
package commons
package io

import scala.scalajs.js

/** ISS-1127 [R0610-P1]: JS FilePathPlatform path-handling bugs — the same bug class fixed on Native by ISS-980.
  *
  * The JS implementation (ssg-commons/src/main/scalajs/ssg/commons/io/FilePathPlatform.scala) mishandles absolute paths: `normalize` (lines 48-61) splits on "/" and drops the empty leading segment,
  * so an absolute input like "/a/../b" comes back as the relative "b"; `toAbsolute` (lines 45-46) prepends "/" instead of resolving against the working directory; `cwd` (lines 76-77) returns the
  * literal "."; `parent` (lines 15-20) returns None for "/a" because of the `lastSep <= 0` guard, instead of Some("/").
  *
  * Expected semantics are defined by the JVM reference implementation ssg-commons/src/main/scalajvm/ssg/commons/io/FilePathPlatform.scala, which wraps java.nio.file.Path:
  *   - normalize = Path.normalize() (line 41-42); per the java.nio.file.Path.normalize javadoc, redundant "." names are removed and a name followed by ".." removes both, while the root component is
  *     preserved — an absolute path stays absolute.
  *   - toAbsolute = Path.toAbsolutePath (line 38-39), which resolves relative paths against the default directory (the process working directory).
  *   - cwd = Paths.get(".").toAbsolutePath.normalize() (line 57-58).
  *   - parent = Path.getParent (line 18-21); Paths.get("/a").getParent is the root "/".
  *   - fileName = Path.getFileName (line 31-34), null for the root, mapped to "".
  *   - resolve(FilePath) = Path.resolve (line 26-29) — resolving an absolute child returns that child.
  *   - of = Paths.get(path) rendered via toString (line 54-55) — redundant separators are collapsed.
  *
  * Every hard-coded expected value below was generated by evaluating the same expression with java.nio.file.Paths on the JVM (anti-cheat C11): normalize("/a/../b") == "/b", normalize("/a/./b") ==
  * "/a/b", normalize("a/../b") == "b", normalize("/..") == "/", parent("/a") == "/", resolve("/base/dir", "../x/./y").normalize == "/base/x/y", resolve("/", "a/b").normalize == "/a/b",
  * resolve("/a/b", "c/../d").normalize == "/a/b/d", Paths.get("/a/b/c.txt").getFileName == "c.txt", Paths.get("/").getFileName == null, Paths.get("/a/b").resolve(Paths.get("c/d")) == "/a/b/c/d",
  * Paths.get("/a/b").resolve(Paths.get("/x/y")) == "/x/y", Paths.get("/a//b/").toString == "/a/b". These match the values pinned by the merged Native suites FilePathIss980NativeSuite and
  * FilePathIss980ExtraNativeSuite — they are the cross-platform contract.
  *
  * Red until ISS-1127 is fixed. java.nio is unavailable on Scala.js, so the working directory used for comparison is obtained independently of the API under test via Node's process module (the test
  * suites run under Node — sbt `Test / jsEnv` is a NodeJSEnv, as proven by FileOpsIss978JsSuite).
  */
final class FilePathIss1127JsSuite extends munit.FunSuite {

  /** Working directory obtained independently of FilePath, via Node's process.cwd() — the Node-side equivalent of the JVM reference impl's Paths.get(".").toAbsolutePath.normalize()
    * (scalajvm/ssg/commons/io/FilePathPlatform.scala:58).
    */
  private def independentCwd: String =
    js.Dynamic.global.require("process").cwd().asInstanceOf[String]

  test("ISS-1127: normalize keeps an absolute path absolute — /a/../b becomes /b") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:41-42 (Path.normalize);
    // JVM-evaluated: Paths.get("/a/../b").normalize() == "/b".
    assertEquals(FilePath.of("/a/../b").normalize.pathString, "/b")
  }

  test("ISS-1127: normalize removes a single-dot segment without dropping the root — /a/./b becomes /a/b") {
    // JVM-evaluated: Paths.get("/a/./b").normalize() == "/a/b".
    assertEquals(FilePath.of("/a/./b").normalize.pathString, "/a/b")
  }

  test("ISS-1127: normalize keeps a relative path relative — a/../b becomes b") {
    // JVM-evaluated: Paths.get("a/../b").normalize() == "b".
    assertEquals(FilePath.of("a/../b").normalize.pathString, "b")
  }

  test("ISS-1127: normalize of /.. collapses to the root /") {
    // JVM-evaluated: Paths.get("/..").normalize() == "/" — the root has no parent, so a leading ".."
    // on an absolute path is discarded and the root is preserved.
    assertEquals(FilePath.of("/..").normalize.pathString, "/")
  }

  test("ISS-1127: normalized absolute path reports isAbsolute") {
    // Follows from the cases above: the root component survives normalization on the JVM.
    assert(FilePath.of("/a/../b").normalize.isAbsolute)
  }

  test("ISS-1127: toAbsolute resolves a relative path against the real working directory") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:38-39 (Path.toAbsolutePath resolves
    // against the default directory). On the JVM, Paths.get("rel/file.txt").toAbsolutePath ==
    // <cwd> + "/rel/file.txt".
    val cwd      = independentCwd
    val absolute = FilePath.of("rel/file.txt").toAbsolute.pathString
    assertEquals(absolute, cwd + "/rel/file.txt")
  }

  test("ISS-1127: toAbsolute leaves an already-absolute path unchanged") {
    // JVM-evaluated: Paths.get("/etc/hosts").toAbsolutePath == "/etc/hosts".
    assertEquals(FilePath.of("/etc/hosts").toAbsolute.pathString, "/etc/hosts")
  }

  test("ISS-1127: cwd returns the real working directory, not the literal dot") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:57-58
    // (cwd = Paths.get(".").toAbsolutePath.normalize()).
    val cwd = independentCwd
    assertEquals(FilePath.cwd.pathString, cwd)
    assertNotEquals(FilePath.cwd.pathString, ".")
    assert(FilePath.cwd.isAbsolute)
  }

  test("ISS-1127: parent of /a is the root Some(/)") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:18-21 (Path.getParent);
    // JVM-evaluated: Paths.get("/a").getParent == "/".
    assertEquals(FilePath.of("/a").parent.map(_.pathString), Some("/"))
  }

  test("ISS-1127: parent of the root / is None") {
    // JVM-evaluated: Paths.get("/").getParent == null, mapped to None by the JVM impl (lines 18-21).
    assertEquals(FilePath.of("/").parent.map(_.pathString), None)
  }

  test("ISS-1127: resolve then normalize on an absolute base matches the JVM") {
    // JVM-evaluated round trips (anti-cheat C11):
    //   Paths.get("/base/dir").resolve("../x/./y").normalize() == "/base/x/y"
    //   Paths.get("/").resolve("a/b").normalize()              == "/a/b"
    //   Paths.get("/a/b").resolve("c/../d").normalize()        == "/a/b/d"
    assertEquals(FilePath.of("/base/dir").resolve("../x/./y").normalize.pathString, "/base/x/y")
    assertEquals(FilePath.of("/").resolve("a/b").normalize.pathString, "/a/b")
    assertEquals(FilePath.of("/a/b").resolve("c/../d").normalize.pathString, "/a/b/d")
  }

  test("ISS-1127: fileName of an absolute path is the last component") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:31-34 (Path.getFileName).
    // JVM-evaluated: Paths.get("/a/b/c.txt").getFileName == "c.txt".
    assertEquals(FilePath.of("/a/b/c.txt").fileName, "c.txt")
  }

  test("ISS-1127: fileName of the root / is the empty string") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:31-34 — getFileName is null for the root,
    // mapped to "". JVM-evaluated: Paths.get("/").getFileName == null.
    assertEquals(FilePath.of("/").fileName, "")
  }

  test("ISS-1127: resolve(FilePath) with a relative child appends, mirroring Path.resolve") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:26-29 (Path.resolve).
    // JVM-evaluated: Paths.get("/a/b").resolve(Paths.get("c/d")) == "/a/b/c/d".
    assertEquals(FilePath.of("/a/b").resolve(FilePath.of("c/d")).pathString, "/a/b/c/d")
  }

  test("ISS-1127: resolve(FilePath) with an absolute child replaces, mirroring Path.resolve") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:26-29 (Path.resolve) — resolving an
    // absolute path returns that absolute path. JVM-evaluated: Paths.get("/a/b").resolve(Paths.get("/x/y")) == "/x/y".
    assertEquals(FilePath.of("/a/b").resolve(FilePath.of("/x/y")).pathString, "/x/y")
  }

  test("ISS-1127: of renders the path the way java.nio.file.Path does (redundant separators collapsed)") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:54-55 (Paths.get(path).toString).
    // JVM-evaluated: Paths.get("/a//b/").toString == "/a/b".
    assertEquals(FilePath.of("/a//b/").pathString, "/a/b")
  }
}
