/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Ported from: flexmark-util-format/src/main/java/com/vladsch/flexmark/util/format/MarkdownTable.java
 * Original: Copyright (c) 2016-2023 Vladimir Schneider
 * Original license: BSD-2-Clause
 */
package ssg
package md
package util
package format

// Forward references: Node, TextCollectingVisitor will be available when util-ast is ported
import ssg.md.util.ast.{ Node, TextCollectingVisitor }
import ssg.md.Nullable
import ssg.md.util.collection.{ MaxAggregator, MinAggregator }
import ssg.md.util.data.DataHolder
import ssg.md.util.format.options.DiscretionaryText
import ssg.md.util.html.CellAlignment
import ssg.md.util.misc.{ CharPredicate, Ref, Utils }
import ssg.md.util.misc.Utils.{ max, maxLimit, min, minLimit }
import ssg.md.util.sequence.{ BasedSequence, LineAppendable, PrefixedSubSequence, RepeatedSequence, SequenceUtils }

import java.util.{ ArrayList, BitSet, Comparator, List as JList }
import java.util.function.BiFunction
import scala.language.implicitConversions
import scala.util.boundary
import scala.util.boundary.break

class MarkdownTable(
  val tableChars: CharSequence,
  var options:    TableFormatOptions
) {

  val header:    TableSection = new TableSection(TableSectionType.HEADER)
  val separator: TableSection = new TableSeparatorSection(TableSectionType.SEPARATOR)
  val body:      TableSection = new TableSection(TableSectionType.BODY)
  val caption:   TableSection = new TableCaptionSection(TableSectionType.CAPTION)

  private var isHeading:       Boolean      = true
  private var _isSeparator:    Boolean      = false
  var formatTableIndentPrefix: CharSequence = if (options == null) "" else options.formatTableIndentPrefix

  // used by finalization and conversion to text
  private var alignments:   Array[CellAlignment] = scala.compiletime.uninitialized
  private var columnWidths: Array[Int]           = scala.compiletime.uninitialized

  // generated by conversion to text
  private val trackedOffsets: ArrayList[TrackedOffset] = new ArrayList[TrackedOffset]()

  private val ALL_SECTIONS:     Array[TableSection] = Array(header, separator, body, caption)
  private val ALL_TABLE_ROWS:   Array[TableSection] = Array(header, separator, body)
  private val ALL_CONTENT_ROWS: Array[TableSection] = Array(header, body)
  private val ALL_HEADER_ROWS:  Array[TableSection] = Array(header)
  private val ALL_BODY_ROWS:    Array[TableSection] = Array(body)

  def this(tableChars: CharSequence, options: Nullable[DataHolder]) = {
    this(tableChars, new TableFormatOptions(options))
  }

  def getCaptionCell: TableCell =
    if (caption.rows.size() > 0 && caption.rows.get(0).cells.size() > 0) caption.rows.get(0).cells.get(0)
    else TableCaptionSection.NULL_CELL

  def setCaptionCell(captionCell: TableCell): Unit = {
    if (caption.rows.size() == 0) {
      caption.rows.add(caption.defaultRow())
    }
    caption.rows.get(0).cells.clear()
    caption.rows.get(0).cells.add(captionCell)
  }

  def getCaption: BasedSequence = getCaptionCell.text

  def setCaption(caption: CharSequence): Unit = {
    val captionCell = getCaptionCell
    setCaptionCell(
      captionCell.withText(
        if (captionCell.openMarker.isEmpty()) "[" else captionCell.openMarker,
        caption,
        if (captionCell.closeMarker.isEmpty()) "]" else captionCell.closeMarker
      )
    )
  }

  /*
   * Used by visitor during table creation
   */
  def setCaptionWithMarkers(
    tableCellNode: Node,
    captionOpen:   CharSequence,
    caption:       CharSequence,
    captionClose:  CharSequence
  ): Unit =
    setCaptionCell(
      new TableCell(
        Nullable(tableCellNode),
        captionOpen,
        if (options.formatTableCaptionSpaces == DiscretionaryText.AS_IS) caption else BasedSequence.of(caption).trim(),
        captionClose,
        1,
        1
      )
    )

  def getHeadingRowCount:     Int = header.rows.size()
  def getSeparatorRowCount:   Int = separator.rows.size()
  def getBodyRowCount:        Int = body.rows.size()
  def getCaptionRowCount:     Int = caption.rows.size()
  def getMaxHeadingColumns:   Int = header.getMaxColumns
  def getMaxSeparatorColumns: Int = separator.getMaxColumns
  def getMaxBodyColumns:      Int = body.getMaxColumns

  def getHaveCaption: Boolean =
    caption.rows.size() > 0 && caption.rows.get(0).cells.size() > 0 && caption.rows.get(0).cells.get(0).columnSpan != 0

  def getMinColumns: Int = {
    val headingColumns   = header.getMinColumns
    val separatorColumns = separator.getMinColumns
    val bodyColumns      = body.getMinColumns
    min(
      if (headingColumns == 0) Integer.MAX_VALUE else headingColumns,
      separatorColumns,
      if (bodyColumns == 0) Integer.MAX_VALUE else bodyColumns
    )
  }

  def getMaxColumns: Int = {
    val headingColumns   = header.getMaxColumns
    val separatorColumns = separator.getMaxColumns
    val bodyColumns      = body.getMaxColumns
    max(headingColumns, separatorColumns, bodyColumns)
  }

  def getMinColumnsWithoutColumns(withSeparator: Boolean, skipColumns: Int*): Int =
    aggregateTotalColumnsWithoutColumns(if (withSeparator) ALL_TABLE_ROWS else ALL_CONTENT_ROWS, MinAggregator, skipColumns.toArray)

  def getMaxColumnsWithoutColumns(withSeparator: Boolean, skipColumns: Int*): Int =
    aggregateTotalColumnsWithoutColumns(if (withSeparator) ALL_TABLE_ROWS else ALL_CONTENT_ROWS, MaxAggregator, skipColumns.toArray)

  def getMinColumnsWithoutRows(withSeparator: Boolean, skipRows: Int*): Int =
    aggregateTotalColumnsWithoutRows(if (withSeparator) ALL_TABLE_ROWS else ALL_CONTENT_ROWS, MinAggregator, skipRows.toArray)

  def getMaxColumnsWithoutRows(withSeparator: Boolean, skipRows: Int*): Int =
    aggregateTotalColumnsWithoutRows(if (withSeparator) ALL_TABLE_ROWS else ALL_CONTENT_ROWS, MaxAggregator, skipRows.toArray)

  def getTrackedOffsets: JList[TrackedOffset] = trackedOffsets

  private def findTrackedOffset(offset: Int): Nullable[TrackedOffset] = {
    var result: Nullable[TrackedOffset] = Nullable(null)
    var done = false
    val iter = trackedOffsets.iterator()
    while (iter.hasNext && !done) {
      val to = iter.next()
      if (to.offset == offset) { result = Nullable(to); done = true }
      else if (to.offset > offset) { done = true }
    }
    result
  }

  def getTrackedOffset(offset: Int): Nullable[TrackedOffset] = findTrackedOffset(offset)

  def getTrackedOffsetIndex(offset: Int): Int = {
    val to = findTrackedOffset(offset)
    if (to.isEmpty) offset else to.get.getIndex
  }

  def getTableStartOffset: Int = {
    // MdNav:diagnostic/4134, index out of range
    val rows = getAllRows
    if (!rows.isEmpty) {
      val row = rows.get(0)
      row.normalizeIfNeeded()
      if (row.cells.size() > 0) row.cells.get(0).getStartOffset(Nullable(null))
      else 0
    } else {
      0
    }
  }

  def getCellOffsetInfo(offset: Int): TableCellOffsetInfo = boundary {
    var r       = 0
    val allRows = getAllSectionRows
    val iter    = allRows.iterator()
    while (iter.hasNext) {
      val row = iter.next()
      row.normalizeIfNeeded()
      val lastCell      = row.cells.get(row.cells.size() - 1)
      val lastSegment   = lastCell.getLastSegment
      var lineEndOffset = lastSegment.baseEndOfLineAnyEOL()
      if (lineEndOffset == -1) lineEndOffset = lastSegment.endOffset

      if (offset <= lineEndOffset) {
        // it is on this line
        var i = 0
        var previousCell: Nullable[TableCell] = Nullable(null)
        val cellIter = row.cells.iterator()
        while (cellIter.hasNext) {
          val cell = cellIter.next()
          if (if (!cell.closeMarker.isEmpty()) offset < cell.closeMarker.endOffset else offset <= cell.text.endOffset) {
            if (offset >= cell.getInsideStartOffset(previousCell) && offset <= cell.getInsideEndOffset) {
              // in the cell area
              break(
                new TableCellOffsetInfo(
                  offset,
                  this,
                  getAllRowsSection(r),
                  Nullable(row),
                  Nullable(cell),
                  r,
                  i,
                  Nullable(Integer.valueOf(i)),
                  Nullable(Integer.valueOf(offset - cell.getInsideStartOffset(previousCell)))
                )
              )
            } else {
              // it the span area or before pipe of first cell
              break(
                new TableCellOffsetInfo(offset, this, getAllRowsSection(r), Nullable(row), Nullable(cell), r, i, Nullable(null), Nullable(null))
              )
            }
          }
          i += 1
          previousCell = Nullable(cell)
        }
        // after the last cell
        break(
          new TableCellOffsetInfo(offset, this, getAllRowsSection(r), Nullable(row), Nullable(lastCell), r, i, Nullable(null), Nullable(null))
        )
      }
      r += 1
    }

    val lastSection = getAllRowsSection(r - 1)
    new TableCellOffsetInfo(offset, this, lastSection, Nullable(null), Nullable(null), r, 0, Nullable(null), Nullable(null))
  }

  def addTrackedOffset(trackedOffset: TrackedOffset): Boolean = {
    val offset = trackedOffset.offset
    trackedOffsets.removeIf(it => it.offset == offset)
    trackedOffsets.add(trackedOffset)

    val info = getCellOffsetInfo(offset)
    if (info.getInsideColumn) {
      // real cell, we can add it to the cells contents
      info.tableRow.get.cells.set(
        info.column,
        info.tableCell.get.withTrackedOffset(
          offset - info.tableCell.get.getTextStartOffset(if (info.column == 0) Nullable(null) else Nullable(info.tableRow.get.cells.get(info.column - 1))),
          trackedOffset.isAfterSpaceEdit,
          trackedOffset.isAfterDelete
        )
      )
      true
    } else if (info.isBeforeCells) {
      info.tableRow.get.beforeOffset = offset
      true
    } else if (info.isInCellSpan) {
      info.tableRow.get.cells.set(info.column, info.tableCell.get.withSpanTrackedOffset(offset - info.tableCell.get.getInsideEndOffset))
      true
    } else if (info.isAfterCells) {
      info.tableRow.get.afterOffset = offset
      true
    } else {
      false
    }
  }

  /*
      Table Manipulation Helper API
   */
  def getAllRows:        JList[TableRow] = getAllSectionsRows(ALL_TABLE_ROWS*)
  def getAllContentRows: JList[TableRow] = getAllSectionsRows(ALL_CONTENT_ROWS*)
  def getAllSectionRows: JList[TableRow] = getAllSectionsRows(ALL_SECTIONS*)

  private def getAllSectionsRows(sections: TableSection*): JList[TableRow] = {
    val rows = new ArrayList[TableRow](header.rows.size() + body.rows.size())
    for (section <- sections)
      rows.addAll(section.rows)
    rows
  }

  def isAllRowsSeparator(index: Int): Boolean =
    index >= header.rows.size() && index < header.rows.size() + separator.rows.size()

  def getAllRowsSection(index: Int): TableSection = {
    var remaining = index
    var found: TableSection = null // NOTE: null at interop boundary
    val iter = ALL_SECTIONS.iterator
    while (iter.hasNext && found == null) {
      val section = iter.next()
      if (remaining < section.rows.size()) {
        found = section
      } else {
        remaining -= section.rows.size()
      }
    }
    found
  }

  def getAllRowsCount:         Int = header.rows.size() + separator.rows.size() + body.rows.size()
  def getAllContentRowsCount:  Int = header.rows.size() + body.rows.size()
  def getAllSectionsRowsCount: Int = header.rows.size() + separator.rows.size() + body.rows.size() + caption.rows.size()

  def forAllRows(manipulator:        TableRowManipulator):                                     Unit = forAllSectionsRows(0, Integer.MAX_VALUE, ALL_TABLE_ROWS, manipulator)
  def forAllRows(startIndex:         Int, manipulator: TableRowManipulator):                   Unit = forAllSectionsRows(startIndex, Integer.MAX_VALUE, ALL_TABLE_ROWS, manipulator)
  def forAllRows(startIndex:         Int, count:       Int, manipulator: TableRowManipulator): Unit = forAllSectionsRows(startIndex, count, ALL_TABLE_ROWS, manipulator)
  def forAllContentRows(manipulator: TableRowManipulator):                                     Unit = forAllSectionsRows(0, Integer.MAX_VALUE, ALL_CONTENT_ROWS, manipulator)
  def forAllContentRows(startIndex:  Int, manipulator: TableRowManipulator):                   Unit = forAllSectionsRows(startIndex, Integer.MAX_VALUE, ALL_CONTENT_ROWS, manipulator)
  def forAllContentRows(startIndex:  Int, count:       Int, manipulator: TableRowManipulator): Unit = forAllSectionsRows(startIndex, count, ALL_CONTENT_ROWS, manipulator)
  def forAllSectionRows(manipulator: TableRowManipulator):                                     Unit = forAllSectionsRows(0, Integer.MAX_VALUE, ALL_SECTIONS, manipulator)
  def forAllSectionRows(startIndex:  Int, manipulator: TableRowManipulator):                   Unit = forAllSectionsRows(startIndex, Integer.MAX_VALUE, ALL_SECTIONS, manipulator)
  def forAllSectionRows(startIndex:  Int, count:       Int, manipulator: TableRowManipulator): Unit = forAllSectionsRows(startIndex, count, ALL_SECTIONS, manipulator)
  def forAllHeaderRows(manipulator:  TableRowManipulator):                                     Unit = forAllSectionsRows(0, Integer.MAX_VALUE, ALL_HEADER_ROWS, manipulator)
  def forAllHeaderRows(startIndex:   Int, manipulator: TableRowManipulator):                   Unit = forAllSectionsRows(startIndex, Integer.MAX_VALUE, ALL_HEADER_ROWS, manipulator)
  def forAllHeaderRows(startIndex:   Int, count:       Int, manipulator: TableRowManipulator): Unit = forAllSectionsRows(startIndex, count, ALL_HEADER_ROWS, manipulator)
  def forAllBodyRows(manipulator:    TableRowManipulator):                                     Unit = forAllSectionsRows(0, Integer.MAX_VALUE, ALL_BODY_ROWS, manipulator)
  def forAllBodyRows(startIndex:     Int, manipulator: TableRowManipulator):                   Unit = forAllSectionsRows(startIndex, Integer.MAX_VALUE, ALL_HEADER_ROWS, manipulator)
  def forAllBodyRows(startIndex:     Int, count:       Int, manipulator: TableRowManipulator): Unit = forAllSectionsRows(startIndex, count, ALL_HEADER_ROWS, manipulator)

  def deleteRows(rowIndex: Int, count: Int): Unit =
    if (rowIndex <= header.rows.size()) {
      var i = count
      while (i > 0 && rowIndex < header.rows.size()) {
        header.rows.remove(rowIndex)
        i -= 1
      }
    } else if (rowIndex >= header.rows.size() + separator.rows.size()) {
      val index = rowIndex - header.rows.size() - separator.rows.size()
      var i     = count
      while (i > 0 && index < body.rows.size()) {
        body.rows.remove(index)
        i -= 1
      }
    }

  def insertRows(rowIndex: Int, count: Int): Unit = {
    val maxColumns = getMaxColumns
    if (rowIndex <= header.rows.size()) {
      insertRowsInto(header.rows, rowIndex, count, maxColumns)
    } else {
      insertRowsInto(body.rows, Utils.rangeLimit(rowIndex - header.rows.size() - separator.rows.size(), 0, body.rows.size()), count, maxColumns)
    }
  }

  private def insertRowsInto(rows: ArrayList[TableRow], index: Int, count: Int, maxColumns: Int): Unit = {
    var i = count
    while (i > 0) {
      val emptyRow = new TableRow()
      emptyRow.appendColumns(maxColumns)
      if (index >= rows.size()) rows.add(emptyRow)
      else rows.add(index, emptyRow)
      i -= 1
    }
  }

  def insertColumns(column: Int, count: Int): Unit = {
    forAllContentRows(
      new TableRowManipulator {
        override def apply(row: TableRow, allRowsIndex: Int, sectionRows: ArrayList[TableRow], sectionRowIndex: Int): Int = {
          sectionRows.get(sectionRowIndex).insertColumns(column, count)
          0
        }
      }
    )
    // insert separator columns separately, since they are not reduced in finalize
    val iter = separator.rows.iterator()
    while (iter.hasNext) iter.next().insertColumns(column, count)
  }

  def deleteColumns(column: Int, count: Int): Unit = {
    forAllContentRows(
      new TableRowManipulator {
        override def apply(row: TableRow, allRowsIndex: Int, sectionRows: ArrayList[TableRow], sectionRowIndex: Int): Int = {
          sectionRows.get(sectionRowIndex).deleteColumns(column, count)
          0
        }
      }
    )
    val iter = separator.rows.iterator()
    while (iter.hasNext) iter.next().deleteColumns(column, count)
  }

  def moveColumn(fromColumn: Int, toColumn: Int): Unit = {
    forAllContentRows(
      new TableRowManipulator {
        override def apply(row: TableRow, allRowsIndex: Int, sectionRows: ArrayList[TableRow], sectionRowIndex: Int): Int = {
          sectionRows.get(sectionRowIndex).moveColumn(fromColumn, toColumn)
          0
        }
      }
    )
    val iter = separator.rows.iterator()
    while (iter.hasNext) iter.next().moveColumn(fromColumn, toColumn)
  }

  /** Test all rows for having given column empty. All columns after row's max column are empty
    *
    * @param column
    *   index in allRows list
    * @return
    *   true if column is empty for all rows, separator row excluded
    */
  def isEmptyColumn(column: Int): Boolean = {
    val result = Array(true)
    forAllContentRows(
      new TableRowManipulator {
        override def apply(row: TableRow, allRowsIndex: Int, sectionRows: ArrayList[TableRow], sectionRowIndex: Int): Int =
          if (!row.isEmptyColumn(column)) { result(0) = false; TableRowManipulator.BREAK }
          else 0
      }
    )
    result(0)
  }

  def isAllRowsEmptyAt(rowIndex:     Int): Boolean = isEmptyRowAt(rowIndex, ALL_TABLE_ROWS)
  def isContentRowsEmptyAt(rowIndex: Int): Boolean = isEmptyRowAt(rowIndex, ALL_CONTENT_ROWS)

  private def isEmptyRowAt(rowIndex: Int, sections: Array[TableSection]): Boolean = {
    val result = Array(false)
    forAllSectionsRows(
      rowIndex,
      1,
      sections,
      new TableRowManipulator {
        override def apply(row: TableRow, allRowsIndex: Int, sectionRows: ArrayList[TableRow], sectionRowIndex: Int): Int = {
          if (row.isEmpty) result(0) = true
          TableRowManipulator.BREAK
        }
      }
    )
    result(0)
  }

  /*
   * Used during table construction by building the table
   * as the AST visiting process (Flexmark or HTML)
   */
  def getHeader:                        Boolean = isHeading
  def setHeader(header:       Boolean): Unit    = isHeading = header
  def isSeparator:                      Boolean = _isSeparator
  def setSeparator(separator: Boolean): Unit    = _isSeparator = separator

  def setHeader():    Unit = { isHeading = true; _isSeparator = false }
  def setSeparator(): Unit = { _isSeparator = true; isHeading = false }
  def setBody():      Unit = { _isSeparator = false; isHeading = false }

  def nextRow(): Unit = {
    if (_isSeparator) throw new IllegalStateException("Only one separator row allowed")
    if (isHeading) header.nextRow() else body.nextRow()
  }

  /** @param cell
    *   cell to add
    */
  def addCell(cell: TableCell): Unit = {
    val tableSection = if (_isSeparator) separator else if (isHeading) header else body

    if (_isSeparator && (cell.columnSpan != 1 || cell.rowSpan != 1)) {
      throw new IllegalStateException("Separator columns cannot span rows/columns")
    }

    val currentRow = tableSection.get(tableSection.row)

    // skip cells that are already set
    while (tableSection.column < currentRow.cells.size() && currentRow.cells.get(tableSection.column) != null)
      tableSection.column += 1

    var rowSpan = 0
    while (rowSpan < cell.rowSpan) {
      tableSection.get(tableSection.row + rowSpan).set(tableSection.column, cell)

      // set the rest to NULL cells up to null column
      var columnSpan = 1
      while (columnSpan < cell.columnSpan) {
        tableSection.expandTo(tableSection.row + rowSpan, tableSection.column + columnSpan)
        if (tableSection.get(tableSection.row + rowSpan).cells.get(tableSection.column + columnSpan) != null) {
          columnSpan = cell.columnSpan // break
        } else {
          tableSection.rows.get(tableSection.row + rowSpan).set(tableSection.column + columnSpan, TableCell.NULL)
          columnSpan += 1
        }
      }
      rowSpan += 1
    }

    tableSection.column += cell.columnSpan
  }

  def normalize(): Unit = {
    header.normalize()
    separator.normalize()
    body.normalize()
  }

  def finalizeTable(): Unit = {
    // remove null cells
    normalize()

    if (options.fillMissingColumns) {
      fillMissingColumns(Nullable(options.formatTableFillMissingMinColumn.getOrElse(null)))
    }

    val sepColumns = getMaxColumns
    alignments = new Array[CellAlignment](sepColumns)
    columnWidths = new Array[Int](sepColumns)
    val spanAlignment = new BitSet(sepColumns)
    var columnSpans   = new ArrayList[MarkdownTable.ColumnSpan]()
    val delta         = new Ref[Integer](0)

    if (separator.rows.size() > 0) {
      val row      = separator.rows.get(0)
      var jSpan    = 0
      val cellIter = row.cells.iterator()
      while (cellIter.hasNext) {
        val cell = cellIter.next()
        // set alignment if not already set or was set by a span and this column is not a span
        if ((alignments(jSpan) == null || cell.columnSpan == 1 && spanAlignment.get(jSpan)) && cell.alignment != CellAlignment.NONE) {
          alignments(jSpan) = cell.alignment
          if (cell.columnSpan > 1) spanAlignment.set(jSpan)
        }
        jSpan += cell.columnSpan
      }
    }

    if (header.rows.size() > 0) {
      val rowIter = header.rows.iterator()
      while (rowIter.hasNext) {
        val row   = rowIter.next()
        var j     = 0
        var jSpan = 0
        val kMax  = row.cells.size()
        var k     = 0
        while (k < kMax) {
          val cell = row.cells.get(k)
          if ((alignments(jSpan) == null || cell.columnSpan == 1 && spanAlignment.get(jSpan)) && cell.alignment != CellAlignment.NONE) {
            alignments(jSpan) = cell.alignment
            if (cell.columnSpan > 1) spanAlignment.set(jSpan)
          }

          delta.value = 0
          val cellText = this.cellText(row.cells, k, false, true, 0, null, delta)
          val width    = options.charWidthProvider.getStringWidth(cellText) + options.spacePad + options.pipeWidth * cell.columnSpan
          if (cell.columnSpan > 1) {
            columnSpans.add(new MarkdownTable.ColumnSpan(j, cell.columnSpan, width))
          } else {
            if (columnWidths(jSpan) < width) columnWidths(jSpan) = width
          }

          j += 1
          jSpan += cell.columnSpan
          k += 1
        }
      }
    }

    if (body.rows.size() > 0) {
      val rowIter = body.rows.iterator()
      while (rowIter.hasNext) {
        val row   = rowIter.next()
        var jSpan = 0
        val kMax  = row.cells.size()
        var k     = 0
        while (k < kMax) {
          val cell = row.cells.get(k)
          delta.value = 0
          val cellText = this.cellText(row.cells, k, false, false, 0, null, delta)
          val width    = options.charWidthProvider.getStringWidth(cellText) + options.spacePad + options.pipeWidth * cell.columnSpan
          if (cell.columnSpan > 1) {
            columnSpans.add(new MarkdownTable.ColumnSpan(jSpan, cell.columnSpan, width))
          } else {
            if (columnWidths(jSpan) < width) columnWidths(jSpan) = width
          }

          jSpan += cell.columnSpan
          k += 1
        }
      }
    }

    // add separator column widths to the calculation
    if (separator.rows.size() == 0 || body.rows.size() > 0 || header.rows.size() > 0) {
      var j = 0
      delta.value = 0
      for (alignment <- alignments) {
        val alignment1 = adjustCellAlignment(alignment)
        val colonCount = if (alignment1 == CellAlignment.LEFT || alignment1 == CellAlignment.RIGHT) 1 else if (alignment1 == CellAlignment.CENTER) 2 else 0
        val dashCount0 = 0
        val dashesOnly = Utils.minLimit(dashCount0, options.minSeparatorColumnWidth - colonCount, options.minSeparatorDashes)
        val dashCount  = if (dashCount0 < dashesOnly) dashesOnly else dashCount0
        val width      = dashCount * options.dashWidth + colonCount * options.colonWidth + options.pipeWidth
        if (columnWidths(j) < width) columnWidths(j) = width
        j += 1
      }
    } else {
      // keep as is
      var j = 0
      delta.value = 0
      val cellIter = separator.rows.get(0).cells.iterator()
      while (cellIter.hasNext) {
        val cell       = cellIter.next()
        val alignment  = adjustCellAlignment(cell.alignment)
        val colonCount = if (alignment == CellAlignment.LEFT || alignment == CellAlignment.RIGHT) 1 else if (alignment == CellAlignment.CENTER) 2 else 0
        val trim       = cell.text.trim(MarkdownTable.COLON_TRIM_CHARS)
        val dashCount0 = trim.length()
        val dashesOnly = Utils.minLimit(dashCount0, options.minSeparatorColumnWidth - colonCount, options.minSeparatorDashes)
        val dashCount  = if (dashCount0 < dashesOnly) dashesOnly else dashCount0
        val width      = dashCount * options.dashWidth + colonCount * options.colonWidth + options.pipeWidth
        if (columnWidths(j) < width) columnWidths(j) = width
        j += 1
      }
    }

    if (!columnSpans.isEmpty) {
      // now need to distribute extra width from spans to contained columns
      val unfixedColumns = new BitSet(sepColumns)
      var newColumnSpans = new ArrayList[MarkdownTable.ColumnSpan](columnSpans.size())

      val spanIter1 = columnSpans.iterator()
      while (spanIter1.hasNext) {
        val columnSpan = spanIter1.next()
        val sw         = spanWidth(columnSpan.startColumn, columnSpan.columnSpan)
        if (sw < columnSpan.width) {
          unfixedColumns.set(columnSpan.startColumn, columnSpan.startColumn + columnSpan.columnSpan)
          newColumnSpans.add(columnSpan)
        }
      }

      // we now distribute additional width equally between columns that are spanned to unfixed columns
      while (!newColumnSpans.isEmpty) {
        columnSpans = newColumnSpans
        val fixedColumns = new BitSet(sepColumns)
        newColumnSpans = new ArrayList[MarkdownTable.ColumnSpan]()

        // remove spans that already fit into fixed columns
        val spanIter2 = columnSpans.iterator()
        while (spanIter2.hasNext) {
          val columnSpan = spanIter2.next()
          val sw         = spanWidth(columnSpan.startColumn, columnSpan.columnSpan)
          val fw         = spanFixedWidth(unfixedColumns, columnSpan.startColumn, columnSpan.columnSpan)
          if (sw <= fw) {
            fixedColumns.set(columnSpan.startColumn, columnSpan.startColumn + columnSpan.columnSpan)
          } else {
            newColumnSpans.add(columnSpan)
          }
        }

        // reset fixed columns
        unfixedColumns.andNot(fixedColumns)
        columnSpans = newColumnSpans
        newColumnSpans = new ArrayList[MarkdownTable.ColumnSpan]()

        val spanIter3 = columnSpans.iterator()
        while (spanIter3.hasNext) {
          val columnSpan = spanIter3.next()
          val sw         = spanWidth(columnSpan.startColumn, columnSpan.columnSpan)
          val fw         = spanFixedWidth(unfixedColumns, columnSpan.startColumn, columnSpan.columnSpan)
          if (sw > fw) {
            val distributeWidth    = sw - fw
            val unfixedColumnCount = unfixedColumns.get(columnSpan.startColumn, columnSpan.startColumn + columnSpan.columnSpan).cardinality()
            val perSpanWidth       = distributeWidth / unfixedColumnCount
            var extraWidth         = distributeWidth - perSpanWidth * unfixedColumnCount

            var i = 0
            while (i < columnSpan.columnSpan) {
              if (unfixedColumns.get(columnSpan.startColumn + i)) {
                columnWidths(columnSpan.startColumn + i) += perSpanWidth
                if (extraWidth > 0) {
                  columnWidths(columnSpan.startColumn + i) += 1
                  extraWidth -= 1
                }
              }
              i += 1
            }
            newColumnSpans.add(columnSpan)
          }
        }
      }
    }
  }

  def fillMissingColumns(): Unit = fillMissingColumns(Nullable(null))

  def fillMissingColumns(minColumn: Nullable[Integer]): Unit = {
    val minColumns = getMinColumns
    val maxColumns = getMaxColumns
    if (minColumns < maxColumns) {
      val hIter = header.rows.iterator()
      while (hIter.hasNext) hIter.next().fillMissingColumns(minColumn, maxColumns)
      val bIter = body.rows.iterator()
      while (bIter.hasNext) bIter.next().fillMissingColumns(minColumn, maxColumns)
    }
  }

  private def setTrackedOffsetIndex(offset: Int, index: Int): Boolean = {
    val to = findTrackedOffset(offset)
    if (to.isDefined) {
      to.get.setIndex(index)
      true
    } else {
      false
    }
  }

  /** Transpose table
    */
  def transposed(columnHeaders: Int): MarkdownTable = {
    val tr = new MarkdownTable(tableChars, options)
    tr.trackedOffsets.addAll(trackedOffsets)

    val maxRows    = getAllRowsCount - 1 // don't count separator rows
    val maxCols    = getMaxColumns
    val tableCells = Array.ofDim[TableCell](maxRows, maxCols)

    // get a matrix of all cells
    forAllSectionsRows(
      0,
      Integer.MAX_VALUE,
      ALL_CONTENT_ROWS,
      new TableRowManipulator {
        override def apply(row: TableRow, allRowsIndex: Int, sectionRows: ArrayList[TableRow], sectionRowIndex: Int): Int = {
          val tableCellRow = tableCells(allRowsIndex)
          val iMax         = row.cells.size()
          var col          = 0
          var i            = 0
          while (i < iMax) {
            val cell = row.cells.get(i)
            var span = 0
            while (span < cell.columnSpan) {
              tableCellRow(col) = new TableCell(cell, span == 0, 1, 1, null)
              col += 1
              span += 1
            }
            i += 1
          }
          0
        }
      }
    )

    tr.setHeader()
    val colHdrs = Math.min(Math.max(0, columnHeaders), maxCols)
    var c       = 0
    while (c < colHdrs) {
      var r = 0
      while (r < maxRows) {
        val cell = tableCells(r)(c)
        tr.addCell(if (cell == null) TableCell.DEFAULT_CELL else cell)
        r += 1
      }
      tr.nextRow()
      c += 1
    }

    val sepRow = separator.rows.get(0)
    tr.setSeparator()
    val iMax = sepRow.cells.size()
    var i    = 0
    while (i < maxRows) {
      if (i < iMax) {
        tr.addCell(new TableCell(sepRow.cells.get(i), true, 1, 1, null))
      } else {
        tr.addCell(new TableCell("---", 1, 1))
      }
      i += 1
    }

    tr.setBody()
    c = colHdrs
    while (c < maxCols) {
      var r = 0
      while (r < maxRows) {
        val cell = tableCells(r)(c)
        tr.addCell(if (cell == null) TableCell.DEFAULT_CELL else cell)
        r += 1
      }
      tr.nextRow()
      c += 1
    }

    tr.setCaptionCell(getCaptionCell)
    tr
  }

  /** Sort table
    */
  def sorted(columnSorts: Array[ColumnSort], textCollectionFlags: Int, numericSuffixTester: Nullable[NumericSuffixPredicate]): MarkdownTable = {
    val sortedTable = new MarkdownTable(tableChars, options)
    sortedTable.trackedOffsets.addAll(trackedOffsets)

    sortedTable.setHeader()
    forAllSectionsRows(
      0,
      Integer.MAX_VALUE,
      ALL_HEADER_ROWS,
      new TableRowManipulator {
        override def apply(row: TableRow, allRowsIndex: Int, sectionRows: ArrayList[TableRow], sectionRowIndex: Int): Int = {
          val iMax = row.cells.size()
          var i    = 0
          while (i < iMax) {
            val cell = row.cells.get(i)
            sortedTable.addCell(if (cell eq TableCell.DEFAULT_CELL) cell else new TableCell(cell, true, cell.rowSpan, cell.columnSpan, cell.alignment))
            i += 1
          }
          sortedTable.nextRow()
          0
        }
      }
    )

    sortedTable.setSeparator()
    val sepRow         = separator.rows.get(0)
    val sepIMax        = sepRow.cells.size()
    val sortAlignments = new Array[CellAlignment](sepIMax)

    var si = 0
    while (si < sepIMax) {
      val cell = sepRow.cells.get(si)
      sortedTable.addCell(if (cell eq TableCell.DEFAULT_CELL) cell else new TableCell(cell, true, cell.rowSpan, cell.columnSpan, cell.alignment))
      sortAlignments(si) = cell.alignment
      si += 1
    }

    val rows      = getAllSectionsRows(body)
    val cellSizes = new Array[Int](sepIMax)

    val rMax = rows.size()
    val cMax = getMaxBodyColumns

    var r = 0
    while (r < rMax) {
      for (columnSort <- columnSorts) {
        val c = columnSort.column
        if (c >= 0 && c < cMax) {
          val spanIndex = rows.get(r).indexOf(c)
          val cell      = rows.get(r).cells.get(spanIndex.index)
          if (spanIndex.index == c && cell != null) {
            // not in span
            cellSizes(c) = Math.max(cellSizes(c), cell.text.length())
          }
        }
      }
      r += 1
    }

    val visitor = new TextCollectingVisitor()
    val numericSuffixPredicate: NumericSuffixPredicate = if (numericSuffixTester.isEmpty) MarkdownTable.ALL_SUFFIXES_SORT else numericSuffixTester.get

    val rowComparator: Comparator[TableRow] = (o1: TableRow, o2: TableRow) => {
      var result = 0
      boundary {
        for (columnSort <- columnSorts) {
          val c = columnSort.column
          if (c >= 0 && c < cMax) {
            val cellSize = cellSizes(c)
            if (cellSize > 0) {
              val sort        = columnSort.sort
              var descending  = sort.isDescending
              val numeric     = sort.isNumeric
              val numericLast = sort.isNumericLast

              val spanIndex1 = o1.indexOf(c)
              val cell1      = o1.cells.get(spanIndex1.index)
              val spanIndex2 = o2.indexOf(c)
              val cell2      = o2.cells.get(spanIndex2.index)

              if (spanIndex1.index == c && cell1 != null && spanIndex2.index == c && cell2 != null) {
                var padLeft1  = 0; var padLeft2 = 0; var padRight1 = 0; var padRight2 = 0
                val cellText1 = if (cell1.tableCellNode.isEmpty) cell1.text.toString else visitor.collectAndGetText(cell1.tableCellNode.get, textCollectionFlags).trim
                val cellText2 = if (cell2.tableCellNode.isEmpty) cell2.text.toString else visitor.collectAndGetText(cell2.tableCellNode.get, textCollectionFlags).trim
                val diff1     = cellSize - cellText1.length
                val diff2     = cellSize - cellText2.length

                sortAlignments(c) match {
                  case CellAlignment.CENTER =>
                    padLeft1 = diff1 >> 1; padRight1 = cellSize - padLeft1
                    padLeft2 = diff2 >> 1; padRight2 = cellSize - padLeft2
                  case CellAlignment.RIGHT =>
                    padLeft1 = diff1; padLeft2 = diff2
                  case _ =>
                }

                if (numeric) {
                  val cellNumeric1 = SequenceUtils.parseNumberPrefixOrNull(Nullable(cellText1), Nullable(numericSuffixPredicate))
                  val cellNumeric2 = SequenceUtils.parseNumberPrefixOrNull(Nullable(cellText2), Nullable(numericSuffixPredicate))

                  if (cellNumeric1.isDefined && cellNumeric2.isDefined) {
                    result = Utils.compare(cellNumeric1.get.first, cellNumeric2.get.first)
                    val numericSuffix1 = cellNumeric1.get.second.get
                    val numericSuffix2 = cellNumeric2.get.second.get

                    if (result == 0 && (numericSuffixPredicate.sortSuffix(numericSuffix1) || numericSuffixPredicate.sortSuffix(numericSuffix2))) {
                      if (numericSuffix1.nonEmpty && numericSuffixPredicate.sortSuffix(numericSuffix1) && numericSuffix2.nonEmpty && numericSuffixPredicate.sortSuffix(numericSuffix2)) {
                        result = numericSuffix1.compareTo(numericSuffix2)
                      } else if (numericSuffix1.nonEmpty && numericSuffixPredicate.sortSuffix(numericSuffix1)) {
                        result = if (numericLast) -1 else 1
                        descending = false
                      } else if (numericSuffix2.nonEmpty && numericSuffixPredicate.sortSuffix(numericSuffix2)) {
                        result = if (numericLast) 1 else -1
                        descending = false
                      }
                    }
                  } else if (cellNumeric1.isDefined) {
                    result = if (numericLast) 1 else -1; descending = false
                  } else if (cellNumeric2.isDefined) {
                    result = if (numericLast) -1 else 1; descending = false
                  } else {
                    val cell1Text = RepeatedSequence.ofSpaces(padLeft1).toString + cellText1 + RepeatedSequence.ofSpaces(padRight1)
                    val cell2Text = RepeatedSequence.ofSpaces(padLeft2).toString + cellText2 + RepeatedSequence.ofSpaces(padRight2)
                    result = cell1Text.compareTo(cell2Text)
                  }
                } else {
                  val cell1Text = RepeatedSequence.ofSpaces(padLeft1).toString + cellText1 + RepeatedSequence.ofSpaces(padRight1)
                  val cell2Text = RepeatedSequence.ofSpaces(padLeft2).toString + cellText2 + RepeatedSequence.ofSpaces(padRight2)
                  result = cell1Text.compareTo(cell2Text)
                }
              } else if (spanIndex1.index == c && cell1 != null) {
                result = 1
              } else if (spanIndex2.index == c && cell2 != null) {
                result = -1
              } else {
                result = 0
              }

              if (result != 0) break(if (descending) -result else result)
            }
          }
        }
        0
      }
    }

    rows.sort(rowComparator)

    sortedTable.setBody()
    var ri = 0
    while (ri < rows.size()) {
      val row   = rows.get(ri)
      val riMax = row.cells.size()
      var ii    = 0
      while (ii < riMax) {
        val cell = row.cells.get(ii)
        sortedTable.addCell(if (cell eq TableCell.DEFAULT_CELL) cell else new TableCell(cell, true, cell.rowSpan, cell.columnSpan, cell.alignment))
        ii += 1
      }
      sortedTable.nextRow()
      ri += 1
    }

    sortedTable.setCaptionCell(getCaptionCell)
    sortedTable
  }

  private[format] def appendDashes(out: LineAppendable, dashCount: Int, sepDashes: BasedSequence, dashOffset: Int): Int = {
    val sepDashesLength = sepDashes.length()
    var remainingDashes = Math.max(0, sepDashesLength - dashOffset)

    if (remainingDashes >= dashCount) {
      out.append(sepDashes.subSequence(dashOffset, dashOffset + dashCount))
      remainingDashes -= dashCount
    } else {
      var usedUpDashes = 0
      if (remainingDashes > 1) {
        out.append(sepDashes.subSequence(dashOffset, dashOffset + 1))
        remainingDashes -= 1
        usedUpDashes += 1
      }
      out.append('-', dashCount - Math.max(0, remainingDashes + usedUpDashes))
      if (remainingDashes > 0) {
        out.append(sepDashes.subSequence(dashOffset, dashOffset + remainingDashes))
        remainingDashes = 0
      }
    }
    sepDashesLength - remainingDashes
  }

  def appendTable(out: LineAppendable): Unit = {
    // we will prepare the separator based on max columns
    val linePrefix = formatTableIndentPrefix

    trackedOffsets.sort(Comparator.comparing[TrackedOffset, Integer]((t: TrackedOffset) => t.offset))

    out.pushOptions()
    out.removeOptions(LineAppendable.F_WHITESPACE_REMOVAL)

    finalizeTable()

    appendRows(out, header.rows, true, linePrefix)

    {
      out.append(linePrefix)
      val row = if (separator.rows.size() > 0) separator.rows.get(0) else null

      if (row != null && row.beforeOffset != TableCell.NOT_TRACKED) {
        setTrackedOffsetIndex(row.beforeOffset, out.offsetWithPending())
      }

      var j     = 0
      val delta = new Ref[Integer](0)
      for (alignment <- alignments) {
        val alignment1 = adjustCellAlignment(alignment)

        val colonCount = if (alignment1 == CellAlignment.LEFT || alignment1 == CellAlignment.RIGHT) 1 else if (alignment1 == CellAlignment.CENTER) 2 else 0
        val diff       = columnWidths(j) - colonCount * options.colonWidth - options.pipeWidth
        var dashCount  = (delta.value + diff) / options.dashWidth
        val dashesOnly = Utils.minLimit(dashCount, options.minSeparatorColumnWidth - colonCount, options.minSeparatorDashes)
        if (dashCount < dashesOnly) dashCount = dashesOnly

        if (Math.abs(delta.value + diff - (dashCount + 1) * options.dashWidth) < Math.abs(delta.value + diff - dashCount * options.dashWidth)) {
          dashCount += 1
        }

        delta.value = delta.value + diff - dashCount * options.dashWidth

        var trackedPos = 0
        var cell:         TableCell = null
        var previousCell: TableCell = null

        if (row != null) {
          val cells = row.cells
          if (j < cells.size()) {
            cell = cells.get(j)
            if (j > 0) previousCell = cells.get(j - 1)
          }
        }

        trackedPos = if (cell == null) TableCell.NOT_TRACKED else minLimit(cell.trackedTextOffset, 0)
        val sepText       = if (cell == null) BasedSequence.NULL else cell.text.trim(MarkdownTable.COLON_TRIM_CHARS)
        var sepDashOffset = 0

        if (trackedPos != TableCell.NOT_TRACKED) {
          if (options.leadTrailPipes && j == 0) out.append('|')
          val beforeFirstColon = trackedPos == 0 && cell.text.charAt(trackedPos) == ':'
          val afterFirstColon  = trackedPos == 1 && cell.text.charAt(trackedPos - 1) == ':'
          val beforeLastColon  = trackedPos == cell.text.length() - 1 && cell.text.charAt(trackedPos) == ':'
          val afterLastColon   = trackedPos == cell.text.length() && cell.text.charAt(trackedPos - 1) == ':'
          val afterLastDash    = trackedPos == cell.text.length() && cell.text.charAt(trackedPos - 1) == '-'

          if (alignment1 == CellAlignment.LEFT || alignment1 == CellAlignment.CENTER) {
            if (beforeFirstColon) {
              setTrackedOffsetIndex(cell.trackedTextOffset + cell.getInsideStartOffset(Nullable(previousCell)), out.offsetWithPending())
              trackedPos = TableCell.NOT_TRACKED
              out.append(':')
            } else if (afterFirstColon) {
              out.append(':')
              setTrackedOffsetIndex(cell.trackedTextOffset + cell.getInsideStartOffset(Nullable(previousCell)), out.offsetWithPending())
              trackedPos = TableCell.NOT_TRACKED
            } else {
              out.append(':')
            }
          } else {
            // no left colon
          }

          if (!afterFirstColon && !beforeFirstColon && !afterLastColon && !beforeLastColon) {
            if (trackedPos == 0) {
              setTrackedOffsetIndex(cell.trackedTextOffset + cell.getInsideStartOffset(Nullable(previousCell)), out.offsetWithPending())
              trackedPos = TableCell.NOT_TRACKED
              sepDashOffset = appendDashes(out, dashCount, sepText, sepDashOffset)
            } else if (!afterLastDash && trackedPos < dashCount) {
              sepDashOffset = appendDashes(out, trackedPos, sepText, sepDashOffset)
              setTrackedOffsetIndex(cell.trackedTextOffset + cell.getInsideStartOffset(Nullable(previousCell)), out.offsetWithPending())
              sepDashOffset = appendDashes(out, dashCount - trackedPos, sepText, sepDashOffset)
              trackedPos = TableCell.NOT_TRACKED
            } else {
              sepDashOffset = appendDashes(out, dashCount, sepText, sepDashOffset)
              setTrackedOffsetIndex(cell.trackedTextOffset + cell.getInsideStartOffset(Nullable(previousCell)), out.offsetWithPending())
              trackedPos = TableCell.NOT_TRACKED
            }
          } else {
            sepDashOffset = appendDashes(out, dashCount, sepText, sepDashOffset)
          }

          if (alignment1 == CellAlignment.RIGHT || alignment1 == CellAlignment.CENTER) {
            if (afterLastColon) {
              out.append(':')
              setTrackedOffsetIndex(cell.trackedTextOffset + cell.getInsideStartOffset(Nullable(previousCell)), out.offsetWithPending())
              trackedPos = TableCell.NOT_TRACKED
            } else if (beforeLastColon) {
              setTrackedOffsetIndex(cell.trackedTextOffset + cell.getInsideStartOffset(Nullable(previousCell)), out.offsetWithPending())
              trackedPos = TableCell.NOT_TRACKED
              out.append(':')
            } else {
              out.append(':')
            }
          } else if (afterLastColon || beforeLastColon) {
            setTrackedOffsetIndex(cell.trackedTextOffset + cell.getInsideStartOffset(Nullable(previousCell)), out.offsetWithPending())
            trackedPos = TableCell.NOT_TRACKED
          }

          assert(trackedPos == TableCell.NOT_TRACKED)
        } else {
          if (options.leadTrailPipes && j == 0) out.append('|')
          if (alignment1 == CellAlignment.LEFT || alignment1 == CellAlignment.CENTER) { out.append(':') }
          sepDashOffset = appendDashes(out, dashCount, sepText, sepDashOffset)
          if (alignment1 == CellAlignment.RIGHT || alignment1 == CellAlignment.CENTER) { out.append(':') }
        }

        j += 1
        if (options.leadTrailPipes || j < alignments.length) out.append('|')
      }

      if (row != null && row.afterOffset != TableCell.NOT_TRACKED) {
        setTrackedOffsetIndex(row.afterOffset, out.offsetWithPending())
      }

      out.line()
    }

    appendRows(out, body.rows, false, linePrefix)

    val captionCell = getCaptionCell
    val captionText = MarkdownTable.formattedCaption(captionCell.text, options)
    if (captionText.isDefined) {
      val formattedCaption = BasedSequence.of(captionText.get).subSequence(0, captionText.get.length)
      var handled          = false

      if (this.caption.rows.size() > 0) {
        val row = this.caption.rows.get(0)
        if (captionCell.trackedTextOffset != TableCell.NOT_TRACKED || row.beforeOffset != TableCell.NOT_TRACKED || row.afterOffset != TableCell.NOT_TRACKED) {
          val cell = captionCell

          out.line()

          if (row.beforeOffset != TableCell.NOT_TRACKED) {
            setTrackedOffsetIndex(row.beforeOffset, out.offsetWithPending())
          }

          var adjCaptionCell = captionCell.withText(captionCell.text.trim())
          if (cell.trackedTextOffset != TableCell.NOT_TRACKED) {
            adjCaptionCell = adjCaptionCell.withTrackedOffset(minLimit(cell.trackedTextOffset - cell.text.trimmedStart().length(), 0))
          }

          var addOpenCaptionSpace  = false
          var addCloseCaptionSpace = false

          if (!adjCaptionCell.text.isBlank()) {
            options.formatTableCaptionSpaces match {
              case DiscretionaryText.ADD =>
                addOpenCaptionSpace = true
                addCloseCaptionSpace = true
              case DiscretionaryText.REMOVE =>
              // nothing
              case _ => // AS_IS
                addOpenCaptionSpace = cell.text.startsWith(" ")
                addCloseCaptionSpace = cell.text.endsWith(" ")
            }
          }

          out.append(linePrefix)
          out.append('[')
          if (addOpenCaptionSpace) out.append(' ')

          val cellOffset = out.offsetWithPending()

          row.cells.set(0, adjCaptionCell)
          val delta    = new Ref[Integer](0)
          val cellText = this.cellText(row.cells, 0, true, false, 0, CellAlignment.LEFT, delta)

          if (row.cells.size() > 0) {
            if (cell.trackedTextOffset != TableCell.NOT_TRACKED) {
              val adjustedCell = row.cells.get(0)
              if (adjustedCell.trackedTextOffset != TableCell.NOT_TRACKED) {
                setTrackedOffsetIndex(
                  cell.trackedTextOffset + cell.text.startOffset,
                  cellOffset + (if (cellText.isBlank()) 1 else minLimit(adjustedCell.trackedTextOffset, 0) + adjustedCell.trackedTextAdjust)
                )
              }
            }
            row.cells.set(0, cell)
          } else {
            row.cells.add(cell)
          }

          out.append(cellText)
          if (addCloseCaptionSpace) out.append(' ')
          out.append(']')

          if (row.afterOffset != TableCell.NOT_TRACKED) {
            setTrackedOffsetIndex(row.afterOffset, out.offsetWithPending())
          }
          out.line()
          handled = true
        }
      }

      if (!handled) {
        out.popOptions().pushOptions()
        out.line().append(linePrefix).append('[').append(formattedCaption).append(']').line()
      }
    }
    out.popOptions()
  }

  private def pipeNeedsSpaceBefore(cell: TableCell): Boolean =
    cell.text.equals(" ") || !cell.text.endsWith(" ")

  private def pipeNeedsSpaceAfter(cell: TableCell): Boolean =
    cell.text.equals(" ") || !cell.text.startsWith(" ")

  private def appendRows(
    out:        LineAppendable,
    rows:       JList[TableRow],
    isHeader:   Boolean,
    linePrefix: CharSequence
  ): Unit = {
    val rowIter = rows.iterator()
    while (rowIter.hasNext) {
      val row   = rowIter.next()
      var j     = 0
      var jSpan = 0
      val delta = new Ref[Integer](0)

      out.append(linePrefix)

      if (row.beforeOffset != TableCell.NOT_TRACKED) {
        setTrackedOffsetIndex(row.beforeOffset, out.offsetWithPending())
      }

      val iMax = row.cells.size()
      var i    = 0
      while (i < iMax) {
        val cell = row.cells.get(i)

        if (j == 0) {
          if (options.leadTrailPipes) {
            out.append('|')
            if (options.spaceAroundPipes && pipeNeedsSpaceAfter(cell)) { out.append(' ') }
          }
        } else {
          if (options.spaceAroundPipes && pipeNeedsSpaceAfter(cell)) out.append(' ')
        }

        val cellAlignment = if (isHeader && cell.alignment != CellAlignment.NONE) cell.alignment else alignments(jSpan)

        val cellText = this.cellText(
          row.cells,
          i,
          true,
          isHeader,
          spanWidth(jSpan, cell.columnSpan) - options.spacePad - options.pipeWidth * cell.columnSpan,
          cellAlignment,
          delta
        )

        if (cell.trackedTextOffset != TableCell.NOT_TRACKED) {
          val adjustedCell = row.cells.get(i)
          if (adjustedCell.trackedTextOffset != TableCell.NOT_TRACKED) {
            val cellOffset     = out.offsetWithPending()
            val adjustForBlank = if (cell.text.isBlank()) -1 else 0
            if (
              !setTrackedOffsetIndex(
                cell.trackedTextOffset + cell.getTextStartOffset(if (i == 0) Nullable(null) else Nullable(row.cells.get(i - 1))),
                cellOffset + minLimit(adjustedCell.trackedTextOffset + adjustForBlank, 0) + adjustedCell.trackedTextAdjust
              )
            ) {
              // QUERY: Triggered after sort table in MdNav for header row
              System.out.println(
                String.format(
                  "Offset not found: cell.trackedTextOffset: %d, adjusted trackedOffset: %d in offsets: %s",
                  cell.trackedTextOffset.asInstanceOf[AnyRef],
                  (cell.trackedTextOffset + cell.getTextStartOffset(if (i == 0) Nullable(null) else Nullable(row.cells.get(i - 1)))).asInstanceOf[AnyRef],
                  trackedOffsets
                )
              )
            }
          }
        }

        out.append(cellText)

        j += 1
        jSpan += cell.columnSpan

        if (j < alignments.length) {
          if (options.spaceAroundPipes && pipeNeedsSpaceBefore(cell)) out.append(' ')
          appendColumnSpan(out, cell.columnSpan, cell.getInsideEndOffset, cell.spanTrackedOffset)
        } else if (options.leadTrailPipes) {
          if (options.spaceAroundPipes && pipeNeedsSpaceBefore(cell)) out.append(' ')
          appendColumnSpan(out, cell.columnSpan, cell.getInsideEndOffset, cell.spanTrackedOffset)
        } else {
          if (options.spaceAroundPipes && pipeNeedsSpaceBefore(cell)) out.append(' ')
          appendColumnSpan(out, cell.columnSpan - 1, cell.getInsideEndOffset, cell.spanTrackedOffset)
        }

        i += 1
      }

      if (row.afterOffset != TableCell.NOT_TRACKED) {
        setTrackedOffsetIndex(row.afterOffset, out.offsetWithPending())
      }

      if (j > 0) out.line()
    }
  }

  private def appendColumnSpan(out: LineAppendable, span: Int, cellInsideEndOffset: Int, trackedSpanOffset: Int): Unit =
    if (trackedSpanOffset == TableCell.NOT_TRACKED) {
      out.append('|', span)
    } else {
      if (trackedSpanOffset == 0) {
        setTrackedOffsetIndex(cellInsideEndOffset + trackedSpanOffset, out.offsetWithPending())
        out.append('|', span)
      } else if (trackedSpanOffset < span) {
        out.append('|', trackedSpanOffset)
        setTrackedOffsetIndex(cellInsideEndOffset + trackedSpanOffset, out.offsetWithPending())
        out.append('|', span - trackedSpanOffset)
      } else {
        out.append('|', span)
        setTrackedOffsetIndex(cellInsideEndOffset + trackedSpanOffset, out.offsetWithPending())
      }
    }

  private def cellText(
    cells:             JList[TableCell],
    index:             Int,
    withTrackedOffset: Boolean,
    isHeader:          Boolean,
    width:             Int,
    alignment:         CellAlignment,
    delta:             Ref[Integer]
  ): BasedSequence = {
    val cell         = cells.get(index)
    var adjustedCell = cell
    var text         = cell.text
    val needsPadding = cell.trackedTextOffset != TableCell.NOT_TRACKED && cell.trackedTextOffset >= cell.text.length()
    var neededPrefix = false

    if (cell.trackedTextOffset != TableCell.NOT_TRACKED) {
      if (cell.trackedTextOffset > cell.text.length()) {
        val suffixed = cell.trackedTextOffset - cell.text.length() - 1
        text = text.append(RepeatedSequence.repeatOf(' ', suffixed))
      } else if (cell.trackedTextOffset < 0) {
        neededPrefix = true
      }
    }

    val length       = options.charWidthProvider.getStringWidth(text)
    var useAlignment = alignment
    if (options.adjustColumnWidth && (length < width || cell.trackedTextOffset > cell.text.length())) {
      if (!options.applyColumnAlignment || useAlignment == null || useAlignment == CellAlignment.NONE) {
        useAlignment = if (isHeader && options.leftAlignMarker != DiscretionaryText.ADD) CellAlignment.CENTER else CellAlignment.LEFT
      } else if (isHeader && useAlignment == CellAlignment.LEFT && options.leftAlignMarker == DiscretionaryText.REMOVE) {
        useAlignment = CellAlignment.CENTER
      }

      val diff       = width - length
      var spaceCount = (delta.value + diff) / options.spaceWidth
      // NOTE: add extra space if accumulated adding extra space gives smaller abs error
      if (width > 0 && Math.abs(delta.value + diff - (spaceCount + 1) * options.spaceWidth) < Math.abs(delta.value + diff - spaceCount * options.spaceWidth)) {
        spaceCount += 1
      }

      delta.value = delta.value + diff - spaceCount * options.spaceWidth

      useAlignment match {
        case CellAlignment.LEFT =>
          if (spaceCount > 0) {
            text = text.append(PrefixedSubSequence.repeatOf(" ", spaceCount, text.getEmptySuffix))
          }
          if (withTrackedOffset && needsPadding && cell.afterSpace) {
            if (spaceCount <= 0) { adjustedCell = adjustedCell.withTrackedTextAdjust(1) }
          }

        case CellAlignment.RIGHT =>
          if (spaceCount > 0) {
            text = PrefixedSubSequence.repeatOf(" ", spaceCount, text)
            if (withTrackedOffset && cell.trackedTextOffset != TableCell.NOT_TRACKED) {
              adjustedCell = cell.withTrackedOffset(maxLimit(text.length(), cell.trackedTextOffset + spaceCount))
            }
            if (withTrackedOffset && neededPrefix && cell.afterSpace) {
              adjustedCell = adjustedCell.withTrackedTextAdjust(1)
            }
          }
          if (withTrackedOffset && needsPadding && cell.afterSpace) {
            if (spaceCount <= 0 || !cell.afterDelete) { adjustedCell = adjustedCell.withTrackedTextAdjust(1) }
          }

        case CellAlignment.CENTER =>
          val count = spaceCount / 2
          if (spaceCount > 0) {
            text = PrefixedSubSequence.repeatOf(" ", count, text).append(PrefixedSubSequence.repeatOf(" ", spaceCount - count, text.getEmptySuffix))
            if (withTrackedOffset && cell.trackedTextOffset != TableCell.NOT_TRACKED) {
              adjustedCell = cell.withTrackedOffset(maxLimit(text.length(), cell.trackedTextOffset + count))
            }
            if (withTrackedOffset && neededPrefix && cell.afterSpace) {
              adjustedCell = adjustedCell.withTrackedTextAdjust(1)
            }
          } else {
            if (withTrackedOffset && needsPadding && cell.afterSpace) {
              adjustedCell = adjustedCell.withTrackedTextAdjust(1)
            }
          }

        case _ =>
      }
    }

    if (withTrackedOffset && adjustedCell.trackedTextOffset != TableCell.NOT_TRACKED) {
      // replace with adjusted offset
      if (adjustedCell.trackedTextOffset > text.length()) {
        adjustedCell = adjustedCell.withTrackedOffset(text.length())
      }
      if (adjustedCell ne cell) cells.set(index, adjustedCell)
    }

    text
  }

  private def spanWidth(col: Int, columnSpan: Int): Int =
    if (columnSpan > 1) {
      var width = 0
      var i     = 0
      while (i < columnSpan) { width += columnWidths(i + col); i += 1 }
      width
    } else {
      columnWidths(col)
    }

  private def spanFixedWidth(unfixedColumns: BitSet, col: Int, columnSpan: Int): Int =
    if (columnSpan > 1) {
      var width = 0
      var i     = 0
      while (i < columnSpan) {
        if (!unfixedColumns.get(i)) { width += columnWidths(i + col) }
        i += 1
      }
      width
    } else {
      if (unfixedColumns.get(col)) 0 else columnWidths(col)
    }

  private def adjustCellAlignment(alignment: CellAlignment): CellAlignment = {
    var result = alignment
    options.leftAlignMarker match {
      case DiscretionaryText.ADD =>
        if (result == null || result == CellAlignment.NONE) { result = CellAlignment.LEFT }
      case DiscretionaryText.REMOVE =>
        if (result == CellAlignment.LEFT) result = CellAlignment.NONE
      case _ =>
    }
    result
  }

  private def aggregateTotalColumnsWithoutColumns(
    sections:    Array[TableSection],
    aggregator:  BiFunction[Nullable[Integer], Nullable[Integer], Nullable[Integer]],
    skipColumns: Array[Int]
  ): Int = {
    val columns = Array[Nullable[Integer]](Nullable(null))

    forAllSectionsRows(
      0,
      Integer.MAX_VALUE,
      sections,
      new TableRowManipulator {
        override def apply(row: TableRow, allRowsIndex: Int, sectionRows: ArrayList[TableRow], sectionRowIndex: Int): Int = {
          val iMax  = row.cells.size()
          var count = 0
          var i     = 0
          while (i < iMax) {
            if (!skipColumns.contains(i)) count += row.cells.get(i).columnSpan
            i += 1
          }
          if (count != 0) {
            columns(0) = aggregator.apply(columns(0), Nullable(Integer.valueOf(count)))
          }
          0
        }
      }
    )

    if (columns(0).isEmpty) 0 else columns(0).get.intValue()
  }

  private def aggregateTotalColumnsWithoutRows(
    sections:   Array[TableSection],
    aggregator: BiFunction[Nullable[Integer], Nullable[Integer], Nullable[Integer]],
    skipRows:   Array[Int]
  ): Int = {
    val columns = Array[Nullable[Integer]](Nullable(null))

    forAllSectionsRows(
      0,
      Integer.MAX_VALUE,
      sections,
      new TableRowManipulator {
        override def apply(row: TableRow, allRowsIndex: Int, sectionRows: ArrayList[TableRow], sectionRowIndex: Int): Int = {
          if (!skipRows.contains(allRowsIndex)) {
            val totalColumns = row.getTotalColumns
            if (totalColumns > 0) { columns(0) = aggregator.apply(columns(0), Nullable(Integer.valueOf(totalColumns))) }
          }
          0
        }
      }
    )

    if (columns(0).isEmpty) 0 else columns(0).get.intValue()
  }

  private def forAllSectionsRows(
    startIndex:  Int,
    count:       Int,
    sections:    Array[TableSection],
    manipulator: TableRowManipulator
  ): Unit =
    if (count <= 0) {
      () // trivial guard clause: nothing to do
    } else {
      var remaining    = count
      var sectionIndex = startIndex
      var allRowsIndex = startIndex

      boundary {
        for (section <- sections) {
          var currentIndex = 0

          if (sectionIndex >= section.rows.size()) {
            sectionIndex -= section.rows.size()
          } else {
            currentIndex = sectionIndex
            sectionIndex = 0

            while (currentIndex < section.rows.size()) {
              val result = manipulator.apply(section.rows.get(currentIndex), allRowsIndex, section.rows, currentIndex)
              if (result == TableRowManipulator.BREAK) break()
              if (result < 0) {
                allRowsIndex -= result // adjust for deleted rows
                remaining += result
              } else {
                currentIndex += result + 1
                remaining -= 1
              }
              if (remaining <= 0) break()
              allRowsIndex += 1
            }
          }
        }
      }
    } // end else

  override def toString: String =
    // NOTE: show not simple name but name of container class if any
    this.getClass.getName.substring(getClass.getPackage.getName.length + 1) + "{" +
      "header=" + header +
      ",\nseparator=" + separator +
      ",\nbody=" + body +
      ",\ncaption=" + caption +
      ",\noptions=" + options +
      ",\ntrackedOffsets=" + trackedOffsets +
      "}"
}

object MarkdownTable {

  val COLON_TRIM_CHARS: CharPredicate = CharPredicate.anyOf(':')

  val NO_SUFFIXES: NumericSuffixPredicate = new NumericSuffixPredicate {
    override def apply(s: String): Boolean = false
  }

  val ALL_SUFFIXES_SORT: NumericSuffixPredicate = new NumericSuffixPredicate {
    override def apply(s: String): Boolean = true
  }

  val ALL_SUFFIXES_NO_SORT: NumericSuffixPredicate = new NumericSuffixPredicate {
    override def apply(s:           String): Boolean = true
    override def sortSuffix(suffix: String): Boolean = false
  }

  def appendFormattedCaption(
    out:     LineAppendable,
    caption: BasedSequence,
    options: TableFormatOptions
  ): Unit = {
    val formattedCaption = MarkdownTable.formattedCaption(caption, options)
    if (formattedCaption.isDefined) {
      out.line().append('[').append(formattedCaption.get).append(']').line()
    }
  }

  def formattedCaption(
    caption: BasedSequence,
    options: TableFormatOptions
  ): Nullable[String] = {
    var append = caption.isNotNull

    options.formatTableCaption match {
      case options.formatTableCaption if options.formatTableCaption == ssg.md.util.format.options.TableCaptionHandling.ADD =>
        append = true
      case options.formatTableCaption if options.formatTableCaption == ssg.md.util.format.options.TableCaptionHandling.REMOVE_EMPTY =>
        append = !caption.isBlank()
      case options.formatTableCaption if options.formatTableCaption == ssg.md.util.format.options.TableCaptionHandling.REMOVE =>
        append = false
      case _ => // AS_IS
    }

    if (append) {
      val captionSpaces = options.formatTableCaptionSpaces match {
        case DiscretionaryText.ADD    => " "
        case DiscretionaryText.REMOVE => ""
        case _                        => ""
      }
      Nullable(captionSpaces + caption.toString + captionSpaces)
    } else {
      Nullable(null)
    }
  }

  class IndexSpanOffset(val index: Int, val spanOffset: Int) {

    override def toString: String =
      "IndexSpanOffset{" +
        "index=" + index +
        ", spanOffset=" + spanOffset +
        '}'
  }

  private class ColumnSpan(val startColumn: Int, val columnSpan: Int, val width: Int) {
    var additionalWidth: Int = 0
  }
}
