/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Environment definition and registration infrastructure for KaTeX.
 *
 * Similar to FunctionDef but for LaTeX environments (e.g. \begin{array}).
 *
 * Original source: katex src/defineEnvironment.ts
 * Original author: Khan Academy and contributors
 * Original license: MIT
 *
 * upstream-commit: 90de9794
 *
 * Migration notes:
 *   Renames: defineEnvironment -> EnvironmentDef.defineEnvironment
 *   Convention: global mutable Record -> mutable.Map
 *   Idiom: TypeScript generics erased, use String node type
 */
package ssg
package katex
package environments

import scala.collection.mutable

import ssg.commons.Nullable
import ssg.katex.parse.AnyParseNode
import ssg.katex.functions.{FunctionDef, HtmlBuilder, MathMLBuilder}

/**
 * The context contains the following properties:
 *  - mode: current parsing mode.
 *  - envName: the name of the environment, one of the listed names.
 *  - parser: the parser object.
 */
final case class EnvContext(
    mode: Mode,
    envName: String,
    parser: AnyRef // Parser — not yet ported
)

/**
 *  - context: information and references provided by the parser
 *  - args: an array of arguments passed to \begin{name}
 *  - optArgs: an array of optional arguments passed to \begin{name}
 */
type EnvHandler =
  (EnvContext, Array[AnyParseNode], Array[Nullable[AnyParseNode]]) => AnyParseNode

/**
 *  - numArgs: (default 0) The number of arguments after the \begin{name} function.
 *  - argTypes: (optional) Just like for a function
 *  - allowedInText: (default false) Whether or not the environment is allowed
 *                   inside text mode (not enforced yet).
 *  - numOptionalArgs: (default 0) Just like for a function
 */
final case class EnvProps(
    numArgs: Int = 0
)

/**
 * Final environment spec for use at parse time.
 * This is almost identical to `EnvDefSpec`, except it
 * 1. includes the function handler
 * 2. requires all arguments except argType
 * It is generated by `defineEnvironment()` below.
 */
final case class EnvSpec(
    nodeType: String,
    // Need to use the type to avoid error. See NOTES below.
    numArgs: Int,
    argTypes: Nullable[Array[ArgType]] = Nullable.Null,
    allowedInText: Boolean = false,
    numOptionalArgs: Int = 0,
    handler: EnvHandler
)

/**
 * Specification for defining an environment (before it is registered).
 */
final case class EnvDefSpec(
    // Unique string to differentiate parse nodes.
    nodeType: String,

    // List of functions which use the give handler, htmlBuilder,
    // and mathmlBuilder.
    names: Array[String],

    // Properties that control how the environments are parsed.
    props: EnvProps,

    handler: EnvHandler,

    // This function returns an object representing the DOM structure to be
    // created when rendering the defined LaTeX function.
    htmlBuilder: Nullable[HtmlBuilder] = Nullable.Null,

    // This function returns an object representing the MathML structure to be
    // created when rendering the defined LaTeX function.
    mathmlBuilder: Nullable[MathMLBuilder] = Nullable.Null
)

object EnvironmentDef {

  /**
   * All registered environments.
   * `environments.js` exports this same dictionary again and makes it public.
   * `Parser.js` requires this dictionary via `environments.js`.
   */
  val _environments: mutable.Map[String, EnvSpec] = mutable.Map.empty

  def defineEnvironment(spec: EnvDefSpec): Unit = {
    // Set default values of environments.
    val data = EnvSpec(
      nodeType = spec.nodeType,
      numArgs = spec.props.numArgs,
      allowedInText = false,
      numOptionalArgs = 0,
      handler = spec.handler
    )
    var i = 0
    while (i < spec.names.length) {
      // TODO: The value type of _environments should be a type union of all
      // possible `EnvSpec` possibilities instead of `EnvSpec`, which is
      // an existential type.
      _environments(spec.names(i)) = data
      i += 1
    }
    spec.htmlBuilder.foreach { builder =>
      FunctionDef._htmlGroupBuilders(spec.nodeType) = builder
    }
    spec.mathmlBuilder.foreach { builder =>
      FunctionDef._mathmlGroupBuilders(spec.nodeType) = builder
    }
  }
}
