/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for identity.
 * Ported from: terser/test/compress/identity.js (11 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ InlineLevel, ToplevelConfig }

final class CompressIdentitySuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // inline_identity
  // =========================================================================
  test("inline_identity".fail) {
    assertCompresses(
      input = """const id = x => x;
        console.log(id(1), id(2))""".stripMargin.trim,
      expected = "console.log(1, 2)",
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_identity_function
  // =========================================================================
  test("inline_identity_function".fail) {
    assertCompresses(
      input = """function id(x) { return x };
        console.log(id(1), id(2))""".stripMargin.trim,
      expected = "console.log(1, 2)",
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_identity_undefined
  // =========================================================================
  test("inline_identity_undefined".fail) {
    assertCompresses(
      input = """const id = x => x;
        console.log(id(), id(undefined))""".stripMargin.trim,
      expected = "console.log(void 0, void 0)",
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_identity_extra_params
  // =========================================================================
  test("inline_identity_extra_params".fail) {
    assertCompresses(
      input = """const id = x => x;
        console.log(id(1, console.log(2)), id(3, 4))""".stripMargin.trim,
      expected = """const id = x => x;
        console.log(id(1, console.log(2)), 3)""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_identity_higher_order
  // =========================================================================
  test("inline_identity_higher_order".fail) {
    assertCompresses(
      input = """const id = x => x;
        const inc = x => x + 1;
        console.log(id(inc(1)), id(inc)(2))""".stripMargin.trim,
      expected = """const inc = x => x + 1;
        console.log(inc(1), inc(2))""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_identity_inline_function
  // =========================================================================
  test("inline_identity_inline_function".fail) {
    assertCompresses(
      input = """const id = x => x;
        console.log(id(x => x + 1)(1), id((x => x + 1)(2)))""".stripMargin.trim,
      expected = "console.log(2, 3)",
      options = AllOff.copy(
        evaluate = true,
        inline = InlineLevel.InlineFull,
        passes = 3,
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_identity_duplicate_arg_var
  // =========================================================================
  test("inline_identity_duplicate_arg_var".fail) {
    assertCompresses(
      input = """const id = x => {
            return x;
            var x;
        };
        console.log(id(1), id(2))""".stripMargin.trim,
      expected = "console.log(1, 2)",
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_identity_inner_ref
  // =========================================================================
  test("inline_identity_inner_ref".fail) {
    assertCompresses(
      input = """const id = a => (function() { return a; })();
        const undef = a => (a => a)();
        console.log(id(1), id(2), undef(3), undef(4))""".stripMargin.trim,
      expected = "console.log(1, 2, void 0, void 0)",
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_identity_async
  // =========================================================================
  test("inline_identity_async".fail) {
    assertCompresses(
      input = """const id = x => x;
        id(async () => await 1)();
        id(async x => await console.log(2))()""".stripMargin.trim,
      expected = """(async () => await 1)();
        (async () => await console.log(2))()""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_identity_lose_this
  // =========================================================================
  test("inline_identity_lose_this".fail) {
    assertCompresses(
      input = """"use strict";

        const id = x => x;

        const func_bag = {
            func: function () { return this === undefined ? "PASS" : "FAIL"; }
        };

        func_bag.func2 = function () { return this === undefined ? "PASS" : "FAIL"; };

        console.log(id(func_bag.func)());
        console.log(id(func_bag.func2)())""".stripMargin.trim,
      expected = """"use strict";

        const id = x => x;

        const func_bag = {
            func: function () { return this === void 0 ? "PASS" : "FAIL"; }
        };

        func_bag.func2 = function () { return this === void 0 ? "PASS" : "FAIL"; };

        console.log((0, func_bag.func)());
        console.log((0, func_bag.func2)())""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // inline_identity_dont_lose_this_when_arg
  // =========================================================================
  test("inline_identity_dont_lose_this_when_arg".fail) {
    assertCompresses(
      input = """"use strict";

        const id = x => x;

        const func_bag = { leak };

        leak(id(func_bag.leak))""".stripMargin.trim,
      expected = """"use strict";

        const id = x => x;

        const func_bag = { leak };

        leak(func_bag.leak)""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

}
