/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1007.
 * Ported from: terser/test/compress/issue-1007.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue1007Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // optional_chaining_boolean_expr
  // =========================================================================
  test("optional_chaining_boolean_expr".fail) {
    assertCompresses(
      input = """(function(option) {
            if (!(option.container?.tagName === "DIV"))
                throw new Error("Invalid `container` and/or `viewer` option.");
        })()""".stripMargin.trim,
      expected = """(function(option) {
            if (option.container?.tagName !== "DIV")
                throw new Error("Invalid `container` and/or `viewer` option.");
        })()""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        ecma = 2015
      )
    )
  }

}
