/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-59.
 * Ported from: terser/test/compress/issue-59.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue59Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // keep_continue
  // =========================================================================
  test("keep_continue") {
    assertCompresses(
      input = """while (a) {
            if (b) {
                switch (true) {
                  case c():
                    d();
                }
                continue;
            }
            f();
        }""".stripMargin.trim,
      expected = """while (a) {
            if (b) {
                switch (true) {
                  case c():
                    d();
                }
                continue;
            }
            f();
        }""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        evaluate = true
      )
    )
  }

}
