/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for negate-iife.
 * Ported from: terser/test/compress/negate-iife.js (15 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.InlineLevel

final class CompressNegateIifeSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // negate_iife_1 (un-pinned by ISS-1163: live-ancestry parent check)
  // =========================================================================
  test("negate_iife_1") {
    assertCompresses(
      input = "(function(){ stuff() })()",
      expected = "!function(){ stuff() }()",
      options = AllOff.copy(
        negateIife = true
      )
    )
  }

  // =========================================================================
  // negate_iife_3
  // =========================================================================
  test("negate_iife_3".fail) {
    assertCompresses(
      input = "(function(){ return t })() ? console.log(true) : console.log(false)",
      expected = "!function(){ return t }() ? console.log(false) : console.log(true)",
      options = AllOff.copy(
        conditionals = true,
        negateIife = true
      )
    )
  }

  // =========================================================================
  // negate_iife_3_evaluate
  // =========================================================================
  test("negate_iife_3_evaluate") {
    assertCompresses(
      input = "(function(){ return true })() ? console.log(true) : console.log(false)",
      expected = "console.log(true)",
      options = AllOff.copy(
        conditionals = true,
        evaluate = true,
        inline = InlineLevel.InlineFull,
        negateIife = true
      )
    )
  }

  // =========================================================================
  // negate_iife_3_side_effects
  // =========================================================================
  test("negate_iife_3_side_effects".fail) {
    assertCompresses(
      input = "(function(){ return t })() ? console.log(true) : console.log(false)",
      expected = "!function(){ return t }() ? console.log(false) : console.log(true)",
      options = AllOff.copy(
        conditionals = true,
        negateIife = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // negate_iife_3_off
  // =========================================================================
  test("negate_iife_3_off".fail) {
    assertCompresses(
      input = "(function(){ return t })() ? console.log(true) : console.log(false)",
      expected = "!function(){ return t }() ? console.log(false) : console.log(true)",
      options = AllOff.copy(
        conditionals = true,
        negateIife = false
      )
    )
  }

  // =========================================================================
  // negate_iife_3_off_evaluate
  // =========================================================================
  test("negate_iife_3_off_evaluate") {
    assertCompresses(
      input = "(function(){ return true })() ? console.log(true) : console.log(false)",
      expected = "console.log(true)",
      options = AllOff.copy(
        conditionals = true,
        evaluate = true,
        inline = InlineLevel.InlineFull,
        negateIife = false
      )
    )
  }

  // =========================================================================
  // negate_iife_4
  // =========================================================================
  test("negate_iife_4".fail) {
    assertCompresses(
      input = """(function(){ return t })() ? console.log(true) : console.log(false);
        (function(){
            console.log("something");
        })()""".stripMargin.trim,
      expected = """!function(){ return t }() ? console.log(false) : console.log(true), function(){
            console.log("something");
        }()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        negateIife = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // sequence_off
  // =========================================================================
  test("sequence_off".fail) {
    assertCompresses(
      input = """function f() {
            (function(){ return t })() ? console.log(true) : console.log(false);
            (function(){
                console.log("something");
            })();
        }
        function g() {
            (function(){
                console.log("something");
            })();
            (function(){ return t })() ? console.log(true) : console.log(false);
        }""".stripMargin.trim,
      expected = """function f() {
            !function(){ return t }() ? console.log(false) : console.log(true), function(){
                console.log("something");
            }();
        }
        function g() {
            (function(){
                console.log("something");
            })(), function(){ return t }() ? console.log(true) : console.log(false);
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        negateIife = false,
        passes = 2,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // negate_iife_5
  // =========================================================================
  test("negate_iife_5".fail) {
    assertCompresses(
      input = """if ((function(){ return t })()) {
            foo(true);
        } else {
            bar(false);
        }
        (function(){
            console.log("something");
        })()""".stripMargin.trim,
      expected = """!function(){ return t }() ? bar(false) : foo(true), function(){
            console.log("something");
        }()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        negateIife = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // negate_iife_5_off
  // =========================================================================
  test("negate_iife_5_off".fail) {
    assertCompresses(
      input = """if ((function(){ return t })()) {
            foo(true);
        } else {
            bar(false);
        }
        (function(){
            console.log("something");
        })()""".stripMargin.trim,
      expected = """!function(){ return t }() ? bar(false) : foo(true), function(){
            console.log("something");
        }()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        negateIife = false,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // negate_iife_nested (un-pinned by ISS-1163: live-ancestry parent check)
  // =========================================================================
  test("negate_iife_nested") {
    assertCompresses(
      input = """function Foo(f) {
            this.f = f;
        }
        new Foo(function() {
            (function(x) {
                (function(y) {
                    console.log(y);
                })(x);
            })(7);
        }).f()""".stripMargin.trim,
      expected = """function Foo(f) {
            this.f = f;
        }
        new Foo(function() {
            !function(x) {
                !function(y) {
                    console.log(y);
                }(x);
            }(7);
        }).f()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        negateIife = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // negate_iife_nested_off
  // =========================================================================
  test("negate_iife_nested_off") {
    assertCompresses(
      input = """function Foo(f) {
            this.f = f;
        }
        new Foo(function() {
            (function(x) {
                (function(y) {
                    console.log(y);
                })(x);
            })(7);
        }).f()""".stripMargin.trim,
      expected = """function Foo(f) {
            this.f = f;
        }
        new Foo(function() {
            (function(x) {
                (function(y) {
                    console.log(y);
                })(x);
            })(7);
        }).f()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        negateIife = false,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // negate_iife_issue_1073
  // =========================================================================
  test("negate_iife_issue_1073") {
    assertCompresses(
      input = """new (function(a) {
            return function Foo() {
                this.x = a;
                console.log(this);
            };
        }(7))()""".stripMargin.trim,
      expected = """new (function(a) {
            return function Foo() {
                this.x = a,
                console.log(this);
            };
        }(7))()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        negateIife = true,
        sequencesLimit = 200
      )
    )
  }

  // =========================================================================
  // issue_1288 (un-pinned by ISS-1163: live-ancestry parent check)
  // =========================================================================
  test("issue_1288") {
    assertCompresses(
      input = """if (w) ;
        else {
            (function f() {})();
        }
        if (!x) {
            (function() {
                x = {};
            })();
        }
        if (y)
            (function() {})();
        else
            (function(z) {
                return z;
            })(0)""".stripMargin.trim,
      expected = """w || !function f() {}();
        x || !function() {
            x = {};
        }();
        y ? !function() {}() : !function(z) {
            return z;
        }(0)""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        negateIife = true,
        sideEffects = false
      )
    )
  }

  // =========================================================================
  // issue_1288_side_effects
  // =========================================================================
  test("issue_1288_side_effects".fail) {
    assertCompresses(
      input = """if (w) ;
        else {
            (function f() {})();
        }
        if (!x) {
            (function() {
                x = {};
            })();
        }
        if (y)
            (function() {})();
        else
            (function(z) {
                return z;
            })(0)""".stripMargin.trim,
      expected = """w;
        x || function() {
            x = {};
        }();
        y""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        negateIife = true,
        sideEffects = true
      )
    )
  }

}
