/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for inline.
 * Ported from: terser/test/compress/inline.js (14 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ InlineLevel, ToplevelConfig }

final class CompressInlineSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // inline_within_extends_1
  // =========================================================================
  test("inline_within_extends_1".fail) {
    assertCompresses(
      input = """(function() {
            function foo(foo_base) {
                return class extends foo_base {};
            }
            function bar(bar_base) {
                return class extends bar_base {};
            }
            console.log((new class extends (foo(bar(Array))){}).concat(["PASS"])[0]);
        })()""".stripMargin.trim,
      expected = """console.log((new class extends(function(foo_base) {
            return class extends foo_base {};
        }(function(bar_base) {
            return class extends bar_base {};
        }(Array))){}).concat([ "PASS" ])[0])""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        inline = InlineLevel.InlineFull,
        passes = 1,
        reduceFuncs = true,
        reduceVars = true,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_within_extends_2
  // =========================================================================
  test("inline_within_extends_2".fail) {
    assertCompresses(
      input = """class Baz extends(foo(bar(Array))) {
            constructor() {
                super(...arguments);
            }
        }
        function foo(foo_base) {
            return class extends foo_base {
                constructor() {
                    super(...arguments);
                }
                second() {
                    return this[1];
                }
            };
        }
        function bar(bar_base) {
            return class extends bar_base {
                constructor(...args) {
                    super(...args);
                }
            };
        }
        console.log(new Baz(1, "PASS", 3).second())""".stripMargin.trim,
      expected = """class Baz extends(function(foo_base) {
            return class extends foo_base {
                constructor() {
                    super(...arguments);
                }
                second() {
                    return this[1];
                }
            };
        }(function(bar_base) {
            return class extends bar_base {
                constructor(...args) {
                    super(...args);
                }
            };
        }(Array))) {
            constructor() {
                super(...arguments);
            }
        }
        console.log(new Baz(1, "PASS", 3).second())""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = false,
        evaluate = true,
        inline = InlineLevel.InlineFull,
        passes = 3,
        reduceFuncs = true,
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // dont_inline_side_effects
  // =========================================================================
  test("dont_inline_side_effects") {
    assertCompresses(
      input = """class X extends (console.log("PASS 1"), null) {
            static [(console.log("PASS 2"), 'prop')] = "PASS 4"
        }

        console.log("PASS 3")

        console.log(X.prop)""".stripMargin.trim,
      expected = """class X extends (console.log("PASS 1"), null) {
            static [(console.log("PASS 2"), 'prop')] = "PASS 4"
        }

        console.log("PASS 3")

        console.log(X.prop)""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // issue_308
  // =========================================================================
  test("issue_308".fail) {
    assertCompresses(
      input = """exports.withStyles = withStyles;

        function _inherits(superClass) {
            if (typeof superClass !== "function") {
                throw new TypeError("Super expression must be a function, not " + typeof superClass);
            }
            Object.create(superClass);
        }

        function withStyles() {
            var a = EXTERNAL();
            return function(_a) {
                _inherits(_a);
                function d() {}
            }(a);
        }""".stripMargin.trim,
      expected = """exports.withStyles = function () {
            !function (superClass) {
                if ("function" != typeof superClass)
                    throw new TypeError("Super expression must be a function, not " + typeof superClass);
                Object.create(superClass);
            }(EXTERNAL());
        }""".stripMargin.trim,
      options = AllOff.copy(
        passes = 4,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // issue_1431_constructor_identity
  // =========================================================================
  test("issue_1431_constructor_identity") {
    assertCompresses(
      input = """let Class = class {};

        function sameConstructor() {
            return new Class()
        }

        console.log(sameConstructor().constructor === sameConstructor().constructor)""".stripMargin.trim,
      expected = """let Class = class {};

        function sameConstructor() {
            return new Class()
        }

        console.log(sameConstructor().constructor === sameConstructor().constructor)""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceFuncs = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // noinline_annotation
  // =========================================================================
  test("noinline_annotation") {
    assertCompresses(
      input = """function no_inline() {
            return 123;
        }

        /*#__NOINLINE__*/no_inline();
        /*#__NOINLINE__*/no_inline()""".stripMargin.trim,
      expected = """function no_inline() {
            return 123;
        }
        no_inline();
        no_inline()""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // noinline_annotation_2
  // =========================================================================
  test("noinline_annotation_2") {
    assertCompresses(
      input = """/*#__NOINLINE__*/
        (() => {
            external()
        })()""".stripMargin.trim,
      expected = """(() => {
            external()
        })()""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // noinline_annotation_3
  // =========================================================================
  test("noinline_annotation_3") {
    assertCompresses(
      input = """(function() {
            function foo(val) { return val; }
            function bar() {
                var pass = 1;
                pass = /*@__NOINLINE__*/ foo(pass);
                window.data = pass;
            }
            window.bar = bar;
            bar();
        })()""".stripMargin.trim,
      expected = """(function() {
            function foo(val) { return val; }
            function bar() {
                var pass = 1;
                pass = foo(pass);
                window.data = pass;
            }
            window.bar = bar;
            bar();
        })()""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_annotation
  // =========================================================================
  test("inline_annotation".fail) {
    assertCompresses(
      input = """function inline() {
            return external();
        }

        /*#__INLINE__*/inline();
        /*#__INLINE__*/inline()""".stripMargin.trim,
      expected = """external();
        external()""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_annotation_2
  // =========================================================================
  test("inline_annotation_2".fail) {
    assertCompresses(
      input = """const shouldInline = n => +n;

        const a = /*@__INLINE__*/ shouldInline("42.0");
        const b = /*@__INLINE__*/ shouldInline("abc");

        console.log(a, b)""".stripMargin.trim,
      expected = "console.log(42, NaN)",
      options = AllOff.copy(
        passes = 3,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // do_not_repeat_when_variable_larger_than_inlined_node
  // =========================================================================
  test("do_not_repeat_when_variable_larger_than_inlined_node".fail) {
    assertCompresses(
      input = """const _string_ = "string";

        pass(_string_);
        pass(_string_);
        pass(_string_);
        pass(_string_);
        pass(_string_)""".stripMargin.trim,
      expected = """const s = "string";

        pass(s);
        pass(s);
        pass(s);
        pass(s);
        pass(s)""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // do_not_repeat_when_variable_larger_than_inlined_node_2
  // =========================================================================
  test("do_not_repeat_when_variable_larger_than_inlined_node_2".fail) {
    assertCompresses(
      input = """const a=0.1, b=0.2, c=a+b;
        console.log(c)""".stripMargin.trim,
      expected = """const c=0.1+0.2;
        console.log(c)""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // do_not_repeat_when_variable_larger_than_inlined_node_3
  // =========================================================================
  test("do_not_repeat_when_variable_larger_than_inlined_node_3".fail) {
    assertCompresses(
      input = """const a = "string";
        const b = "string";
        const c = a + b;
        console.log(c, c)""".stripMargin.trim,
      expected = """const c = "stringstring";
        console.log(c, c)""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        inline = InlineLevel.InlineFull,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // inline_using_correct_arguments
  // =========================================================================
  test("inline_using_correct_arguments".fail) {
    assertCompresses(
      input = """function run (s, t) {
            return s.run(t);
        }

        /*#__INLINE__*/ run(a, "foo");
        /*#__INLINE__*/ run(a, "bar");
        /*#__INLINE__*/ run(a, "123")""".stripMargin.trim,
      expected = """s = a, t = "foo", s.run(t);
        var s, t;
        (function(s) { return s.run("bar") })(a);
        (function(s) { return s.run("123") })(a)""".stripMargin.trim,
      options = AllOff.copy(
        inline = InlineLevel.InlineFull,
        passes = 2,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

}
