/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1044.
 * Ported from: terser/test/compress/issue-1044.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue1044Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // issue_1044
  // =========================================================================
  test("issue_1044") {
    assertCompresses(
      input = "const mixed = Base ? class extends Base {} : class {}",
      expected = "const mixed = Base ? class extends Base {} : class {}",
      options = AllOff.copy(
        conditionals = true,
        evaluate = true
      )
    )
  }

}
