/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for import-meta.
 * Ported from: terser/test/compress/import-meta.js (5 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressImportMetaSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // import_meta_basic
  // =========================================================================
  test("import_meta_basic".fail) {
    assertCompresses(
      input = """import.meta
        import.meta.something
        import.meta?.something
        import.meta.url.includes()""".stripMargin.trim,
      expected = """import.meta,
        import.meta.something,
        import.meta,
        import.meta.url.includes()""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // propmangle
  // =========================================================================
  test("propmangle".fail) {
    assertCompresses(
      input = """import.meta
        import.meta.prop1
        import.meta["kept"]""".stripMargin.trim,
      expected = """import.meta
        import.meta._$$prop1$$_
        import.meta["kept"]""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // pure_getters
  // =========================================================================
  test("pure_getters") {
    assertCompresses(
      input = "import.meta",
      expected = "import.meta",
      options = AllOff.copy(
        pureGetters = "strict",
        unused = false
      )
    )
  }

  // =========================================================================
  // global_defs
  // =========================================================================
  test("global_defs".fail) {
    assertCompresses(
      input = """import.meta;
        leak(import.meta.LIT)
        leak(import.meta.OBJ)
        leak(import.meta.FUNC)""".stripMargin.trim,
      expected = """import.meta;
        leak(123);
        leak({hello: 123});
        leak(() => false)""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // global_defs_whole
  // =========================================================================
  test("global_defs_whole".fail) {
    assertCompresses(
      input = "console.log(import.meta.url)",
      expected = "console.log(\"http://example.com\")",
      options = AllOff
    )
  }

}
