/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1043.
 * Ported from: terser/test/compress/issue-1043.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue1043Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // issue_1043
  // =========================================================================
  test("issue_1043") {
    assertCompresses(
      input = """function* range(start = 0, end = null, step = 1) {
            if (end == null) {
                end = start;
                start = 0;
            }

            for (let i = start; i < end; i += step) {
                yield i;
            }
        }""".stripMargin.trim,
      expected = """function* range(start = 0, end = null, step = 1) {
            if (end == null) {
                end = start;
                start = 0;
            }

            for (let i = start; i < end; i += step)
                yield i;
        }""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

}
