/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1431.
 * Ported from: terser/test/compress/issue-1431.js (4 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue1431Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // level_zero
  // =========================================================================
  test("level_zero".fail) {
    assertCompresses(
      input = """function f(x) {
            function n(a) {
                return a * a;
            }
            return function() {
                return x;
            };
        }""".stripMargin.trim,
      expected = """function f(r) {
            function n(r) {
                return r * r;
            }
            return function() {
                return r;
            };
        }""".stripMargin.trim,
      options = AllOff.copy(
        keepFnames = true
      )
    )
  }

  // =========================================================================
  // level_one
  // =========================================================================
  test("level_one".fail) {
    assertCompresses(
      input = """function f(x) {
            return function() {
                function n(a) {
                    return a * a;
                }
                return x(n);
            };
        }""".stripMargin.trim,
      expected = """function f(r) {
            return function() {
                function n(r) {
                    return r * r;
                }
                return r(n);
            };
        }""".stripMargin.trim,
      options = AllOff.copy(
        keepFnames = true
      )
    )
  }

  // =========================================================================
  // level_two
  // =========================================================================
  test("level_two".fail) {
    assertCompresses(
      input = """function f(x) {
            return function() {
                function r(a) {
                    return a * a;
                }
                return function() {
                    function n(a) {
                        return a * a;
                    }
                    return x(n);
                };
            };
        }""".stripMargin.trim,
      expected = """function f(t) {
            return function() {
                function r(t) {
                    return t * t;
                }
                return function() {
                    function n(t) {
                        return t * t;
                    }
                    return t(n);
                };
            };
        }""".stripMargin.trim,
      options = AllOff.copy(
        keepFnames = true
      )
    )
  }

  // =========================================================================
  // level_three
  // =========================================================================
  test("level_three".fail) {
    assertCompresses(
      input = """function f(x) {
            return function() {
                function r(a) {
                    return a * a;
                }
                return [
                    function() {
                        function t(a) {
                            return a * a;
                        }
                        return t;
                    },
                    function() {
                        function n(a) {
                            return a * a;
                        }
                        return x(n);
                    }
                ];
            };
        }""".stripMargin.trim,
      expected = """function f(u) {
            return function() {
                function r(u) {
                    return u * u;
                }
                return [
                    function() {
                        function t(u) {
                            return u * u;
                        }
                        return t;
                    },
                    function() {
                        function n(u) {
                            return u * u;
                        }
                        return u(n);
                    }
                ];
            };
        }""".stripMargin.trim,
      options = AllOff.copy(
        keepFnames = true
      )
    )
  }

}
