/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for string-literal.
 * Ported from: terser/test/compress/string-literal.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressStringLiteralSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // octal_escape_sequence
  // =========================================================================
  test("octal_escape_sequence") {
    assertCompresses(
      input = """var boundaries = "\0\7\00\07\70\77\000\077\300\377";
        var border_check = "\400\700\0000\3000"""".stripMargin.trim,
      expected = """var boundaries = "\x00\x07\x00\x07\x38\x3f\x00\x3f\xc0\xff";
        var border_check = "\x20\x30\x38\x30\x00\x30\xc0\x30"""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // issue_1929
  // =========================================================================
  test("issue_1929") {
    assertCompresses(
      input = """function f(s) {
            return s.split(/[\\/]/);
        }
        var r = f("A/B\\C\\D/E\\F");
        console.log(r[5], r[4], r[3], r[2], r[1], r[0], r.length)""".stripMargin.trim,
      expected = """function f(s) {
            return s.split(/[\\/]/);
        }
        var r = f("A/B\\C\\D/E\\F");
        console.log(r[5], r[4], r[3], r[2], r[1], r[0], r.length)""".stripMargin.trim,
      options = AllOff
    )
  }

}
