/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue_999.
 * Ported from: terser/test/compress/issue_999.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue999Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // switch_case_and_private_fields
  // =========================================================================
  test("switch_case_and_private_fields".fail) {
    assertCompresses(
      input = """class A {
            #a = "FAIL";
            #b = "PASS";

            print(variant) {
                switch (variant) {
                    case 1:
                        return this.#a;
                    case 2:
                        return this.#b;
                }
            }
        }
        console.log(new A().print(2))""".stripMargin.trim,
      expected = """class A {
            #a = "FAIL";
            #b = "PASS";

            print(variant) {
                switch (variant) {
                    case 1:
                        return this.#a;
                    case 2:
                        return this.#b;
                }
            }
        }
        console.log(new A().print(2))""".stripMargin.trim,
      options = AllOff.copy(
        deadCode = true,
        switches = true
      )
    )
  }

}
