/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for sandbox.
 * Ported from: terser/test/compress/sandbox.js (1 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressSandboxSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // console_log
  // =========================================================================
  test("console_log") {
    assertCompresses(
      input = """console.log("%% %s");
        console.log("%% %s", "%s")""".stripMargin.trim,
      expected = """console.log("%% %s");
        console.log("%% %s", "%s")""".stripMargin.trim,
      options = AllOff
    )
  }

}
