/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for nullish.
 * Ported from: terser/test/compress/nullish.js (6 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.ToplevelConfig

final class CompressNullishSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // conditional_to_nullish_coalescing
  // =========================================================================
  test("conditional_to_nullish_coalescing") {
    assertCompresses(
      input = """const foo = id('something');

        leak(foo == null ? bar : foo)""".stripMargin.trim,
      expected = """const foo = id('something');

        leak(foo ?? bar)""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ecma = 2020,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // conditional_to_nullish_coalescing_2
  // =========================================================================
  test("conditional_to_nullish_coalescing_2") {
    assertCompresses(
      input = """const foo = id('something')

        console.log('negative cases')
        foo === null || foo === null ? bar : foo;
        foo === undefined || foo === undefined ? bar : foo;
        foo === null || foo === undefined ? foo : bar;
        some_global === null || some_global === undefined ? bar : some_global;

        console.log('positive cases')
        foo === null || foo === void 0 ? bar : foo;
        foo === null || foo === undefined ? bar : foo;
        foo === undefined || foo === null ? bar : foo""".stripMargin.trim,
      expected = """const foo = id('something')

        console.log('negative cases')
        foo === null || foo === null ? bar : foo;
        foo === void 0 || foo === void 0 ? bar : foo;
        foo === null || foo === void 0 ? foo : bar;
        some_global === null || some_global === void 0 ? bar : some_global;

        console.log('positive cases')
        foo ?? bar;
        foo ?? bar;
        foo ?? bar""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ecma = 2020,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // simplify_nullish_coalescing
  // =========================================================================
  test("simplify_nullish_coalescing".fail) {
    assertCompresses(
      input = """const y = id("one")
        const is_null = null
        const not_null = "two"
        console.log(is_null ?? y);
        console.log(not_null ?? y)""".stripMargin.trim,
      expected = """const y = id("one")
        console.log(y)
        console.log("two")""".stripMargin.trim,
      options = AllOff.copy(
        ecma = 2020,
        sequencesLimit = 0,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // nullish_coalescing_boolean_context
  // =========================================================================
  test("nullish_coalescing_boolean_context".fail) {
    assertCompresses(
      input = """if (null ?? unknown) {
            pass()
        }

        if (unknown ?? false) {
            pass()
        }

        if (4 + 4 ?? unknown) {
            pass()
        }""".stripMargin.trim,
      expected = """unknown&&pass();
        unknown&&pass();
        pass()""".stripMargin.trim,
      options = AllOff.copy(
        booleans = true,
        conditionals = true,
        ecma = 2020,
        evaluate = true,
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // delete_nullish
  // =========================================================================
  test("delete_nullish") {
    assertCompresses(
      input = """delete obj?.key;
        const other = { key: true };
        delete other?.key""".stripMargin.trim,
      expected = """delete obj?.key;
        const other = { key: true };
        delete other?.key""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // delete_nullish_2
  // =========================================================================
  test("delete_nullish_2".fail) {
    assertCompresses(
      input = """delete null?.key;
        delete null?.deep.key;
        delete null.deep?.key;
        delete null?.deep?.key""".stripMargin.trim,
      expected = "delete null.deep?.key",
      options = AllOff.copy(
        evaluate = true,
        passes = 3
      )
    )
  }

}
