/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-782.
 * Ported from: terser/test/compress/issue-782.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue782Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // remove_redundant_sequence_items
  // =========================================================================
  test("remove_redundant_sequence_items".fail) {
    assertCompresses(
      input = """(0, 1, eval)();
        (0, 1, logThis)();
        (0, 1, _decorators.logThis)()""".stripMargin.trim,
      expected = """(0, eval)();
        logThis();
        (0, _decorators.logThis)()""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // dont_remove_this_binding_sequence
  // =========================================================================
  test("dont_remove_this_binding_sequence".fail) {
    assertCompresses(
      input = """(0, eval)();
        (0, logThis)();
        (0, _decorators.logThis)()""".stripMargin.trim,
      expected = """(0, eval)();
        logThis();
        (0, _decorators.logThis)()""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

}
