/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-973.
 * Ported from: terser/test/compress/issue-973.js (3 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.ToplevelConfig

final class CompressIssue973Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // this_binding_conditionals
  // =========================================================================
  test("this_binding_conditionals".fail) {
    assertCompresses(
      input = """(1 && a)();
        (0 || a)();
        (0 || 1 && a)();
        (1 ? a : 0)();

        (1 && a.b)();
        (0 || a.b)();
        (0 || 1 && a.b)();
        (1 ? a.b : 0)();

        (1 && a[b])();
        (0 || a[b])();
        (0 || 1 && a[b])();
        (1 ? a[b] : 0)();

        (1 && eval)();
        (0 || eval)();
        (0 || 1 && eval)();
        (1 ? eval : 0)()""".stripMargin.trim,
      expected = """a();
        a();
        a();
        a();

        (0, a.b)();
        (0, a.b)();
        (0, a.b)();
        (0, a.b)();

        (0, a[b])();
        (0, a[b])();
        (0, a[b])();
        (0, a[b])();

        (0, eval)();
        (0, eval)();
        (0, eval)();
        (0, eval)()""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        evaluate = true,
        sideEffects = true
      )
    )
  }

  // =========================================================================
  // this_binding_collapse_vars
  // =========================================================================
  test("this_binding_collapse_vars".fail) {
    assertCompresses(
      input = """var c = a; c();
        var d = a.b; d();
        var e = eval; e()""".stripMargin.trim,
      expected = """a();
        (0, a.b)();
        (0, eval)()""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // this_binding_side_effects
  // =========================================================================
  test("this_binding_side_effects".fail) {
    assertCompresses(
      input = """(function (foo) {
            (0, foo)();
            (0, foo.bar)();
            (0, eval)('console.log(foo);');
        }());
        (function (foo) {
            var eval = console;
            (0, foo)();
            (0, foo.bar)();
            (0, eval)('console.log(foo);');
        }())""".stripMargin.trim,
      expected = """(function (foo) {
            foo();
            (0, foo.bar)();
            (0, eval)('console.log(foo);');
        }());
        (function (foo) {
            var eval = console;
            foo();
            (0, foo.bar)();
            (0, eval)('console.log(foo);');
        }())""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true
      )
    )
  }

}
