/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-208.
 * Ported from: terser/test/compress/issue-208.js (3 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue208Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // do_not_update_lhs
  // =========================================================================
  test("do_not_update_lhs") {
    assertCompresses(
      input = """DEBUG++;
        DEBUG += 1;
        DEBUG = 1""".stripMargin.trim,
      expected = """DEBUG++;
        DEBUG += 1;
        DEBUG = 1""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // do_update_rhs
  // =========================================================================
  test("do_update_rhs".fail) {
    assertCompresses(
      input = """MY_DEBUG = DEBUG;
        MY_DEBUG += DEBUG""".stripMargin.trim,
      expected = """MY_DEBUG = 0;
        MY_DEBUG += 0""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // mixed
  // =========================================================================
  test("mixed".fail) {
    assertCompresses(
      input = """const ENV = 3;
        var FOO = 4;
        f(ENV * 10);
        --FOO;
        DEBUG = 1;
        DEBUG++;
        DEBUG += 1;
        f(DEBUG);
        x = DEBUG""".stripMargin.trim,
      expected = """const ENV = 3;
        var FOO = 4;
        f(10);
        --FOO;
        DEBUG = 1;
        DEBUG++;
        DEBUG += 1;
        f(0);
        x = 0""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true
      )
    )
  }

}
