/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-2001.
 * Ported from: terser/test/compress/issue-2001.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.ToplevelConfig

final class CompressIssue2001Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // export_toplevel_1
  // =========================================================================
  test("export_toplevel_1".fail) {
    assertCompresses(
      input = """function f(){}
        export function g(){}
        export default function h(){}""".stripMargin.trim,
      expected = """export function g(){}
        export default function h(){}""".stripMargin.trim,
      options = AllOff.copy(
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // export_toplevel_2
  // =========================================================================
  test("export_toplevel_2".fail) {
    assertCompresses(
      input = """class A {}
        export class B {}
        export default class C {}""".stripMargin.trim,
      expected = """export class B {}
        export default class C {}""".stripMargin.trim,
      options = AllOff.copy(
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

}
