/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1609.
 * Ported from: terser/test/compress/issue-1609.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue1609Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // chained_evaluation_1
  // =========================================================================
  test("chained_evaluation_1".fail) {
    assertCompresses(
      input = """(function() {
            var a = 1;
            (function() {
                var b = a, c;
                c = f(b);
                c.bar = b;
            })();
        })()""".stripMargin.trim,
      expected = """(function() {
            (function() {
                f(1).bar = 1;
            })();
        })()""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        evaluate = true,
        reduceFuncs = true,
        reduceVars = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // chained_evaluation_2
  // =========================================================================
  test("chained_evaluation_2".fail) {
    assertCompresses(
      input = """(function() {
            var a = "long piece of string";
            (function() {
                var b = a, c;
                c = f(b);
                c.bar = b;
            })();
        })()""".stripMargin.trim,
      expected = """(function() {
            (function() {
                var b = "long piece of string";
                f(b).bar = b;
            })();
        })()""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        evaluate = true,
        reduceFuncs = true,
        reduceVars = true,
        unused = true
      )
    )
  }

}
