/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for parameters.
 * Ported from: terser/test/compress/parameters.js (6 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressParametersSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // regression_assign_arrow_functions
  // =========================================================================
  test("regression_assign_arrow_functions") {
    assertCompresses(
      input = """oninstall = e => false;
        oninstall = () => false""".stripMargin.trim,
      expected = """oninstall=e=>false;
        oninstall=()=>false""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // destructuring_arguments_1
  // =========================================================================
  test("destructuring_arguments_1".fail) {
    assertCompresses(
      input = """(function ( a ) { });
        (function ( [ a ] ) { });
        (function ( [ a, b ] ) { });
        (function ( [ [ a ] ] ) { });
        (function ( [ [ a, b ] ] ) { });
        (function ( [ a, [ b ] ] ) { });
        (function ( [ [ b ], a ] ) { });

        (function ( { a } ) { });
        (function ( { a, b } ) { });

        (function ( [ { a } ] ) { });
        (function ( [ { a, b } ] ) { });
        (function ( [ a, { b } ] ) { });
        (function ( [ { b }, a ] ) { });

        ( [ a ] ) => { };
        ( [ a, b ] ) => { };

        ( { a } ) => { };
        ( { a, b, c, d, e } ) => { };

        ( [ a ] ) => b;
        ( [ a, b ] ) => c;

        ( { a } ) => b;
        ( { a, b } ) => c""".stripMargin.trim,
      expected = """(function(a){});
        (function([a]){});
        (function([a,b]){});
        (function([[a]]){});
        (function([[a,b]]){});
        (function([a,[b]]){});
        (function([[b],a]){});

        (function({a}){});
        (function({a,b}){});

        (function([{a}]){});
        (function([{a,b}]){});
        (function([a,{b}]){});
        (function([{b},a]){});

        ([a])=>{};
        ([a,b])=>{};

        ({a})=>{};
        ({a,b,c,d,e})=>{};

        ([a])=>b;
        ([a,b])=>c;

        ({a})=>b;
        ({a,b})=>c""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // destructuring_arguments_2
  // =========================================================================
  test("destructuring_arguments_2".fail) {
    assertCompresses(
      input = """(function([]) {});
        (function({}) {});
        (function([,,,,,]) {});
        (function ([a, {b: c}]) {});
        (function ([...args]) {});
        (function ({x,}) {});
        class a { *method({ [thrower()]: x } = {}) {}};
        (function(a, b, c, d, [{e: [...f]}]){})(1, 2, 3, 4, [{e: [1, 2, 3]}])""".stripMargin.trim,
      expected = """(function([]) {});
        (function({}) {});
        (function([,,,,,]) {});
        (function ([a, {b: c}]) {});
        (function ([...args]) {});
        (function ({x,}) {});
        class a { *method({ [thrower()]: x } = {}) {}};
        (function(a, b, c, d, [{e: [...f]}]){})(1, 2, 3, 4, [{e: [1, 2, 3]}])""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // keep_default_arg_when_undefined
  // =========================================================================
  test("keep_default_arg_when_undefined".fail) {
    assertCompresses(
      input = """function x(a = void 0) { }
        console.log(x.length)""".stripMargin.trim,
      expected = """function x(a = void 0) { }
        console.log(x.length)""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        keepFargs = true
      )
    )
  }

  // =========================================================================
  // drop_default_arg_when_undefined_and_iife
  // =========================================================================
  test("drop_default_arg_when_undefined_and_iife") {
    assertCompresses(
      input = "console.log((function x(a = void 0) { })())",
      expected = "console.log((function x(a) { })())",
      options = AllOff.copy(
        evaluate = true,
        keepFargs = true
      )
    )
  }

  // =========================================================================
  // accept_duplicated_parameters_in_non_strict_without_spread_or_default_assignment
  // =========================================================================
  test("accept_duplicated_parameters_in_non_strict_without_spread_or_default_assignment") {
    assertCompresses(
      input = """function a(b, b){}
        function b({c: test, c: test}){}""".stripMargin.trim,
      expected = """function a(b, b){}
        function b({c: test, c: test}){}""".stripMargin.trim,
      options = AllOff
    )
  }

}
