/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for drop-console.
 * Ported from: terser/test/compress/drop-console.js (5 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ DropConsoleConfig, ToplevelConfig }

final class CompressDropConsoleSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // drop_console_1
  // =========================================================================
  test("drop_console_1") {
    assertCompresses(
      input = """console.log('foo');
        console.log.apply(console, arguments)""".stripMargin.trim,
      expected = """console.log('foo');
        console.log.apply(console, arguments)""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // drop_console_2
  // =========================================================================
  test("drop_console_2") {
    assertCompresses(
      input = """console.log('foo');
        console.log.apply(console, arguments)""".stripMargin.trim,
      expected = """// with regular compression these will be stripped out as well
        void 0;
        void 0""".stripMargin.trim,
      options = AllOff.copy(
        dropConsole = DropConsoleConfig.All
      )
    )
  }

  // =========================================================================
  // unexpected_side_effects_dropping_console
  // =========================================================================
  test("unexpected_side_effects_dropping_console".fail) {
    assertCompresses(
      input = """function f() {
            var a = 33;
            console.log(a++);
            alert(a);
        }""".stripMargin.trim,
      expected = """function f() {
            alert(33);
        }""".stripMargin.trim,
      options = AllOff.copy(
        dropConsole = DropConsoleConfig.All,
        evaluate = true,
        reduceVars = true,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // unexpected_returned_value_dropping_console
  // =========================================================================
  test("unexpected_returned_value_dropping_console".fail) {
    assertCompresses(
      input = """const b = {
            log: console.log.bind(console),
        };

        b.log("hi")""".stripMargin.trim,
      expected = """const b={
            log: function(){}.bind(),
        };

        b.log("hi")""".stripMargin.trim,
      options = AllOff.copy(
        dropConsole = DropConsoleConfig.All,
        evaluate = true,
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // drop_console_with_array_option
  // =========================================================================
  test("drop_console_with_array_option") {
    assertCompresses(
      input = """console.log("foo");
        console.log.apply(console, arguments);
        console.info("foo")""".stripMargin.trim,
      expected = """void 0;
        void 0;
        console.info("foo")""".stripMargin.trim,
      options = AllOff.copy(
        dropConsole = DropConsoleConfig.Methods(Set("log"))
      )
    )
  }

}
