/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1052.
 * Ported from: terser/test/compress/issue-1052.js (7 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue1052Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // multiple_functions
  // =========================================================================
  test("multiple_functions".fail) {
    assertCompresses(
      input = """( function() {
            if ( !window ) {
                return;
            }
            function f() {}
            function g() {}
        } )()""".stripMargin.trim,
      expected = """( function() {
            // NOTE: other compression steps will reduce this
            // down to just `window`.
            if ( window );
            function f() {}
            function g() {}
        } )()""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = false,
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // single_function
  // =========================================================================
  test("single_function".fail) {
    assertCompresses(
      input = """( function() {
            if ( !window ) {
                return;
            }
            function f() {}
        } )()""".stripMargin.trim,
      expected = """( function() {
            if ( window );
            function f() {}
        } )()""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = false,
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // deeply_nested
  // =========================================================================
  test("deeply_nested".fail) {
    assertCompresses(
      input = """( function() {
            if ( !window ) {
                return;
            }
            function f() {}
            function g() {}
            if ( !document ) {
                return;
            }
            function h() {}
        } )()""".stripMargin.trim,
      expected = """( function() {
            // NOTE: other compression steps will reduce this
            // down to just `window`.
            if ( window )
                if (document);
            function f() {}
            function g() {}
            function h() {}
        } )()""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = false,
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // not_hoisted_when_already_nested
  // =========================================================================
  test("not_hoisted_when_already_nested".fail) {
    assertCompresses(
      input = """( function() {
            if ( !window ) {
                return;
            }
            if ( foo ) function f() {}
        } )()""".stripMargin.trim,
      expected = """( function() {
            if ( window )
                if ( foo ) function f() {}
        } )()""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = false,
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // defun_if_return
  // =========================================================================
  test("defun_if_return".fail) {
    assertCompresses(
      input = """function e() {
            function f() {}
            if (!window) return;
            else function g() {}
            function h() {}
        }""".stripMargin.trim,
      expected = """function e() {
            function f() {}
            if (window) function g() {}
            function h() {}
        }""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = false,
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // defun_hoist_funs
  // =========================================================================
  test("defun_hoist_funs".fail) {
    assertCompresses(
      input = """function e() {
            function f() {}
            if (!window) return;
            else function g() {}
            function h() {}
        }""".stripMargin.trim,
      expected = """function e() {
            function f() {}
            function h() {}
            if (window) function g() {}
        }""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = true,
        ifReturn = true
      )
    )
  }

  // =========================================================================
  // defun_else_if_return
  // =========================================================================
  test("defun_else_if_return".fail) {
    assertCompresses(
      input = """function e() {
            function f() {}
            if (window) function g() {}
            else return;
            function h() {}
        }""".stripMargin.trim,
      expected = """function e() {
            function f() {}
            if (window) function g() {}
            function h() {}
        }""".stripMargin.trim,
      options = AllOff.copy(
        hoistFuns = false,
        ifReturn = true
      )
    )
  }

}
