/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for issue-1443.
 * Ported from: terser/test/compress/issue-1443.js (2 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }

final class CompressIssue1443Suite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // unsafe_undefined
  // =========================================================================
  test("unsafe_undefined".fail) {
    assertCompresses(
      input = """function f(undefined) {
            return function() {
                if (a)
                    return b;
                if (c)
                    return d;
            };
        }""".stripMargin.trim,
      expected = """function f(n) {
            return function() {
                return a ? b : c ? d : n;
            };
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true,
        unsafeUndefined = true
      )
    )
  }

  // =========================================================================
  // keep_fnames
  // =========================================================================
  test("keep_fnames".fail) {
    assertCompresses(
      input = """function f(undefined) {
            return function() {
                function n(a) {
                    return a * a;
                }
                if (a)
                    return b;
                if (c)
                    return d;
            };
        }""".stripMargin.trim,
      expected = """function f(r) {
            return function() {
                function n(r) {
                    return r * r;
                }
                return a ? b : c ? d : r;
            };
        }""".stripMargin.trim,
      options = AllOff.copy(
        conditionals = true,
        ifReturn = true,
        unsafeUndefined = true
      )
    )
  }

}
