/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for async.
 * Ported from: terser/test/compress/async.js (11 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.{ InlineLevel, ToplevelConfig }

final class CompressAsyncSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // async_function_declaration
  // =========================================================================
  test("async_function_declaration") {
    assertCompresses(
      input = """async function f0() {}
        async function f1() { await x + y; }
        async function f2() { await (x + y); }
        async function f3() { await x + await y; }
        async function f4() { await (x + await y); }
        async function f5() { await x; await y; }
        async function f6() { await x, await y; }""".stripMargin.trim,
      expected = """async function f0() {}
        async function f1() { await x, y; }
        async function f2() { await (x + y); }
        async function f3() { await x, await y; }
        async function f4() { await (x + await y); }
        async function f5() { await x; await y; }
        async function f6() { await x, await y; }""".stripMargin.trim,
      options = AllOff.copy(
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // async_function_expression
  // =========================================================================
  test("async_function_expression".fail) {
    assertCompresses(
      input = """var named = async function foo() {
            await bar(1 + 0) + (2 + 0);
        }
        var anon = async function() {
            await (1 + 0) + bar(2 + 0);
        }""".stripMargin.trim,
      expected = """var named = async function() {
            await bar(1);
        };
        var anon = async function() {
            await 1, bar(2);
        }""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true,
        sideEffects = true,
        unused = true
      )
    )
  }

  // =========================================================================
  // async_class
  // =========================================================================
  test("async_class".fail) {
    assertCompresses(
      input = """class Foo {
            async m1() {
                return await foo(1 + 2);
            }
            static async m2() {
                return await foo(3 + 4);
            }
        }""".stripMargin.trim,
      expected = """class Foo {
            async m1() {
                return await foo(3);
            }
            static async m2() {
                return await foo(7);
            }
        }""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true
      )
    )
  }

  // =========================================================================
  // async_object_literal
  // =========================================================================
  test("async_object_literal".fail) {
    assertCompresses(
      input = """var obj = {
            async a() {
                await foo(1 + 0);
            },
            anon: async function(){
                await foo(2 + 0);
            }
        }""".stripMargin.trim,
      expected = """var obj = {
            async a() {
                await foo(1);
            },
            anon: async function() {
                await foo(2);
            }
        }""".stripMargin.trim,
      options = AllOff.copy(
        evaluate = true
      )
    )
  }

  // =========================================================================
  // async_export
  // =========================================================================
  test("async_export") {
    assertCompresses(
      input = """export async function run() {};
        export default async function def() {}""".stripMargin.trim,
      expected = """export async function run() {};
        export default async function def() {}""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // async_inline
  // =========================================================================
  test("async_inline".fail) {
    assertCompresses(
      input = """(async function(){ return await 3; })();
        (async function(x){ await console.log(x); })(4);

        function invoke(x, y) { return x(y); }
        invoke( async function(){ return await 1; } );
        invoke( async function(x){ await console.log(x); }, 2);

        function top() { console.log("top"); }
        top();

        async function async_top() { console.log("async_top"); }
        async_top()""".stripMargin.trim,
      expected = """!async function(){await 3}();
        !async function(){await console.log(4)}();

        function invoke(x, y){return x(y)}
        invoke(async function(){return await 1});
        invoke(async function(x){await console.log(x)}, 2);

        console.log("top");

        !async function(){console.log("async_top")}()""".stripMargin.trim,
      options = AllOff.copy(
        collapseVars = true,
        conditionals = true,
        evaluate = true,
        inline = InlineLevel.InlineFull,
        negateIife = true,
        reduceFuncs = true,
        reduceVars = true,
        sideEffects = true,
        toplevel = ToplevelConfig(funcs = true, vars = true),
        unused = true
      )
    )
  }

  // =========================================================================
  // async_identifiers
  // =========================================================================
  test("async_identifiers") {
    assertCompresses(
      input = """var async = function(x){ console.log("async", x); };
        var await = function(x){ console.log("await", x); };
        async(1);
        await(2)""".stripMargin.trim,
      expected = """var async = function(x){ console.log("async", x); };
        var await = function(x){ console.log("await", x); };
        async(1);
        await(2)""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // async_shorthand_property
  // =========================================================================
  test("async_shorthand_property".fail) {
    assertCompresses(
      input = """function print(o) { console.log(o.async + " " + o.await); }
        var async = "Async", await = "Await";

        print({ async });
        print({ await });
        print({ async, await });
        print({ await, async });

        print({ async: async });
        print({ await: await });
        print({ async: async, await: await });
        print({ await: await, async: async })""".stripMargin.trim,
      expected = """function a(a) { console.log(a.async + " " + a.await); }
        var n = "Async", c = "Await";

        a({ async: n });
        a({ await: c });
        a({ async: n, await: c });
        a({ await: c, async: n });

        a({ async: n });
        a({ await: c });
        a({ async: n, await: c });
        a({ await: c, async: n })""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // async_arrow
  // =========================================================================
  test("async_arrow") {
    assertCompresses(
      input = """let a1 = async x => await foo(x);
        let a2 = async () => await bar();
        let a3 = async (x) => await baz(x);
        let a4 = async (x, y) => { await far(x, y); }
        let a5 = async ({x = [1], y: z = 2}) => { await wow(x, z); }""".stripMargin.trim,
      expected = """let a1 = async x => await foo(x);
        let a2 = async () => await bar();
        let a3 = async (x) => await baz(x);
        let a4 = async (x, y) => { await far(x, y); }
        let a5 = async ({x = [1], y: z = 2}) => { await wow(x, z); }""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // issue_3079
  // =========================================================================
  test("issue_3079") {
    assertCompresses(
      input = """async => 1;
        var async = async => async;
        console.log(async(1));
        async = (async) => async;
        console.log(async(2));
        console.log({
            m: async => async ? "3" : "4"
        }.m(true))""".stripMargin.trim,
      expected = """async => 1;
        var async = async => async;
        console.log(async(1));
        async = (async) => async;
        console.log(async(2));
        console.log({
            m: async => async ? "3" : "4"
        }.m(true))""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // for_await_of_2
  // =========================================================================
  test("for_await_of_2") {
    assertCompresses(
      input = """async function foo(x) {
            for await (a of x) {}
            for await (var b of x) {}
            for await (let c of x) {}
            for await (const d of x) {}
        }
        const bar = async x => {
            for await (a of x) {}
            for await (var b of x) {}
            for await (let c of x) {}
            for await (const d of x) {}
        }""".stripMargin.trim,
      expected = """async function foo(x) {
            for await (a of x) ;
            for await (var b of x) ;
            for await (let c of x) ;
            for await (const d of x) ;
        }
        const bar = async x => {
            for await (a of x) ;
            for await (var b of x) ;
            for await (let c of x) ;
            for await (const d of x) ;
        }""".stripMargin.trim,
      options = AllOff
    )
  }

}
