/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0
 *
 * Compression tests for comparing.
 * Ported from: terser/test/compress/comparing.js (12 test cases)
 *
 * Uses CompressTestHelper with false_by_default mode.
 * Auto-generated by scripts/gen-compress-tests.js */
package ssg
package js
package compress

import CompressTestHelper.{ AllOff, assertCompresses }
import ssg.js.compress.ToplevelConfig

final class CompressComparingSuite extends munit.FunSuite {

  override val munitTimeout = scala.concurrent.duration.Duration(120, "s")

  // =========================================================================
  // keep_comparisons
  // =========================================================================
  test("keep_comparisons") {
    assertCompresses(
      input = """var obj1 = {
            valueOf: function() {triggeredFirst();}
        }
        var obj2 = {
            valueOf: function() {triggeredSecond();}
        }
        var result1 = obj1 <= obj2;
        var result2 = obj1 <  obj2;
        var result3 = obj1 >= obj2;
        var result4 = obj1 >  obj2""".stripMargin.trim,
      expected = """var obj1 = {
            valueOf: function() {triggeredFirst();}
        }
        var obj2 = {
            valueOf: function() {triggeredSecond();}
        }
        var result1 = obj1 <= obj2;
        var result2 = obj1 <  obj2;
        var result3 = obj1 >= obj2;
        var result4 = obj1 >  obj2""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        unsafeComps = false
      )
    )
  }

  // =========================================================================
  // keep_comparisons_with_unsafe_comps
  // =========================================================================
  test("keep_comparisons_with_unsafe_comps".fail) {
    assertCompresses(
      input = """var obj1 = {
            valueOf: function() {triggeredFirst();}
        }
        var obj2 = {
            valueOf: function() {triggeredSecond();}
        }
        var result1 = obj1 <= obj2;
        var result2 = obj1 <  obj2;
        var result3 = obj1 >= obj2;
        var result4 = obj1 >  obj2""".stripMargin.trim,
      expected = """var obj1 = {
            valueOf: function() {triggeredFirst();}
        }
        var obj2 = {
            valueOf: function() {triggeredSecond();}
        }
        var result1 = obj2 >= obj1;
        var result2 = obj2 >  obj1;
        var result3 = obj1 >= obj2;
        var result4 = obj1 >  obj2""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        unsafeComps = true
      )
    )
  }

  // =========================================================================
  // dont_change_in_or_instanceof_expressions
  // =========================================================================
  test("dont_change_in_or_instanceof_expressions") {
    assertCompresses(
      input = """1 in 1;
        null in null;
        1 instanceof 1;
        null instanceof null""".stripMargin.trim,
      expected = """1 in 1;
        null in null;
        1 instanceof 1;
        null instanceof null""".stripMargin.trim,
      options = AllOff
    )
  }

  // =========================================================================
  // self_comparison_1
  // =========================================================================
  test("self_comparison_1".fail) {
    assertCompresses(
      input = """a === a;
        a !== b;
        b.c === a.c;
        b.c !== b.c""".stripMargin.trim,
      expected = """a == a;
        a !== b;
        b.c === a.c;
        b.c != b.c""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true
      )
    )
  }

  // =========================================================================
  // self_comparison_2
  // =========================================================================
  test("self_comparison_2".fail) {
    assertCompresses(
      input = """function f() {}
        var o = {};
        console.log(f != f, o === o)""".stripMargin.trim,
      expected = """function f() {}
        var o = {};
        console.log(false, true)""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        reduceFuncs = true,
        reduceVars = true,
        toplevel = ToplevelConfig(funcs = true, vars = true)
      )
    )
  }

  // =========================================================================
  // issue_2857_1
  // =========================================================================
  test("issue_2857_1") {
    assertCompresses(
      input = """function f1(a) {
            a === undefined || a === null;
            a === undefined || a !== null;
            a !== undefined || a === null;
            a !== undefined || a !== null;
            a === undefined && a === null;
            a === undefined && a !== null;
            a !== undefined && a === null;
            a !== undefined && a !== null;
        }
        function f2(a) {
            a === null || a === undefined;
            a === null || a !== undefined;
            a !== null || a === undefined;
            a !== null || a !== undefined;
            a === null && a === undefined;
            a === null && a !== undefined;
            a !== null && a === undefined;
            a !== null && a !== undefined;
        }""".stripMargin.trim,
      expected = """function f1(a) {
            null == a;
            void 0 === a || null !== a;
            void 0 !== a || null === a;
            void 0 !== a || null !== a;
            void 0 === a && null === a;
            void 0 === a && null !== a;
            void 0 !== a && null === a;
            null != a;
        }
        function f2(a) {
            null == a;
            null === a || void 0 !== a;
            null !== a || void 0 === a;
            null !== a || void 0 !== a;
            null === a && void 0 === a;
            null === a && void 0 !== a;
            null !== a && void 0 === a;
            null != a;
        }""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        lhsConstants = true
      )
    )
  }

  // =========================================================================
  // issue_2857_2
  // =========================================================================
  test("issue_2857_2") {
    assertCompresses(
      input = """function f(a, p) {
            a === undefined || a === null || p;
            a === undefined || a !== null || p;
            a !== undefined || a === null || p;
            a !== undefined || a !== null || p;
            a === undefined && a === null || p;
            a === undefined && a !== null || p;
            a !== undefined && a === null || p;
            a !== undefined && a !== null || p;
        }""".stripMargin.trim,
      expected = """function f(a, p) {
            null == a || p;
            void 0 === a || null !== a || p;
            void 0 !== a || null === a || p;
            void 0 !== a || null !== a || p;
            void 0 === a && null === a || p;
            void 0 === a && null !== a || p;
            void 0 !== a && null === a || p;
            null != a || p;
        }""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        lhsConstants = true
      )
    )
  }

  // =========================================================================
  // issue_2857_3
  // =========================================================================
  test("issue_2857_3") {
    assertCompresses(
      input = """function f(a, p) {
            a === undefined || a === null && p;
            a === undefined || a !== null && p;
            a !== undefined || a === null && p;
            a !== undefined || a !== null && p;
            a === undefined && a === null && p;
            a === undefined && a !== null && p;
            a !== undefined && a === null && p;
            a !== undefined && a !== null && p;
        }""".stripMargin.trim,
      expected = """function f(a, p) {
            void 0 === a || null === a && p;
            void 0 === a || null !== a && p;
            void 0 !== a || null === a && p;
            void 0 !== a || null !== a && p;
            void 0 === a && null === a && p;
            void 0 === a && null !== a && p;
            void 0 !== a && null === a && p;
            null != a && p;
        }""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        lhsConstants = true
      )
    )
  }

  // =========================================================================
  // issue_2857_4
  // =========================================================================
  test("issue_2857_4") {
    assertCompresses(
      input = """function f(a, p) {
            p || a === undefined || a === null;
            p || a === undefined || a !== null;
            p || a !== undefined || a === null;
            p || a !== undefined || a !== null;
            p || a === undefined && a === null;
            p || a === undefined && a !== null;
            p || a !== undefined && a === null;
            p || a !== undefined && a !== null;
        }""".stripMargin.trim,
      expected = """function f(a, p) {
            p || null == a;
            p || void 0 === a || null !== a;
            p || void 0 !== a || null === a;
            p || void 0 !== a || null !== a;
            p || void 0 === a && null === a;
            p || void 0 === a && null !== a;
            p || void 0 !== a && null === a;
            p || null != a;
        }""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        lhsConstants = true
      )
    )
  }

  // =========================================================================
  // issue_2857_5
  // =========================================================================
  test("issue_2857_5") {
    assertCompresses(
      input = """function f(a, p) {
            p && a === undefined || a === null;
            p && a === undefined || a !== null;
            p && a !== undefined || a === null;
            p && a !== undefined || a !== null;
            p && a === undefined && a === null;
            p && a === undefined && a !== null;
            p && a !== undefined && a === null;
            p && a !== undefined && a !== null;
        }""".stripMargin.trim,
      expected = """function f(a, p) {
            p && void 0 === a || null === a;
            p && void 0 === a || null !== a;
            p && void 0 !== a || null === a;
            p && void 0 !== a || null !== a;
            p && void 0 === a && null === a;
            p && void 0 === a && null !== a;
            p && void 0 !== a && null === a;
            p && null != a;
        }""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        lhsConstants = true
      )
    )
  }

  // =========================================================================
  // issue_2857_6
  // =========================================================================
  test("issue_2857_6".fail) {
    assertCompresses(
      input = """function f(a) {
            if (({}).b === undefined || {}.b === null)
                return a.b !== undefined && a.b !== null;
        }
        console.log(f({
            a: [ null ],
            get b() {
                return this.a.shift();
            }
        }))""".stripMargin.trim,
      expected = """function f(a) {
            if (null == {}.b)
                return void 0 !== a.b && null !== a.b;
        }
        console.log(f({
            a: [ null ],
            get b() {
                return this.a.shift();
            }
        }))""".stripMargin.trim,
      options = AllOff.copy(
        comparisons = true,
        lhsConstants = true,
        pureGetters = "strict",
        reduceVars = true
      )
    )
  }

  // =========================================================================
  // bigint_vs_number
  // =========================================================================
  test("bigint_vs_number") {
    assertCompresses(
      input = "if (-1 !== -1n) console.log(\"PASS\")",
      expected = "if (-1 !== -1n) console.log(\"PASS\")",
      options = AllOff.copy(
        comparisons = true
      )
    )
  }

}
