/*
 * Copyright (c) 2026 SSG contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * ParseNode<"spacing"> created in Parser.js from the "spacing" symbol Groups.
 *
 * Original source: katex src/functions/symbolsSpacing.ts
 * Original author: Khan Academy and contributors
 * Original license: MIT
 *
 * upstream-commit: 90de9794
 */
package ssg
package katex
package functions

import scala.collection.mutable.ArrayBuffer

import ssg.commons.Nullable
import ssg.katex.ParseError
import ssg.katex.build.BuildCommon
import ssg.katex.parse._
import ssg.katex.tree.{ MathNode, TextNode }

object SymbolsSpacingFunc {

  // A map of CSS-based spacing functions to their CSS class.
  private val cssSpace: Map[String, String] = Map(
    "\\nobreak" -> "nobreak",
    "\\allowbreak" -> "allowbreak"
  )

  // A lookup table to determine whether a spacing function/symbol should be
  // treated like a regular space character.  If a symbol or command is a key
  // in this table, then it should be a regular space character.  Furthermore,
  // the associated value may have a `className` specifying an extra CSS class
  // to add to the created `span`.
  private val regularSpace: Map[String, String] = Map(
    " " -> "",
    "\\ " -> "",
    "~" -> "nobreak",
    "\\space" -> "",
    "\\nobreakspace" -> "nobreak"
  )

  def register(): Unit =
    // ParseNode<"spacing"> created in Parser.js from the "spacing" symbol Groups in
    // src/symbols.js.
    FunctionDef.defineFunctionBuilders(
      nodeType = "spacing",
      htmlBuilder = Nullable { (group, options) =>
        val g    = group.asInstanceOf[ParseNodeSpacing]
        val opts = options.asInstanceOf[Options]
        if (regularSpace.contains(g.text)) {
          val className = regularSpace(g.text)
          // Spaces are generated by adding an actual space. Each of these
          // things has an entry in the symbols table, so these will be turned
          // into appropriate outputs.
          if (g.mode == Mode.Text) {
            val ord = BuildCommon.makeOrd(g, opts, "textord")
            ord.asInstanceOf[tree.SymbolNode].classes += className
            ord
          } else {
            BuildCommon.makeSpan(ArrayBuffer("mspace", className), ArrayBuffer(BuildCommon.mathsym(g.text, g.mode, opts)), Nullable(opts))
          }
        } else if (cssSpace.contains(g.text)) {
          // Spaces based on just a CSS class.
          BuildCommon.makeSpan(ArrayBuffer("mspace", cssSpace(g.text)), ArrayBuffer.empty, Nullable(opts))
        } else {
          throw new ParseError(s"""Unknown type of space "${g.text}"""")
        }
      },
      mathmlBuilder = Nullable { (group, options) =>
        val g = group.asInstanceOf[ParseNodeSpacing]

        if (regularSpace.contains(g.text)) {
          new MathNode("mtext", ArrayBuffer(new TextNode(" ")))
        } else if (cssSpace.contains(g.text)) {
          // CSS-based MathML spaces (\nobreak, \allowbreak) are ignored
          new MathNode("mspace")
        } else {
          throw new ParseError(s"""Unknown type of space "${g.text}"""")
        }
      }
    )
}
