/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0 */
package ssg
package commons
package io

import java.nio.file.Paths

/** ISS-980: Native FilePathPlatform path-handling bugs.
  *
  * The Native implementation (ssg-commons/src/main/scalanative/ssg/commons/io/FilePathPlatform.scala) mishandles absolute paths: `normalize` (lines 46-59) splits on "/" and drops the empty leading
  * segment, so an absolute input like "/a/../b" comes back as the relative "b"; `toAbsolute` (lines 43-44) prepends "/" instead of resolving against the working directory; `cwd` (lines 74-75) returns
  * the literal "."; `parent` (lines 14-19) returns None for "/a" because of the `lastSep <= 0` guard, instead of Some("/").
  *
  * Expected semantics are defined by the JVM reference implementation ssg-commons/src/main/scalajvm/ssg/commons/io/FilePathPlatform.scala, which wraps java.nio.file.Path:
  *   - normalize = Path.normalize() (line 41-42); per the java.nio.file.Path.normalize javadoc, redundant "." names are removed and a name followed by ".." removes both, while the root component is
  *     preserved — an absolute path stays absolute.
  *   - toAbsolute = Path.toAbsolutePath (line 38-39), which resolves relative paths against the default directory (the process working directory).
  *   - cwd = Paths.get(".").toAbsolutePath.normalize() (line 57-58).
  *   - parent = Path.getParent (line 18-21); Paths.get("/a").getParent is the root "/".
  *
  * Every hard-coded expected value below was generated by evaluating the same expression with java.nio.file.Paths on the JVM (anti-cheat C11): normalize("/a/../b") == "/b", normalize("/a/./b") ==
  * "/a/b", normalize("a/../b") == "b", normalize("/..") == "/", parent("/a") == "/", resolve("/base/dir", "../x/./y").normalize == "/base/x/y", resolve("/", "a/b").normalize == "/a/b",
  * resolve("/a/b", "c/../d").normalize == "/a/b/d".
  *
  * Red until ISS-980 is fixed. The working directory used for comparison is obtained independently of the API under test, via java.nio.file.Paths (available on Scala Native, as proven by
  * FileOpsIss977NativeSuite).
  */
final class FilePathIss980NativeSuite extends munit.FunSuite {

  /** Working directory obtained independently of FilePath, mirroring the JVM reference impl (scalajvm/ssg/commons/io/FilePathPlatform.scala:58).
    */
  private def independentCwd: String =
    Paths.get(".").toAbsolutePath.normalize().toString

  test("ISS-980: normalize keeps an absolute path absolute — /a/../b becomes /b") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:41-42 (Path.normalize);
    // JVM-evaluated: Paths.get("/a/../b").normalize() == "/b".
    assertEquals(FilePath.of("/a/../b").normalize.pathString, "/b")
  }

  test("ISS-980: normalize removes a single-dot segment without dropping the root — /a/./b becomes /a/b") {
    // JVM-evaluated: Paths.get("/a/./b").normalize() == "/a/b".
    assertEquals(FilePath.of("/a/./b").normalize.pathString, "/a/b")
  }

  test("ISS-980: normalize keeps a relative path relative — a/../b becomes b") {
    // JVM-evaluated: Paths.get("a/../b").normalize() == "b".
    assertEquals(FilePath.of("a/../b").normalize.pathString, "b")
  }

  test("ISS-980: normalize of /.. collapses to the root /") {
    // JVM-evaluated: Paths.get("/..").normalize() == "/" — the root has no parent, so a leading ".."
    // on an absolute path is discarded and the root is preserved.
    assertEquals(FilePath.of("/..").normalize.pathString, "/")
  }

  test("ISS-980: normalized absolute path reports isAbsolute") {
    // Follows from the cases above: the root component survives normalization on the JVM.
    assert(FilePath.of("/a/../b").normalize.isAbsolute)
  }

  test("ISS-980: toAbsolute resolves a relative path against the real working directory") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:38-39 (Path.toAbsolutePath resolves
    // against the default directory). On the JVM, Paths.get("rel/file.txt").toAbsolutePath ==
    // <cwd> + "/rel/file.txt".
    val cwd      = independentCwd
    val absolute = FilePath.of("rel/file.txt").toAbsolute.pathString
    assertEquals(absolute, cwd + "/rel/file.txt")
  }

  test("ISS-980: toAbsolute leaves an already-absolute path unchanged") {
    // JVM-evaluated: Paths.get("/etc/hosts").toAbsolutePath == "/etc/hosts".
    assertEquals(FilePath.of("/etc/hosts").toAbsolute.pathString, "/etc/hosts")
  }

  test("ISS-980: cwd returns the real working directory, not the literal dot") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:57-58
    // (cwd = Paths.get(".").toAbsolutePath.normalize()).
    val cwd = independentCwd
    assertEquals(FilePath.cwd.pathString, cwd)
    assertNotEquals(FilePath.cwd.pathString, ".")
    assert(FilePath.cwd.isAbsolute)
  }

  test("ISS-980: parent of /a is the root Some(/)") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:18-21 (Path.getParent);
    // JVM-evaluated: Paths.get("/a").getParent == "/".
    assertEquals(FilePath.of("/a").parent.map(_.pathString), Some("/"))
  }

  test("ISS-980: parent of the root / is None") {
    // JVM-evaluated: Paths.get("/").getParent == null, mapped to None by the JVM impl (lines 18-21).
    assertEquals(FilePath.of("/").parent.map(_.pathString), None)
  }

  test("ISS-980: resolve then normalize on an absolute base matches the JVM") {
    // JVM-evaluated round trips (anti-cheat C11):
    //   Paths.get("/base/dir").resolve("../x/./y").normalize() == "/base/x/y"
    //   Paths.get("/").resolve("a/b").normalize()              == "/a/b"
    //   Paths.get("/a/b").resolve("c/../d").normalize()        == "/a/b/d"
    assertEquals(FilePath.of("/base/dir").resolve("../x/./y").normalize.pathString, "/base/x/y")
    assertEquals(FilePath.of("/").resolve("a/b").normalize.pathString, "/a/b")
    assertEquals(FilePath.of("/a/b").resolve("c/../d").normalize.pathString, "/a/b/d")
  }
}
