/* Copyright (c) 2026 SSG contributors SPDX-License-Identifier: Apache-2.0 */
package ssg
package commons
package io

import java.nio.file.Paths

/** ISS-980: Native FilePathPlatform path-handling bugs.
  *
  * After ISS-1346 the Native impl uses OS-independent POSIX string logic: all paths use forward slashes, Windows drive-absolute paths are rendered as "/C:/..." (POSIX-absolute), and normalize uses a
  * pure-Scala POSIX dot-segment resolver (not nio). The expected values below are POSIX literals matching JVM-evaluated java.nio.file.Path expressions (anti-cheat C11). The `independentCwd` helper
  * obtains the host cwd via raw nio then POSIX-renders it (replace backslash, prefix '/' for drive-absolute) to match the OS-independent model, so the cwd/toAbsolute assertions are correct on all
  * host OSes.
  *
  * Every hard-coded expected value below was generated by evaluating the same expression with java.nio.file.Paths on the JVM (anti-cheat C11): normalize("/a/../b") == "/b", normalize("/a/./b") ==
  * "/a/b", normalize("a/../b") == "b", normalize("/..") == "/", parent("/a") == "/", resolve("/base/dir", "../x/./y").normalize == "/base/x/y", resolve("/", "a/b").normalize == "/a/b",
  * resolve("/a/b", "c/../d").normalize == "/a/b/d".
  */
final class FilePathIss980NativeSuite extends munit.FunSuite {

  /** Working directory obtained independently of FilePath, POSIX-rendered to match the OS-independent model.
    *
    * Raw nio returns the host OS form (e.g. `D:\Users\foo` on Windows). The OS-independent model uses forward slashes and prefixes '/' on drive-absolute paths (e.g. `/D:/Users/foo`). This helper
    * applies the same transform as FilePathPlatform.cwd so the comparison is valid on every host OS.
    */
  private def independentCwd: String = {
    val host = Paths.get(".").toAbsolutePath.normalize().toString.replace('\\', '/')
    if (host.startsWith("/")) host else "/" + host
  }

  test("ISS-980: normalize keeps an absolute path absolute — /a/../b becomes /b") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:41-42 (Path.normalize);
    // JVM-evaluated: Paths.get("/a/../b").normalize() == "/b".
    assertEquals(FilePath.of("/a/../b").normalize.pathString, "/b")
  }

  test("ISS-980: normalize removes a single-dot segment without dropping the root — /a/./b becomes /a/b") {
    // JVM-evaluated: Paths.get("/a/./b").normalize() == "/a/b".
    assertEquals(FilePath.of("/a/./b").normalize.pathString, "/a/b")
  }

  test("ISS-980: normalize keeps a relative path relative — a/../b becomes b") {
    // JVM-evaluated: Paths.get("a/../b").normalize() == "b".
    assertEquals(FilePath.of("a/../b").normalize.pathString, "b")
  }

  test("ISS-980: normalize of /.. collapses to the root /") {
    // JVM-evaluated: Paths.get("/..").normalize() == "/" — the root has no parent, so a leading ".."
    // on an absolute path is discarded and the root is preserved.
    assertEquals(FilePath.of("/..").normalize.pathString, "/")
  }

  test("ISS-980: normalized absolute path reports isAbsolute") {
    // Follows from the cases above: the root component survives normalization on the JVM.
    assert(FilePath.of("/a/../b").normalize.isAbsolute)
  }

  test("ISS-980: toAbsolute resolves a relative path against the real working directory") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:38-39 (Path.toAbsolutePath resolves
    // against the default directory). On the JVM, Paths.get("rel/file.txt").toAbsolutePath ==
    // <cwd> + "/rel/file.txt".
    val cwd      = independentCwd
    val absolute = FilePath.of("rel/file.txt").toAbsolute.pathString
    assertEquals(absolute, cwd + "/rel/file.txt")
  }

  test("ISS-980: toAbsolute leaves an already-absolute path unchanged") {
    // JVM-evaluated: Paths.get("/etc/hosts").toAbsolutePath == "/etc/hosts".
    assertEquals(FilePath.of("/etc/hosts").toAbsolute.pathString, "/etc/hosts")
  }

  test("ISS-980: cwd returns the real working directory, not the literal dot") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:57-58
    // (cwd = Paths.get(".").toAbsolutePath.normalize()).
    val cwd = independentCwd
    assertEquals(FilePath.cwd.pathString, cwd)
    assertNotEquals(FilePath.cwd.pathString, ".")
    assert(FilePath.cwd.isAbsolute)
  }

  test("ISS-980: parent of /a is the root Some(/)") {
    // JVM parity: scalajvm/ssg/commons/io/FilePathPlatform.scala:18-21 (Path.getParent);
    // JVM-evaluated: Paths.get("/a").getParent == "/".
    assertEquals(FilePath.of("/a").parent.map(_.pathString), Some("/"))
  }

  test("ISS-980: parent of the root / is None") {
    // JVM-evaluated: Paths.get("/").getParent == null, mapped to None by the JVM impl (lines 18-21).
    assertEquals(FilePath.of("/").parent.map(_.pathString), None)
  }

  test("ISS-980: resolve then normalize on an absolute base matches the JVM") {
    // JVM-evaluated round trips (anti-cheat C11):
    //   Paths.get("/base/dir").resolve("../x/./y").normalize() == "/base/x/y"
    //   Paths.get("/").resolve("a/b").normalize()              == "/a/b"
    //   Paths.get("/a/b").resolve("c/../d").normalize()        == "/a/b/d"
    assertEquals(FilePath.of("/base/dir").resolve("../x/./y").normalize.pathString, "/base/x/y")
    assertEquals(FilePath.of("/").resolve("a/b").normalize.pathString, "/a/b")
    assertEquals(FilePath.of("/a/b").resolve("c/../d").normalize.pathString, "/a/b/d")
  }
}
